// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myFunction_QDLDL_factor (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        linsys_solver_L_p_address0,
        linsys_solver_L_p_ce0,
        linsys_solver_L_p_we0,
        linsys_solver_L_p_d0,
        linsys_solver_L_p_q0,
        linsys_solver_bwork_address0,
        linsys_solver_bwork_ce0,
        linsys_solver_bwork_we0,
        linsys_solver_bwork_d0,
        linsys_solver_bwork_q0,
        linsys_solver_fwork_address0,
        linsys_solver_fwork_ce0,
        linsys_solver_fwork_we0,
        linsys_solver_fwork_d0,
        linsys_solver_fwork_q0,
        linsys_solver_D_address0,
        linsys_solver_D_ce0,
        linsys_solver_D_we0,
        linsys_solver_D_d0,
        linsys_solver_D_q0,
        linsys_solver_iwork_address0,
        linsys_solver_iwork_ce0,
        linsys_solver_iwork_we0,
        linsys_solver_iwork_d0,
        linsys_solver_iwork_address1,
        linsys_solver_iwork_ce1,
        linsys_solver_iwork_we1,
        linsys_solver_iwork_d1,
        linsys_solver_iwork_q1,
        linsys_solver_KKT_x_address0,
        linsys_solver_KKT_x_ce0,
        linsys_solver_KKT_x_q0,
        linsys_solver_L_x_address0,
        linsys_solver_L_x_ce0,
        linsys_solver_L_x_we0,
        linsys_solver_L_x_d0,
        linsys_solver_L_x_q0,
        linsys_solver_L_i_address0,
        linsys_solver_L_i_ce0,
        linsys_solver_L_i_we0,
        linsys_solver_L_i_d0,
        linsys_solver_L_i_q0,
        linsys_solver_Dinv_address0,
        linsys_solver_Dinv_ce0,
        linsys_solver_Dinv_we0,
        linsys_solver_Dinv_d0,
        linsys_solver_Dinv_q0
);

parameter    ap_ST_fsm_state1 = 78'd1;
parameter    ap_ST_fsm_state2 = 78'd2;
parameter    ap_ST_fsm_state3 = 78'd4;
parameter    ap_ST_fsm_state4 = 78'd8;
parameter    ap_ST_fsm_state5 = 78'd16;
parameter    ap_ST_fsm_state6 = 78'd32;
parameter    ap_ST_fsm_state7 = 78'd64;
parameter    ap_ST_fsm_state8 = 78'd128;
parameter    ap_ST_fsm_state9 = 78'd256;
parameter    ap_ST_fsm_state10 = 78'd512;
parameter    ap_ST_fsm_state11 = 78'd1024;
parameter    ap_ST_fsm_state12 = 78'd2048;
parameter    ap_ST_fsm_state13 = 78'd4096;
parameter    ap_ST_fsm_state14 = 78'd8192;
parameter    ap_ST_fsm_state15 = 78'd16384;
parameter    ap_ST_fsm_state16 = 78'd32768;
parameter    ap_ST_fsm_state17 = 78'd65536;
parameter    ap_ST_fsm_state18 = 78'd131072;
parameter    ap_ST_fsm_state19 = 78'd262144;
parameter    ap_ST_fsm_state20 = 78'd524288;
parameter    ap_ST_fsm_state21 = 78'd1048576;
parameter    ap_ST_fsm_state22 = 78'd2097152;
parameter    ap_ST_fsm_state23 = 78'd4194304;
parameter    ap_ST_fsm_state24 = 78'd8388608;
parameter    ap_ST_fsm_state25 = 78'd16777216;
parameter    ap_ST_fsm_state26 = 78'd33554432;
parameter    ap_ST_fsm_state27 = 78'd67108864;
parameter    ap_ST_fsm_state28 = 78'd134217728;
parameter    ap_ST_fsm_state29 = 78'd268435456;
parameter    ap_ST_fsm_state30 = 78'd536870912;
parameter    ap_ST_fsm_pp2_stage0 = 78'd1073741824;
parameter    ap_ST_fsm_state33 = 78'd2147483648;
parameter    ap_ST_fsm_state34 = 78'd4294967296;
parameter    ap_ST_fsm_state35 = 78'd8589934592;
parameter    ap_ST_fsm_state36 = 78'd17179869184;
parameter    ap_ST_fsm_state37 = 78'd34359738368;
parameter    ap_ST_fsm_state38 = 78'd68719476736;
parameter    ap_ST_fsm_pp3_stage0 = 78'd137438953472;
parameter    ap_ST_fsm_pp3_stage1 = 78'd274877906944;
parameter    ap_ST_fsm_pp3_stage2 = 78'd549755813888;
parameter    ap_ST_fsm_pp3_stage3 = 78'd1099511627776;
parameter    ap_ST_fsm_pp3_stage4 = 78'd2199023255552;
parameter    ap_ST_fsm_pp3_stage5 = 78'd4398046511104;
parameter    ap_ST_fsm_state51 = 78'd8796093022208;
parameter    ap_ST_fsm_state52 = 78'd17592186044416;
parameter    ap_ST_fsm_state53 = 78'd35184372088832;
parameter    ap_ST_fsm_state54 = 78'd70368744177664;
parameter    ap_ST_fsm_state55 = 78'd140737488355328;
parameter    ap_ST_fsm_state56 = 78'd281474976710656;
parameter    ap_ST_fsm_state57 = 78'd562949953421312;
parameter    ap_ST_fsm_state58 = 78'd1125899906842624;
parameter    ap_ST_fsm_state59 = 78'd2251799813685248;
parameter    ap_ST_fsm_state60 = 78'd4503599627370496;
parameter    ap_ST_fsm_state61 = 78'd9007199254740992;
parameter    ap_ST_fsm_state62 = 78'd18014398509481984;
parameter    ap_ST_fsm_state63 = 78'd36028797018963968;
parameter    ap_ST_fsm_state64 = 78'd72057594037927936;
parameter    ap_ST_fsm_state65 = 78'd144115188075855872;
parameter    ap_ST_fsm_state66 = 78'd288230376151711744;
parameter    ap_ST_fsm_state67 = 78'd576460752303423488;
parameter    ap_ST_fsm_state68 = 78'd1152921504606846976;
parameter    ap_ST_fsm_state69 = 78'd2305843009213693952;
parameter    ap_ST_fsm_state70 = 78'd4611686018427387904;
parameter    ap_ST_fsm_state71 = 78'd9223372036854775808;
parameter    ap_ST_fsm_state72 = 78'd18446744073709551616;
parameter    ap_ST_fsm_state73 = 78'd36893488147419103232;
parameter    ap_ST_fsm_state74 = 78'd73786976294838206464;
parameter    ap_ST_fsm_state75 = 78'd147573952589676412928;
parameter    ap_ST_fsm_state76 = 78'd295147905179352825856;
parameter    ap_ST_fsm_state77 = 78'd590295810358705651712;
parameter    ap_ST_fsm_state78 = 78'd1180591620717411303424;
parameter    ap_ST_fsm_state79 = 78'd2361183241434822606848;
parameter    ap_ST_fsm_state80 = 78'd4722366482869645213696;
parameter    ap_ST_fsm_state81 = 78'd9444732965739290427392;
parameter    ap_ST_fsm_state82 = 78'd18889465931478580854784;
parameter    ap_ST_fsm_state83 = 78'd37778931862957161709568;
parameter    ap_ST_fsm_state84 = 78'd75557863725914323419136;
parameter    ap_ST_fsm_state85 = 78'd151115727451828646838272;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] linsys_solver_L_p_address0;
output   linsys_solver_L_p_ce0;
output   linsys_solver_L_p_we0;
output  [5:0] linsys_solver_L_p_d0;
input  [5:0] linsys_solver_L_p_q0;
output  [5:0] linsys_solver_bwork_address0;
output   linsys_solver_bwork_ce0;
output   linsys_solver_bwork_we0;
output  [0:0] linsys_solver_bwork_d0;
input  [0:0] linsys_solver_bwork_q0;
output  [5:0] linsys_solver_fwork_address0;
output   linsys_solver_fwork_ce0;
output   linsys_solver_fwork_we0;
output  [31:0] linsys_solver_fwork_d0;
input  [31:0] linsys_solver_fwork_q0;
output  [5:0] linsys_solver_D_address0;
output   linsys_solver_D_ce0;
output   linsys_solver_D_we0;
output  [31:0] linsys_solver_D_d0;
input  [31:0] linsys_solver_D_q0;
output  [6:0] linsys_solver_iwork_address0;
output   linsys_solver_iwork_ce0;
output   linsys_solver_iwork_we0;
output  [5:0] linsys_solver_iwork_d0;
output  [6:0] linsys_solver_iwork_address1;
output   linsys_solver_iwork_ce1;
output   linsys_solver_iwork_we1;
output  [5:0] linsys_solver_iwork_d1;
input  [5:0] linsys_solver_iwork_q1;
output  [6:0] linsys_solver_KKT_x_address0;
output   linsys_solver_KKT_x_ce0;
input  [31:0] linsys_solver_KKT_x_q0;
output  [5:0] linsys_solver_L_x_address0;
output   linsys_solver_L_x_ce0;
output   linsys_solver_L_x_we0;
output  [31:0] linsys_solver_L_x_d0;
input  [31:0] linsys_solver_L_x_q0;
output  [5:0] linsys_solver_L_i_address0;
output   linsys_solver_L_i_ce0;
output   linsys_solver_L_i_we0;
output  [5:0] linsys_solver_L_i_d0;
input  [5:0] linsys_solver_L_i_q0;
output  [5:0] linsys_solver_Dinv_address0;
output   linsys_solver_Dinv_ce0;
output   linsys_solver_Dinv_we0;
output  [31:0] linsys_solver_Dinv_d0;
input  [31:0] linsys_solver_Dinv_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] linsys_solver_L_p_address0;
reg linsys_solver_L_p_ce0;
reg linsys_solver_L_p_we0;
reg[5:0] linsys_solver_bwork_address0;
reg linsys_solver_bwork_ce0;
reg linsys_solver_bwork_we0;
reg[0:0] linsys_solver_bwork_d0;
reg[5:0] linsys_solver_fwork_address0;
reg linsys_solver_fwork_ce0;
reg linsys_solver_fwork_we0;
reg[31:0] linsys_solver_fwork_d0;
reg[5:0] linsys_solver_D_address0;
reg linsys_solver_D_ce0;
reg linsys_solver_D_we0;
reg[31:0] linsys_solver_D_d0;
reg[6:0] linsys_solver_iwork_address0;
reg linsys_solver_iwork_ce0;
reg linsys_solver_iwork_we0;
reg[5:0] linsys_solver_iwork_d0;
reg[6:0] linsys_solver_iwork_address1;
reg linsys_solver_iwork_ce1;
reg linsys_solver_iwork_we1;
reg[6:0] linsys_solver_KKT_x_address0;
reg linsys_solver_KKT_x_ce0;
reg[5:0] linsys_solver_L_x_address0;
reg linsys_solver_L_x_ce0;
reg linsys_solver_L_x_we0;
reg[5:0] linsys_solver_L_i_address0;
reg linsys_solver_L_i_ce0;
reg linsys_solver_L_i_we0;
reg[5:0] linsys_solver_Dinv_address0;
reg linsys_solver_Dinv_ce0;
reg linsys_solver_Dinv_we0;

(* fsm_encoding = "none" *) reg   [77:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] linsys_solver_KKT_p_address0;
reg    linsys_solver_KKT_p_ce0;
wire   [6:0] linsys_solver_KKT_p_q0;
wire   [5:0] linsys_solver_KKT_p_address1;
reg    linsys_solver_KKT_p_ce1;
wire   [6:0] linsys_solver_KKT_p_q1;
wire   [6:0] linsys_solver_KKT_i_address0;
reg    linsys_solver_KKT_i_ce0;
wire   [5:0] linsys_solver_KKT_i_q0;
reg   [63:0] nnzE_2_reg_478;
reg   [63:0] nnzY_1_reg_488;
reg   [63:0] j_15_reg_535;
wire   [31:0] grp_fu_556_p2;
reg   [31:0] reg_566;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state84;
wire   [31:0] grp_fu_552_p2;
reg   [31:0] reg_571;
wire    ap_CS_fsm_pp3_stage5;
reg    ap_enable_reg_pp3_iter0;
wire    ap_block_state44_pp3_stage5_iter0;
wire    ap_block_state50_pp3_stage5_iter1;
wire    ap_block_pp3_stage5_11001;
reg   [0:0] icmp_ln199_reg_1195;
wire    ap_CS_fsm_state56;
wire    ap_CS_fsm_state60;
wire   [5:0] i_fu_578_p2;
wire    ap_CS_fsm_state2;
reg   [31:0] linsys_solver_KKT_x_load_reg_1001;
wire    ap_CS_fsm_state4;
wire   [0:0] and_ln120_fu_652_p2;
reg   [0:0] and_ln120_reg_1008;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln126_fu_658_p2;
reg   [0:0] icmp_ln126_reg_1012;
wire    ap_CS_fsm_state23;
wire   [63:0] zext_ln126_fu_664_p1;
reg   [63:0] zext_ln126_reg_1016;
wire   [5:0] k_3_fu_669_p2;
reg   [5:0] k_3_reg_1022;
wire   [63:0] zext_ln87_fu_680_p1;
reg   [63:0] zext_ln87_reg_1037;
wire    ap_CS_fsm_state24;
wire   [63:0] zext_ln87_1_fu_684_p1;
reg   [5:0] linsys_solver_D_addr_1_reg_1047;
wire   [0:0] icmp_ln142_fu_688_p2;
reg   [0:0] icmp_ln142_reg_1052;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln142_1_fu_694_p2;
wire   [0:0] icmp_ln190_fu_699_p2;
reg   [0:0] icmp_ln190_reg_1069;
reg   [5:0] bidx_reg_1073;
wire    ap_CS_fsm_state26;
wire   [0:0] icmp_ln150_fu_711_p2;
reg   [0:0] icmp_ln150_reg_1078;
reg   [5:0] linsys_solver_bwork_addr_1_reg_1082;
reg   [0:0] linsys_solver_bwork_load_reg_1087;
wire    ap_CS_fsm_state27;
wire   [63:0] nnzE_1_fu_717_p2;
wire    ap_CS_fsm_state29;
wire   [0:0] icmp_ln182_fu_748_p2;
reg   [0:0] icmp_ln182_reg_1099;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state31_pp2_stage0_iter0;
wire    ap_block_state32_pp2_stage0_iter1;
wire    ap_block_pp2_stage0_11001;
wire   [63:0] nnzE_3_fu_758_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [63:0] zext_ln183_fu_770_p1;
reg   [63:0] zext_ln183_reg_1108;
wire   [63:0] nnzY_2_fu_795_p2;
reg    ap_enable_reg_pp2_iter1;
wire   [63:0] add_ln182_fu_811_p2;
wire    ap_CS_fsm_state33;
wire   [63:0] i_100_fu_817_p2;
reg   [63:0] i_100_reg_1128;
wire    ap_CS_fsm_state35;
wire   [63:0] i_99_fu_829_p2;
reg   [63:0] i_99_reg_1141;
wire    ap_CS_fsm_state36;
wire   [0:0] icmp_ln190_1_fu_823_p2;
wire   [63:0] zext_ln87_3_fu_846_p1;
reg   [63:0] zext_ln87_3_reg_1151;
wire    ap_CS_fsm_state37;
reg   [6:0] linsys_solver_iwork_addr_2_reg_1157;
reg   [5:0] linsys_solver_fwork_addr_2_reg_1162;
reg   [5:0] tmpIdx_1_reg_1172;
wire    ap_CS_fsm_state38;
wire   [63:0] zext_ln87_5_fu_867_p1;
reg   [63:0] zext_ln87_5_reg_1177;
reg   [31:0] yVals_cidx_reg_1184;
wire   [63:0] zext_ln87_6_fu_871_p1;
wire   [0:0] icmp_ln199_fu_875_p2;
wire    ap_CS_fsm_pp3_stage0;
wire    ap_block_state39_pp3_stage0_iter0;
wire    ap_block_state45_pp3_stage0_iter1;
wire    ap_block_pp3_stage0_11001;
reg   [0:0] icmp_ln199_reg_1195_pp3_iter1_reg;
reg   [31:0] linsys_solver_L_x_load_reg_1209;
wire    ap_CS_fsm_pp3_stage1;
wire    ap_block_state40_pp3_stage1_iter0;
wire    ap_block_state46_pp3_stage1_iter1;
wire    ap_block_pp3_stage1_11001;
reg   [5:0] linsys_solver_fwork_addr_3_reg_1214;
reg   [5:0] linsys_solver_fwork_addr_3_reg_1214_pp3_iter1_reg;
wire   [0:0] addr_cmp16_fu_888_p2;
reg   [0:0] addr_cmp16_reg_1219;
reg   [31:0] linsys_solver_fwork_load_reg_1224;
wire    ap_CS_fsm_pp3_stage2;
wire    ap_block_state41_pp3_stage2_iter0;
wire    ap_block_state47_pp3_stage2_iter1;
wire    ap_block_pp3_stage2_11001;
wire   [31:0] reuse_select17_fu_902_p3;
reg   [31:0] reuse_select17_reg_1229;
wire   [63:0] j_16_fu_908_p2;
reg   [63:0] j_16_reg_1234;
wire   [31:0] grp_fu_547_p2;
reg   [31:0] sub_reg_1239;
wire    ap_CS_fsm_pp3_stage4;
reg    ap_enable_reg_pp3_iter1;
wire    ap_block_state43_pp3_stage4_iter0;
wire    ap_block_state49_pp3_stage4_iter1;
wire    ap_block_pp3_stage4_11001;
wire    ap_CS_fsm_state51;
reg   [31:0] linsys_solver_Dinv_load_reg_1250;
wire    ap_CS_fsm_state52;
wire    ap_CS_fsm_state65;
reg   [31:0] linsys_solver_D_load_1_reg_1260;
wire    ap_CS_fsm_state67;
wire    ap_CS_fsm_state30;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_flush_enable;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state39;
wire    ap_block_pp3_stage5_subdone;
reg   [5:0] i_072_reg_418;
wire   [0:0] icmp_ln104_fu_584_p2;
reg   [5:0] k_reg_429;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state85;
reg   [63:0] nnzY_reg_442;
wire    ap_CS_fsm_state34;
reg   [63:0] i_98_reg_454;
reg   [63:0] nnzE_reg_466;
reg   [63:0] nnzY_3_reg_499;
reg   [31:0] empty_134_reg_514;
reg   [63:0] i_266_in_reg_525;
reg   [63:0] ap_phi_mux_j_15_phi_fu_538_p4;
wire    ap_block_pp3_stage0;
wire   [63:0] zext_ln107_fu_601_p1;
wire   [63:0] i_072_cast1_fu_590_p1;
wire   [63:0] zext_ln115_fu_612_p1;
wire   [63:0] zext_ln140_fu_675_p1;
wire   [63:0] zext_ln87_2_fu_705_p1;
wire   [63:0] zext_ln174_fu_733_p1;
wire    ap_block_pp2_stage0;
wire   [63:0] zext_ln197_fu_862_p1;
wire   [63:0] zext_ln200_fu_880_p1;
wire    ap_block_pp3_stage1;
wire    ap_CS_fsm_state57;
reg   [63:0] reuse_addr_reg13_fu_110;
reg   [31:0] reuse_reg12_fu_114;
reg   [31:0] ap_sig_allocacmp_reuse_reg12_load;
wire    ap_block_pp3_stage5;
reg   [63:0] reuse_addr_reg_fu_118;
reg   [5:0] reuse_reg_fu_122;
wire   [5:0] reuse_select_fu_786_p3;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state66;
wire    ap_CS_fsm_state3;
reg   [31:0] grp_fu_547_p0;
wire    ap_CS_fsm_state61;
reg   [31:0] grp_fu_552_p0;
reg   [31:0] grp_fu_552_p1;
wire    ap_block_pp3_stage2;
wire    ap_CS_fsm_state53;
reg   [31:0] grp_fu_556_p1;
wire    ap_CS_fsm_state69;
reg   [31:0] grp_fu_561_p0;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state68;
wire   [6:0] i_072_cast_fu_597_p1;
wire   [6:0] add_ln115_fu_606_p2;
wire   [31:0] bitcast_ln120_fu_617_p1;
wire   [7:0] tmp_fu_620_p4;
wire   [22:0] trunc_ln120_fu_630_p1;
wire   [0:0] icmp_ln120_1_fu_640_p2;
wire   [0:0] icmp_ln120_fu_634_p2;
wire   [0:0] or_ln120_fu_646_p2;
wire   [0:0] grp_fu_561_p2;
wire   [6:0] trunc_ln87_fu_723_p1;
wire   [6:0] add_ln174_fu_727_p2;
wire   [6:0] empty_133_fu_754_p1;
wire   [6:0] add_ln183_1_fu_764_p2;
wire   [0:0] addr_cmp_fu_781_p2;
wire   [6:0] zext_ln87_4_fu_852_p1;
wire   [6:0] add_ln197_fu_856_p2;
wire   [31:0] bitcast_ln223_fu_924_p1;
wire   [7:0] tmp_90_fu_927_p4;
wire   [22:0] trunc_ln223_fu_937_p1;
wire   [0:0] icmp_ln223_1_fu_947_p2;
wire   [0:0] icmp_ln223_fu_941_p2;
wire   [0:0] or_ln223_fu_953_p2;
wire   [0:0] and_ln223_fu_959_p2;
reg   [77:0] ap_NS_fsm;
wire    ap_block_pp3_stage1_subdone;
wire    ap_block_pp3_stage2_subdone;
wire    ap_block_state42_pp3_stage3_iter0;
wire    ap_block_state48_pp3_stage3_iter1;
wire    ap_block_pp3_stage3_subdone;
wire    ap_block_pp3_stage4_subdone;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 78'd1;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
end

myFunction_QDLDL_factor_linsys_solver_KKT_p #(
    .DataWidth( 7 ),
    .AddressRange( 35 ),
    .AddressWidth( 6 ))
linsys_solver_KKT_p_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linsys_solver_KKT_p_address0),
    .ce0(linsys_solver_KKT_p_ce0),
    .q0(linsys_solver_KKT_p_q0),
    .address1(linsys_solver_KKT_p_address1),
    .ce1(linsys_solver_KKT_p_ce1),
    .q1(linsys_solver_KKT_p_q1)
);

myFunction_QDLDL_factor_linsys_solver_KKT_i #(
    .DataWidth( 6 ),
    .AddressRange( 79 ),
    .AddressWidth( 7 ))
linsys_solver_KKT_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linsys_solver_KKT_i_address0),
    .ce0(linsys_solver_KKT_i_ce0),
    .q0(linsys_solver_KKT_i_q0)
);

myFunction_fsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_5_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_547_p0),
    .din1(reg_571),
    .ce(1'b1),
    .dout(grp_fu_547_p2)
);

myFunction_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_552_p0),
    .din1(grp_fu_552_p1),
    .ce(1'b1),
    .dout(grp_fu_552_p2)
);

myFunction_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1065353216),
    .din1(grp_fu_556_p1),
    .ce(1'b1),
    .dout(grp_fu_556_p2)
);

myFunction_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_561_p0),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd1),
    .dout(grp_fu_561_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp2_flush_enable)) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state30)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state30)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage0_subdone) & (1'b1 == ap_condition_pp3_exit_iter0_state39) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state38)) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp3_stage5_subdone) & (1'b1 == ap_CS_fsm_pp3_stage5))) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end else if ((1'b1 == ap_CS_fsm_state38)) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state65)) begin
        empty_134_reg_514 <= grp_fu_547_p2;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        empty_134_reg_514 <= linsys_solver_D_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln104_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_072_reg_418 <= i_fu_578_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_072_reg_418 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state65)) begin
        i_266_in_reg_525 <= i_99_reg_1141;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        i_266_in_reg_525 <= nnzY_reg_442;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln142_fu_688_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        i_98_reg_454 <= zext_ln87_1_fu_684_p1;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        i_98_reg_454 <= i_100_reg_1128;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        j_15_reg_535 <= j_16_reg_1234;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        j_15_reg_535 <= zext_ln87_6_fu_871_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state85)) begin
        k_reg_429 <= k_3_reg_1022;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        k_reg_429 <= 6'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        nnzE_2_reg_478 <= nnzE_reg_466;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln182_fu_748_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        nnzE_2_reg_478 <= nnzE_3_fu_758_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((linsys_solver_bwork_q0 == 1'd0)) begin
        if ((1'b1 == ap_CS_fsm_state29)) begin
            nnzE_reg_466 <= nnzE_1_fu_717_p2;
        end else if ((1'b1 == ap_CS_fsm_state27)) begin
            nnzE_reg_466 <= 64'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        nnzY_1_reg_488 <= nnzY_reg_442;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln182_reg_1099 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        nnzY_1_reg_488 <= nnzY_2_fu_795_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((linsys_solver_bwork_load_reg_1087 == 1'd0) & (icmp_ln150_reg_1078 == 1'd0) & (1'b1 == ap_CS_fsm_state33))) begin
        nnzY_3_reg_499 <= add_ln182_fu_811_p2;
    end else if ((((icmp_ln150_fu_711_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26)) | ((1'b1 == ap_CS_fsm_state27) & (linsys_solver_bwork_q0 == 1'd1)))) begin
        nnzY_3_reg_499 <= nnzY_reg_442;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln142_fu_688_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        nnzY_reg_442 <= 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        nnzY_reg_442 <= nnzY_3_reg_499;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln190_1_fu_823_p2 == 1'd1) & (icmp_ln190_reg_1069 == 1'd1) & (icmp_ln142_reg_1052 == 1'd1) & (1'b1 == ap_CS_fsm_state36))) begin
        reuse_addr_reg13_fu_110 <= 64'd18446744073709551615;
    end else if (((icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage1_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
        reuse_addr_reg13_fu_110 <= zext_ln200_fu_880_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        reuse_addr_reg_fu_118 <= 64'd18446744073709551615;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln182_reg_1099 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        reuse_addr_reg_fu_118 <= nnzY_1_reg_488;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln190_1_fu_823_p2 == 1'd1) & (icmp_ln190_reg_1069 == 1'd1) & (icmp_ln142_reg_1052 == 1'd1) & (1'b1 == ap_CS_fsm_state36))) begin
        reuse_reg12_fu_114 <= 32'd0;
    end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln199_reg_1195_pp3_iter1_reg == 1'd1) & (1'b0 == ap_block_pp3_stage5_11001) & (1'b1 == ap_CS_fsm_pp3_stage5))) begin
        reuse_reg12_fu_114 <= sub_reg_1239;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        reuse_reg_fu_122 <= 6'd0;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln182_reg_1099 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        reuse_reg_fu_122 <= reuse_select_fu_786_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage1_11001) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
        addr_cmp16_reg_1219 <= addr_cmp16_fu_888_p2;
        linsys_solver_fwork_addr_3_reg_1214 <= zext_ln200_fu_880_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        and_ln120_reg_1008 <= and_ln120_fu_652_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        bidx_reg_1073 <= linsys_solver_KKT_i_q0;
        icmp_ln150_reg_1078 <= icmp_ln150_fu_711_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        i_100_reg_1128 <= i_100_fu_817_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln190_1_fu_823_p2 == 1'd1) & (icmp_ln190_reg_1069 == 1'd1) & (icmp_ln142_reg_1052 == 1'd1) & (1'b1 == ap_CS_fsm_state36))) begin
        i_99_reg_1141 <= i_99_fu_829_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        icmp_ln126_reg_1012 <= icmp_ln126_fu_658_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        icmp_ln142_reg_1052 <= icmp_ln142_fu_688_p2;
        linsys_solver_D_addr_1_reg_1047 <= zext_ln126_reg_1016;
        zext_ln87_reg_1037[6 : 0] <= zext_ln87_fu_680_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln182_reg_1099 <= icmp_ln182_fu_748_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln142_1_fu_694_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        icmp_ln190_reg_1069 <= icmp_ln190_fu_699_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage0_11001) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        icmp_ln199_reg_1195 <= icmp_ln199_fu_875_p2;
        icmp_ln199_reg_1195_pp3_iter1_reg <= icmp_ln199_reg_1195;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage5_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage5))) begin
        j_16_reg_1234 <= j_16_fu_908_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln126_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
        k_3_reg_1022 <= k_3_fu_669_p2;
        zext_ln126_reg_1016[5 : 0] <= zext_ln126_fu_664_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state67)) begin
        linsys_solver_D_load_1_reg_1260 <= linsys_solver_D_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        linsys_solver_Dinv_load_reg_1250 <= linsys_solver_Dinv_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        linsys_solver_KKT_x_load_reg_1001 <= linsys_solver_KKT_x_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage1_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
        linsys_solver_L_x_load_reg_1209 <= linsys_solver_L_x_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln150_fu_711_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26))) begin
        linsys_solver_bwork_addr_1_reg_1082 <= zext_ln87_2_fu_705_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        linsys_solver_bwork_load_reg_1087 <= linsys_solver_bwork_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        linsys_solver_fwork_addr_2_reg_1162 <= zext_ln87_3_fu_846_p1;
        linsys_solver_iwork_addr_2_reg_1157 <= zext_ln197_fu_862_p1;
        zext_ln87_3_reg_1151[5 : 0] <= zext_ln87_3_fu_846_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp3_stage1_11001) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
        linsys_solver_fwork_addr_3_reg_1214_pp3_iter1_reg <= linsys_solver_fwork_addr_3_reg_1214;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage2_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage2))) begin
        linsys_solver_fwork_load_reg_1224 <= linsys_solver_fwork_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state21))) begin
        reg_566 <= grp_fu_556_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state56) | ((icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage5_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage5)))) begin
        reg_571 <= grp_fu_552_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage5_11001) & (1'b1 == ap_CS_fsm_pp3_stage5))) begin
        reuse_select17_reg_1229 <= reuse_select17_fu_902_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln199_reg_1195_pp3_iter1_reg == 1'd1) & (1'b0 == ap_block_pp3_stage4_11001) & (1'b1 == ap_CS_fsm_pp3_stage4))) begin
        sub_reg_1239 <= grp_fu_547_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        tmpIdx_1_reg_1172 <= linsys_solver_iwork_q1;
        yVals_cidx_reg_1184 <= linsys_solver_fwork_q0;
        zext_ln87_5_reg_1177[5 : 0] <= zext_ln87_5_fu_867_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln182_fu_748_p2 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        zext_ln183_reg_1108[6 : 0] <= zext_ln183_fu_770_p1[6 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln182_fu_748_p2 == 1'd1) & (1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_condition_pp2_flush_enable = 1'b1;
    end else begin
        ap_condition_pp2_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln199_fu_875_p2 == 1'd0)) begin
        ap_condition_pp3_exit_iter0_state39 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state39 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state69) & ((1'd1 == and_ln120_reg_1008) | ((icmp_ln126_reg_1012 == 1'd0) | (1'd1 == and_ln223_fu_959_p2)))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln199_reg_1195 == 1'd1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        ap_phi_mux_j_15_phi_fu_538_p4 = j_16_reg_1234;
    end else begin
        ap_phi_mux_j_15_phi_fu_538_p4 = j_15_reg_535;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state69) & ((1'd1 == and_ln120_reg_1008) | ((icmp_ln126_reg_1012 == 1'd0) | (1'd1 == and_ln223_fu_959_p2))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln199_reg_1195_pp3_iter1_reg == 1'd1) & (1'b0 == ap_block_pp3_stage5) & (1'b1 == ap_CS_fsm_pp3_stage5))) begin
        ap_sig_allocacmp_reuse_reg12_load = sub_reg_1239;
    end else begin
        ap_sig_allocacmp_reuse_reg12_load = reuse_reg12_fu_114;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        grp_fu_547_p0 = empty_134_reg_514;
    end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage0) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        grp_fu_547_p0 = reuse_select17_reg_1229;
    end else begin
        grp_fu_547_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state57))) begin
        grp_fu_552_p0 = yVals_cidx_reg_1184;
    end else if (((1'b0 == ap_block_pp3_stage2) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage2))) begin
        grp_fu_552_p0 = linsys_solver_L_x_load_reg_1209;
    end else begin
        grp_fu_552_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        grp_fu_552_p1 = reg_571;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        grp_fu_552_p1 = linsys_solver_Dinv_load_reg_1250;
    end else if (((1'b0 == ap_block_pp3_stage2) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage2))) begin
        grp_fu_552_p1 = yVals_cidx_reg_1184;
    end else begin
        grp_fu_552_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        grp_fu_556_p1 = linsys_solver_D_load_1_reg_1260;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_556_p1 = linsys_solver_KKT_x_load_reg_1001;
    end else begin
        grp_fu_556_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        grp_fu_561_p0 = linsys_solver_D_load_1_reg_1260;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_561_p0 = linsys_solver_KKT_x_load_reg_1001;
    end else begin
        grp_fu_561_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25))) begin
        linsys_solver_D_address0 = linsys_solver_D_addr_1_reg_1047;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linsys_solver_D_address0 = 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        linsys_solver_D_address0 = i_072_cast1_fu_590_p1;
    end else begin
        linsys_solver_D_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        linsys_solver_D_ce0 = 1'b1;
    end else begin
        linsys_solver_D_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        linsys_solver_D_d0 = empty_134_reg_514;
    end else if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state4))) begin
        linsys_solver_D_d0 = linsys_solver_KKT_x_q0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        linsys_solver_D_d0 = 32'd0;
    end else begin
        linsys_solver_D_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((icmp_ln190_1_fu_823_p2 == 1'd0) & (icmp_ln190_reg_1069 == 1'd1) & (icmp_ln142_reg_1052 == 1'd1) & (1'b1 == ap_CS_fsm_state36)) | ((icmp_ln150_fu_711_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26)) | ((icmp_ln104_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        linsys_solver_D_we0 = 1'b1;
    end else begin
        linsys_solver_D_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state85)) begin
        linsys_solver_Dinv_address0 = zext_ln126_reg_1016;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        linsys_solver_Dinv_address0 = zext_ln87_3_reg_1151;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        linsys_solver_Dinv_address0 = 6'd0;
    end else begin
        linsys_solver_Dinv_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state85) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state51))) begin
        linsys_solver_Dinv_ce0 = 1'b1;
    end else begin
        linsys_solver_Dinv_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state85) | (1'b1 == ap_CS_fsm_state22))) begin
        linsys_solver_Dinv_we0 = 1'b1;
    end else begin
        linsys_solver_Dinv_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        linsys_solver_KKT_i_ce0 = 1'b1;
    end else begin
        linsys_solver_KKT_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        linsys_solver_KKT_p_ce0 = 1'b1;
    end else begin
        linsys_solver_KKT_p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        linsys_solver_KKT_p_ce1 = 1'b1;
    end else begin
        linsys_solver_KKT_p_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        linsys_solver_KKT_x_address0 = i_98_reg_454;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        linsys_solver_KKT_x_address0 = 7'd0;
    end else begin
        linsys_solver_KKT_x_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state25))) begin
        linsys_solver_KKT_x_ce0 = 1'b1;
    end else begin
        linsys_solver_KKT_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        linsys_solver_L_i_address0 = zext_ln87_5_reg_1177;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        linsys_solver_L_i_address0 = ap_phi_mux_j_15_phi_fu_538_p4;
    end else begin
        linsys_solver_L_i_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        linsys_solver_L_i_ce0 = 1'b1;
    end else begin
        linsys_solver_L_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        linsys_solver_L_i_we0 = 1'b1;
    end else begin
        linsys_solver_L_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        linsys_solver_L_p_address0 = zext_ln87_3_fu_846_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        linsys_solver_L_p_address0 = zext_ln107_fu_601_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        linsys_solver_L_p_address0 = 6'd0;
    end else begin
        linsys_solver_L_p_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        linsys_solver_L_p_ce0 = 1'b1;
    end else begin
        linsys_solver_L_p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln104_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        linsys_solver_L_p_we0 = 1'b1;
    end else begin
        linsys_solver_L_p_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        linsys_solver_L_x_address0 = zext_ln87_5_reg_1177;
    end else if (((1'b0 == ap_block_pp3_stage0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0))) begin
        linsys_solver_L_x_address0 = ap_phi_mux_j_15_phi_fu_538_p4;
    end else begin
        linsys_solver_L_x_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | ((1'b0 == ap_block_pp3_stage0_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0)))) begin
        linsys_solver_L_x_ce0 = 1'b1;
    end else begin
        linsys_solver_L_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        linsys_solver_L_x_we0 = 1'b1;
    end else begin
        linsys_solver_L_x_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        linsys_solver_bwork_address0 = zext_ln87_3_reg_1151;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state29))) begin
        linsys_solver_bwork_address0 = 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        linsys_solver_bwork_address0 = linsys_solver_bwork_addr_1_reg_1082;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        linsys_solver_bwork_address0 = zext_ln87_2_fu_705_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        linsys_solver_bwork_address0 = i_072_cast1_fu_590_p1;
    end else begin
        linsys_solver_bwork_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state2))) begin
        linsys_solver_bwork_ce0 = 1'b1;
    end else begin
        linsys_solver_bwork_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state27))) begin
        linsys_solver_bwork_d0 = 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state2))) begin
        linsys_solver_bwork_d0 = 1'd0;
    end else begin
        linsys_solver_bwork_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | ((icmp_ln104_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state29) & (linsys_solver_bwork_q0 == 1'd0)) | ((1'b1 == ap_CS_fsm_state27) & (linsys_solver_bwork_q0 == 1'd0)))) begin
        linsys_solver_bwork_we0 = 1'b1;
    end else begin
        linsys_solver_bwork_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        linsys_solver_fwork_address0 = linsys_solver_fwork_addr_2_reg_1162;
    end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage5) & (1'b1 == ap_CS_fsm_pp3_stage5))) begin
        linsys_solver_fwork_address0 = linsys_solver_fwork_addr_3_reg_1214_pp3_iter1_reg;
    end else if (((1'b0 == ap_block_pp3_stage1) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1))) begin
        linsys_solver_fwork_address0 = zext_ln200_fu_880_p1;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        linsys_solver_fwork_address0 = zext_ln87_3_fu_846_p1;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        linsys_solver_fwork_address0 = zext_ln87_2_fu_705_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        linsys_solver_fwork_address0 = i_072_cast1_fu_590_p1;
    end else begin
        linsys_solver_fwork_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state2) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage5_11001) & (1'b1 == ap_CS_fsm_pp3_stage5)) | ((1'b0 == ap_block_pp3_stage1_11001) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage1)))) begin
        linsys_solver_fwork_ce0 = 1'b1;
    end else begin
        linsys_solver_fwork_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage5) & (1'b1 == ap_CS_fsm_pp3_stage5))) begin
        linsys_solver_fwork_d0 = sub_reg_1239;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        linsys_solver_fwork_d0 = linsys_solver_KKT_x_q0;
    end else if (((1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state2))) begin
        linsys_solver_fwork_d0 = 32'd0;
    end else begin
        linsys_solver_fwork_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | ((icmp_ln104_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln199_reg_1195_pp3_iter1_reg == 1'd1) & (1'b0 == ap_block_pp3_stage5_11001) & (1'b1 == ap_CS_fsm_pp3_stage5)) | ((icmp_ln150_fu_711_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26)))) begin
        linsys_solver_fwork_we0 = 1'b1;
    end else begin
        linsys_solver_fwork_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        linsys_solver_iwork_address0 = nnzY_1_reg_488;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        linsys_solver_iwork_address0 = zext_ln174_fu_733_p1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        linsys_solver_iwork_address0 = 7'd34;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        linsys_solver_iwork_address0 = zext_ln115_fu_612_p1;
    end else begin
        linsys_solver_iwork_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        linsys_solver_iwork_address1 = linsys_solver_iwork_addr_2_reg_1157;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        linsys_solver_iwork_address1 = zext_ln197_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        linsys_solver_iwork_address1 = i_99_fu_829_p2;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        linsys_solver_iwork_address1 = zext_ln183_fu_770_p1;
    end else begin
        linsys_solver_iwork_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state2) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        linsys_solver_iwork_ce0 = 1'b1;
    end else begin
        linsys_solver_iwork_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state36) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        linsys_solver_iwork_ce1 = 1'b1;
    end else begin
        linsys_solver_iwork_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        linsys_solver_iwork_d0 = reuse_select_fu_786_p3;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        linsys_solver_iwork_d0 = bidx_reg_1073;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state2))) begin
        linsys_solver_iwork_d0 = 6'd0;
    end else begin
        linsys_solver_iwork_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln104_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln182_reg_1099 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b1 == ap_CS_fsm_state29) & (linsys_solver_bwork_q0 == 1'd0)) | ((1'b1 == ap_CS_fsm_state27) & (linsys_solver_bwork_q0 == 1'd0)))) begin
        linsys_solver_iwork_we0 = 1'b1;
    end else begin
        linsys_solver_iwork_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        linsys_solver_iwork_we1 = 1'b1;
    end else begin
        linsys_solver_iwork_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln104_fu_584_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'd1 == and_ln120_fu_652_p2) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((icmp_ln126_fu_658_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state69;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((icmp_ln142_fu_688_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln190_fu_699_p2 == 1'd0) & (icmp_ln142_1_fu_694_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else if (((icmp_ln190_fu_699_p2 == 1'd1) & (icmp_ln142_1_fu_694_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((icmp_ln150_fu_711_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((1'b1 == ap_CS_fsm_state27) & (linsys_solver_bwork_q0 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((1'b1 == ap_CS_fsm_state29) & (linsys_solver_bwork_q0 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((ap_enable_reg_pp2_iter1 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b0) & (1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            if (((1'b1 == ap_CS_fsm_state36) & ((icmp_ln142_reg_1052 == 1'd0) | ((icmp_ln190_1_fu_823_p2 == 1'd0) | (icmp_ln190_reg_1069 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state66;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_pp3_stage0;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if ((~((ap_enable_reg_pp3_iter1 == 1'b0) & (icmp_ln199_fu_875_p2 == 1'd0) & (1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter0 == 1'b1)) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage1;
            end else if (((ap_enable_reg_pp3_iter1 == 1'b0) & (icmp_ln199_fu_875_p2 == 1'd0) & (1'b0 == ap_block_pp3_stage0_subdone) & (ap_enable_reg_pp3_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_pp3_stage1 : begin
            if ((1'b0 == ap_block_pp3_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage1;
            end
        end
        ap_ST_fsm_pp3_stage2 : begin
            if ((1'b0 == ap_block_pp3_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage2;
            end
        end
        ap_ST_fsm_pp3_stage3 : begin
            if ((1'b0 == ap_block_pp3_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage3;
            end
        end
        ap_ST_fsm_pp3_stage4 : begin
            if ((1'b0 == ap_block_pp3_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage4;
            end
        end
        ap_ST_fsm_pp3_stage5 : begin
            if ((~((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage5_subdone) & (ap_enable_reg_pp3_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp3_stage5)) & (1'b0 == ap_block_pp3_stage5_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b0 == ap_block_pp3_stage5_subdone) & (ap_enable_reg_pp3_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp3_stage5))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage5;
            end
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            if (((1'b1 == ap_CS_fsm_state69) & ((1'd1 == and_ln120_reg_1008) | ((icmp_ln126_reg_1012 == 1'd0) | (1'd1 == and_ln223_fu_959_p2))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state70;
            end
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln115_fu_606_p2 = ($signed(i_072_cast_fu_597_p1) + $signed(7'd68));

assign add_ln174_fu_727_p2 = (trunc_ln87_fu_723_p1 + 7'd34);

assign add_ln182_fu_811_p2 = (nnzE_reg_466 + nnzY_reg_442);

assign add_ln183_1_fu_764_p2 = (empty_133_fu_754_p1 + 7'd33);

assign add_ln197_fu_856_p2 = ($signed(zext_ln87_4_fu_852_p1) + $signed(7'd68));

assign addr_cmp16_fu_888_p2 = ((reuse_addr_reg13_fu_110 == zext_ln200_fu_880_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_781_p2 = ((reuse_addr_reg_fu_118 == zext_ln183_reg_1108) ? 1'b1 : 1'b0);

assign and_ln120_fu_652_p2 = (or_ln120_fu_646_p2 & grp_fu_561_p2);

assign and_ln223_fu_959_p2 = (or_ln223_fu_953_p2 & grp_fu_561_p2);

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_pp3_stage1 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_pp3_stage2 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_pp3_stage4 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_pp3_stage5 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state84 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state85 = ap_CS_fsm[32'd77];

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_state31_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp3_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp3_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp3_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp3_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp3_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp3_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp3_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp3_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp3_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp3_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign bitcast_ln120_fu_617_p1 = linsys_solver_KKT_x_load_reg_1001;

assign bitcast_ln223_fu_924_p1 = linsys_solver_D_load_1_reg_1260;

assign empty_133_fu_754_p1 = nnzE_2_reg_478[6:0];

assign i_072_cast1_fu_590_p1 = i_072_reg_418;

assign i_072_cast_fu_597_p1 = i_072_reg_418;

assign i_100_fu_817_p2 = (i_98_reg_454 + 64'd1);

assign i_99_fu_829_p2 = ($signed(i_266_in_reg_525) + $signed(64'd18446744073709551615));

assign i_fu_578_p2 = (i_072_reg_418 + 6'd1);

assign icmp_ln104_fu_584_p2 = ((i_072_reg_418 == 6'd34) ? 1'b1 : 1'b0);

assign icmp_ln120_1_fu_640_p2 = ((trunc_ln120_fu_630_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln120_fu_634_p2 = ((tmp_fu_620_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln126_fu_658_p2 = ((k_reg_429 < 6'd34) ? 1'b1 : 1'b0);

assign icmp_ln142_1_fu_694_p2 = ((i_98_reg_454 == zext_ln87_reg_1037) ? 1'b1 : 1'b0);

assign icmp_ln142_fu_688_p2 = ((linsys_solver_KKT_p_q0 < linsys_solver_KKT_p_q1) ? 1'b1 : 1'b0);

assign icmp_ln150_fu_711_p2 = ((linsys_solver_KKT_i_q0 == k_reg_429) ? 1'b1 : 1'b0);

assign icmp_ln182_fu_748_p2 = ((nnzE_2_reg_478 == 64'd0) ? 1'b1 : 1'b0);

assign icmp_ln190_1_fu_823_p2 = (($signed(i_266_in_reg_525) > $signed(64'd0)) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_699_p2 = (($signed(nnzY_reg_442) > $signed(64'd0)) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_875_p2 = (($signed(ap_phi_mux_j_15_phi_fu_538_p4) < $signed(zext_ln87_5_reg_1177)) ? 1'b1 : 1'b0);

assign icmp_ln223_1_fu_947_p2 = ((trunc_ln223_fu_937_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln223_fu_941_p2 = ((tmp_90_fu_927_p4 != 8'd255) ? 1'b1 : 1'b0);

assign j_16_fu_908_p2 = (j_15_reg_535 + 64'd1);

assign k_3_fu_669_p2 = (k_reg_429 + 6'd1);

assign linsys_solver_Dinv_d0 = reg_566;

assign linsys_solver_KKT_i_address0 = i_98_reg_454;

assign linsys_solver_KKT_p_address0 = zext_ln126_fu_664_p1;

assign linsys_solver_KKT_p_address1 = zext_ln140_fu_675_p1;

assign linsys_solver_L_i_d0 = k_reg_429;

assign linsys_solver_L_p_d0 = 6'd0;

assign linsys_solver_L_x_d0 = reg_571;

assign linsys_solver_iwork_d1 = (tmpIdx_1_reg_1172 + 6'd1);

assign nnzE_1_fu_717_p2 = (nnzE_reg_466 + 64'd1);

assign nnzE_3_fu_758_p2 = ($signed(nnzE_2_reg_478) + $signed(64'd18446744073709551615));

assign nnzY_2_fu_795_p2 = (nnzY_1_reg_488 + 64'd1);

assign or_ln120_fu_646_p2 = (icmp_ln120_fu_634_p2 | icmp_ln120_1_fu_640_p2);

assign or_ln223_fu_953_p2 = (icmp_ln223_fu_941_p2 | icmp_ln223_1_fu_947_p2);

assign reuse_select17_fu_902_p3 = ((addr_cmp16_reg_1219[0:0] == 1'b1) ? ap_sig_allocacmp_reuse_reg12_load : linsys_solver_fwork_load_reg_1224);

assign reuse_select_fu_786_p3 = ((addr_cmp_fu_781_p2[0:0] == 1'b1) ? reuse_reg_fu_122 : linsys_solver_iwork_q1);

assign tmp_90_fu_927_p4 = {{bitcast_ln223_fu_924_p1[30:23]}};

assign tmp_fu_620_p4 = {{bitcast_ln120_fu_617_p1[30:23]}};

assign trunc_ln120_fu_630_p1 = bitcast_ln120_fu_617_p1[22:0];

assign trunc_ln223_fu_937_p1 = bitcast_ln223_fu_924_p1[22:0];

assign trunc_ln87_fu_723_p1 = nnzE_reg_466[6:0];

assign zext_ln107_fu_601_p1 = i_fu_578_p2;

assign zext_ln115_fu_612_p1 = add_ln115_fu_606_p2;

assign zext_ln126_fu_664_p1 = k_reg_429;

assign zext_ln140_fu_675_p1 = k_3_fu_669_p2;

assign zext_ln174_fu_733_p1 = add_ln174_fu_727_p2;

assign zext_ln183_fu_770_p1 = add_ln183_1_fu_764_p2;

assign zext_ln197_fu_862_p1 = add_ln197_fu_856_p2;

assign zext_ln200_fu_880_p1 = linsys_solver_L_i_q0;

assign zext_ln87_1_fu_684_p1 = linsys_solver_KKT_p_q0;

assign zext_ln87_2_fu_705_p1 = linsys_solver_KKT_i_q0;

assign zext_ln87_3_fu_846_p1 = linsys_solver_iwork_q1;

assign zext_ln87_4_fu_852_p1 = linsys_solver_iwork_q1;

assign zext_ln87_5_fu_867_p1 = linsys_solver_iwork_q1;

assign zext_ln87_6_fu_871_p1 = linsys_solver_L_p_q0;

assign zext_ln87_fu_680_p1 = linsys_solver_KKT_p_q1;

always @ (posedge ap_clk) begin
    zext_ln126_reg_1016[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln87_reg_1037[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln183_reg_1108[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln87_3_reg_1151[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln87_5_reg_1177[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //myFunction_QDLDL_factor
