-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myFunction_is_dual_infeasible is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    eps_dual_inf : IN STD_LOGIC_VECTOR (31 downto 0);
    work_delta_x_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    work_delta_x_ce0 : OUT STD_LOGIC;
    work_delta_x_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    qdata_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qdata_ce0 : OUT STD_LOGIC;
    qdata_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_350_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_350_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_350_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_350_p_ce : OUT STD_LOGIC;
    grp_fu_359_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_359_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_359_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_359_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_359_p_ce : OUT STD_LOGIC );
end;


architecture behav of myFunction_is_dual_infeasible is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (25 downto 0) := "00000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (25 downto 0) := "00000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (25 downto 0) := "00000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (25 downto 0) := "00000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (25 downto 0) := "00000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (25 downto 0) := "00000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (25 downto 0) := "00001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (25 downto 0) := "00010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (25 downto 0) := "00100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (25 downto 0) := "01000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (25 downto 0) := "10000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_DA24260 : STD_LOGIC_VECTOR (31 downto 0) := "00001101101000100100001001100000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_148 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_134_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_154 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal i_69_fu_159_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_69_reg_484 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln14_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal abs_v_i_fu_228_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal abs_v_i_reg_497 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal max_9_fu_319_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal and_ln158_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln158_reg_509 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal i_71_fu_368_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_71_reg_513 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal icmp_ln49_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_1_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_1_reg_531 : STD_LOGIC_VECTOR (0 downto 0);
    signal qdata_load_reg_536 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_392_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal icmp_ln159_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_reg_546 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal icmp_ln159_1_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_1_reg_551 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_2_fu_447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_2_reg_556 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_3_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_3_reg_561 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_reg_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_reg_100 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_70_reg_111 : STD_LOGIC_VECTOR (3 downto 0);
    signal prod_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln14_fu_165_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln49_fu_374_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_134_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_134_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal grp_fu_139_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_139_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal bitcast_ln14_fu_176_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_40_fu_180_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln14_fu_190_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln14_20_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_19_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln14_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln14_fu_218_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln14_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln14_5_fu_224_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln14_10_fu_236_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln14_11_fu_253_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_42_fu_239_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln14_8_fu_249_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln14_22_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_21_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_fu_257_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln14_9_fu_267_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln14_24_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln14_23_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln14_8_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln14_9_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln14_8_fu_307_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln14_9_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln158_fu_326_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_330_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln158_fu_340_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln158_1_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln158_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln158_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal bitcast_ln159_fu_399_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln159_1_fu_417_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_45_fu_403_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln159_fu_413_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_46_fu_421_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln159_1_fu_431_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal or_ln159_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln159_1_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_134_ce : STD_LOGIC;
    signal grp_fu_139_ce : STD_LOGIC;
    signal grp_fu_139_opcode : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_392_in_valid : STD_LOGIC;
    signal and_ln159_1_fu_473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_392_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myFunction_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component myFunction_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component myFunction_facc_32ns_32ns_1ns_32_6_no_dsp_1 IS
    generic (
        DWIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        ce : IN STD_LOGIC;
        in_data : IN STD_LOGIC_VECTOR (31 downto 0);
        in_last : IN STD_LOGIC_VECTOR (0 downto 0);
        in_valid : IN STD_LOGIC;
        out_data : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    facc_32ns_32ns_1ns_32_6_no_dsp_1_U96 : component myFunction_facc_32ns_32ns_1ns_32_6_no_dsp_1
    generic map (
        DWIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        ce => ap_const_logic_1,
        in_data => reg_154,
        in_last => icmp_ln49_1_reg_531,
        in_valid => grp_fu_392_in_valid,
        out_data => grp_fu_392_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_70_reg_111_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln158_fu_362_p2))) then 
                i_70_reg_111 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                i_70_reg_111 <= i_71_reg_513;
            end if; 
        end if;
    end process;

    i_reg_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                i_reg_100 <= i_69_reg_484;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_100 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    max_reg_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                max_reg_88 <= max_9_fu_319_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                max_reg_88 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    prod_reg_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln158_fu_362_p2))) then 
                prod_reg_122 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
                prod_reg_122 <= grp_fu_392_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                abs_v_i_reg_497 <= abs_v_i_fu_228_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                and_ln158_reg_509 <= and_ln158_fu_362_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_69_reg_484 <= i_69_fu_159_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                i_71_reg_513 <= i_71_fu_368_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state24)) then
                icmp_ln159_1_reg_551 <= icmp_ln159_1_fu_441_p2;
                icmp_ln159_2_reg_556 <= icmp_ln159_2_fu_447_p2;
                icmp_ln159_3_reg_561 <= icmp_ln159_3_fu_453_p2;
                icmp_ln159_reg_546 <= icmp_ln159_fu_435_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln49_fu_380_p2 = ap_const_lv1_0))) then
                icmp_ln49_1_reg_531 <= icmp_ln49_1_fu_386_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                qdata_load_reg_536 <= qdata_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state3))) then
                reg_148 <= work_delta_x_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state14))) then
                reg_154 <= grp_fu_350_p_dout0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln14_fu_170_p2, and_ln158_fu_362_p2, and_ln158_reg_509, ap_CS_fsm_state8, ap_CS_fsm_state9, icmp_ln49_fu_380_p2, ap_CS_fsm_state25, and_ln159_1_fu_473_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln14_fu_170_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (ap_const_lv1_1 = and_ln158_fu_362_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state25;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln49_fu_380_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state25) and ((ap_const_lv1_0 = and_ln159_1_fu_473_p2) or (ap_const_lv1_0 = and_ln158_reg_509)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state26;
                end if;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    abs_v_i_fu_228_p3 <= 
        bitcast_ln14_5_fu_224_p1 when (and_ln14_fu_212_p2(0) = '1') else 
        reg_148;
    and_ln14_8_fu_307_p2 <= (or_ln14_9_fu_301_p2 and or_ln14_8_fu_283_p2);
    and_ln14_9_fu_313_p2 <= (grp_fu_359_p_dout0 and and_ln14_8_fu_307_p2);
    and_ln14_fu_212_p2 <= (or_ln14_fu_206_p2 and grp_fu_359_p_dout0);
    and_ln158_fu_362_p2 <= (or_ln158_fu_356_p2 and grp_fu_359_p_dout0);
    and_ln159_1_fu_473_p2 <= (grp_fu_359_p_dout0 and and_ln159_fu_467_p2);
    and_ln159_fu_467_p2 <= (or_ln159_fu_459_p2 and or_ln159_1_fu_463_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, and_ln158_reg_509, ap_CS_fsm_state25, and_ln159_1_fu_473_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state25) and ((ap_const_lv1_0 = and_ln159_1_fu_473_p2) or (ap_const_lv1_0 = and_ln158_reg_509))) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(and_ln158_reg_509, ap_CS_fsm_state25, and_ln159_1_fu_473_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state25) and ((ap_const_lv1_0 = and_ln159_1_fu_473_p2) or (ap_const_lv1_0 = and_ln158_reg_509)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln14_10_fu_236_p1 <= abs_v_i_reg_497;
    bitcast_ln14_11_fu_253_p1 <= max_reg_88;
    bitcast_ln14_5_fu_224_p1 <= xor_ln14_fu_218_p2;
    bitcast_ln14_fu_176_p1 <= reg_148;
    bitcast_ln158_fu_326_p1 <= max_reg_88;
    bitcast_ln159_1_fu_417_p1 <= reg_154;
    bitcast_ln159_fu_399_p1 <= prod_reg_122;
    grp_fu_134_ce <= ap_const_logic_1;

    grp_fu_134_p0_assign_proc : process(ap_CS_fsm_state9, qdata_load_reg_536, max_reg_88, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_134_p0 <= qdata_load_reg_536;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_134_p0 <= max_reg_88;
        else 
            grp_fu_134_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_134_p1_assign_proc : process(eps_dual_inf, reg_148, ap_CS_fsm_state9, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_134_p1 <= reg_148;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_134_p1 <= eps_dual_inf;
        else 
            grp_fu_134_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_134_p2 <= grp_fu_350_p_dout0;
    grp_fu_139_ce <= ap_const_logic_1;

    grp_fu_139_opcode_assign_proc : process(ap_CS_fsm_state2, icmp_ln14_fu_170_p2, ap_CS_fsm_state24, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state24))) then 
            grp_fu_139_opcode <= ap_const_lv5_4;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state6) or ((icmp_ln14_fu_170_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            grp_fu_139_opcode <= ap_const_lv5_2;
        else 
            grp_fu_139_opcode <= "XXXXX";
        end if; 
    end process;


    grp_fu_139_p0_assign_proc : process(reg_148, ap_CS_fsm_state2, abs_v_i_reg_497, ap_CS_fsm_state24, max_reg_88, prod_reg_122, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            grp_fu_139_p0 <= prod_reg_122;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_139_p0 <= abs_v_i_reg_497;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_139_p0 <= reg_148;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_139_p0 <= max_reg_88;
        else 
            grp_fu_139_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_139_p1_assign_proc : process(reg_154, ap_CS_fsm_state2, ap_CS_fsm_state24, max_reg_88, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            grp_fu_139_p1 <= reg_154;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_139_p1 <= max_reg_88;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_139_p1 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_139_p1 <= ap_const_lv32_DA24260;
        else 
            grp_fu_139_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_139_p2 <= grp_fu_359_p_dout0;
    grp_fu_350_p_ce <= ap_const_logic_1;
    grp_fu_350_p_din0 <= grp_fu_134_p0;
    grp_fu_350_p_din1 <= grp_fu_134_p1;
    grp_fu_359_p_ce <= ap_const_logic_1;
    grp_fu_359_p_din0 <= grp_fu_139_p0;
    grp_fu_359_p_din1 <= grp_fu_139_p1;
    grp_fu_359_p_opcode <= grp_fu_139_opcode;

    grp_fu_392_in_valid_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            grp_fu_392_in_valid <= ap_const_logic_1;
        else 
            grp_fu_392_in_valid <= ap_const_logic_0;
        end if; 
    end process;

    i_69_fu_159_p2 <= std_logic_vector(unsigned(i_reg_100) + unsigned(ap_const_lv4_1));
    i_71_fu_368_p2 <= std_logic_vector(unsigned(i_70_reg_111) + unsigned(ap_const_lv4_1));
    icmp_ln14_19_fu_194_p2 <= "0" when (tmp_40_fu_180_p4 = ap_const_lv8_FF) else "1";
    icmp_ln14_20_fu_200_p2 <= "1" when (trunc_ln14_fu_190_p1 = ap_const_lv23_0) else "0";
    icmp_ln14_21_fu_271_p2 <= "0" when (tmp_42_fu_239_p4 = ap_const_lv8_FF) else "1";
    icmp_ln14_22_fu_277_p2 <= "1" when (trunc_ln14_8_fu_249_p1 = ap_const_lv23_0) else "0";
    icmp_ln14_23_fu_289_p2 <= "0" when (tmp_43_fu_257_p4 = ap_const_lv8_FF) else "1";
    icmp_ln14_24_fu_295_p2 <= "1" when (trunc_ln14_9_fu_267_p1 = ap_const_lv23_0) else "0";
    icmp_ln14_fu_170_p2 <= "1" when (i_reg_100 = ap_const_lv4_F) else "0";
    icmp_ln158_1_fu_350_p2 <= "1" when (trunc_ln158_fu_340_p1 = ap_const_lv23_0) else "0";
    icmp_ln158_fu_344_p2 <= "0" when (tmp_fu_330_p4 = ap_const_lv8_FF) else "1";
    icmp_ln159_1_fu_441_p2 <= "1" when (trunc_ln159_fu_413_p1 = ap_const_lv23_0) else "0";
    icmp_ln159_2_fu_447_p2 <= "0" when (tmp_46_fu_421_p4 = ap_const_lv8_FF) else "1";
    icmp_ln159_3_fu_453_p2 <= "1" when (trunc_ln159_1_fu_431_p1 = ap_const_lv23_0) else "0";
    icmp_ln159_fu_435_p2 <= "0" when (tmp_45_fu_403_p4 = ap_const_lv8_FF) else "1";
    icmp_ln49_1_fu_386_p2 <= "1" when (i_71_fu_368_p2 = ap_const_lv4_F) else "0";
    icmp_ln49_fu_380_p2 <= "1" when (i_70_reg_111 = ap_const_lv4_F) else "0";
    max_9_fu_319_p3 <= 
        abs_v_i_reg_497 when (and_ln14_9_fu_313_p2(0) = '1') else 
        max_reg_88;
    or_ln14_8_fu_283_p2 <= (icmp_ln14_22_fu_277_p2 or icmp_ln14_21_fu_271_p2);
    or_ln14_9_fu_301_p2 <= (icmp_ln14_24_fu_295_p2 or icmp_ln14_23_fu_289_p2);
    or_ln14_fu_206_p2 <= (icmp_ln14_20_fu_200_p2 or icmp_ln14_19_fu_194_p2);
    or_ln158_fu_356_p2 <= (icmp_ln158_fu_344_p2 or icmp_ln158_1_fu_350_p2);
    or_ln159_1_fu_463_p2 <= (icmp_ln159_3_reg_561 or icmp_ln159_2_reg_556);
    or_ln159_fu_459_p2 <= (icmp_ln159_reg_546 or icmp_ln159_1_reg_551);
    qdata_address0 <= zext_ln49_fu_374_p1(4 - 1 downto 0);

    qdata_ce0_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            qdata_ce0 <= ap_const_logic_1;
        else 
            qdata_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_40_fu_180_p4 <= bitcast_ln14_fu_176_p1(30 downto 23);
    tmp_42_fu_239_p4 <= bitcast_ln14_10_fu_236_p1(30 downto 23);
    tmp_43_fu_257_p4 <= bitcast_ln14_11_fu_253_p1(30 downto 23);
    tmp_45_fu_403_p4 <= bitcast_ln159_fu_399_p1(30 downto 23);
    tmp_46_fu_421_p4 <= bitcast_ln159_1_fu_417_p1(30 downto 23);
    tmp_fu_330_p4 <= bitcast_ln158_fu_326_p1(30 downto 23);
    trunc_ln14_8_fu_249_p1 <= bitcast_ln14_10_fu_236_p1(23 - 1 downto 0);
    trunc_ln14_9_fu_267_p1 <= bitcast_ln14_11_fu_253_p1(23 - 1 downto 0);
    trunc_ln14_fu_190_p1 <= bitcast_ln14_fu_176_p1(23 - 1 downto 0);
    trunc_ln158_fu_340_p1 <= bitcast_ln158_fu_326_p1(23 - 1 downto 0);
    trunc_ln159_1_fu_431_p1 <= bitcast_ln159_1_fu_417_p1(23 - 1 downto 0);
    trunc_ln159_fu_413_p1 <= bitcast_ln159_fu_399_p1(23 - 1 downto 0);

    work_delta_x_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state9, zext_ln14_fu_165_p1, zext_ln49_fu_374_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            work_delta_x_address0 <= zext_ln49_fu_374_p1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            work_delta_x_address0 <= zext_ln14_fu_165_p1(4 - 1 downto 0);
        else 
            work_delta_x_address0 <= "XXXX";
        end if; 
    end process;


    work_delta_x_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            work_delta_x_ce0 <= ap_const_logic_1;
        else 
            work_delta_x_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln14_fu_218_p2 <= (bitcast_ln14_fu_176_p1 xor ap_const_lv32_80000000);
    zext_ln14_fu_165_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_100),64));
    zext_ln49_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_70_reg_111),64));
end behav;
