-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myFunction_compute_dua_res is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    qdata_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    qdata_ce0 : OUT STD_LOGIC;
    qdata_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    work_x_prev_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    work_x_prev_ce0 : OUT STD_LOGIC;
    work_x_prev_we0 : OUT STD_LOGIC;
    work_x_prev_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    work_Px_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    work_Px_ce0 : OUT STD_LOGIC;
    work_Px_we0 : OUT STD_LOGIC;
    work_Px_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of myFunction_compute_dua_res is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_72_fu_91_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_72_reg_119 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln43_fu_97_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_reg_124 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln43_fu_102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_74_fu_113_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_reg_69 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_73_reg_80 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln85_fu_108_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_73_reg_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln43_fu_102_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_73_reg_80 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                i_73_reg_80 <= i_74_fu_113_p2;
            end if; 
        end if;
    end process;

    i_reg_69_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_reg_69 <= i_72_reg_119;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_69 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_72_reg_119 <= i_72_fu_91_p2;
                    zext_ln43_reg_124(3 downto 0) <= zext_ln43_fu_97_p1(3 downto 0);
            end if;
        end if;
    end process;
    zext_ln43_reg_124(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln43_fu_102_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln43_fu_102_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_const_logic_0;
    i_72_fu_91_p2 <= std_logic_vector(unsigned(i_reg_69) + unsigned(ap_const_lv4_1));
    i_74_fu_113_p2 <= std_logic_vector(unsigned(i_73_reg_80) + unsigned(ap_const_lv4_1));
    icmp_ln43_fu_102_p2 <= "1" when (i_reg_69 = ap_const_lv4_F) else "0";
    qdata_address0 <= zext_ln43_fu_97_p1(4 - 1 downto 0);

    qdata_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            qdata_ce0 <= ap_const_logic_1;
        else 
            qdata_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    work_Px_address0 <= zext_ln85_fu_108_p1(4 - 1 downto 0);

    work_Px_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            work_Px_ce0 <= ap_const_logic_1;
        else 
            work_Px_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    work_Px_d0 <= ap_const_lv32_0;

    work_Px_we0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            work_Px_we0 <= ap_const_logic_1;
        else 
            work_Px_we0 <= ap_const_logic_0;
        end if; 
    end process;

    work_x_prev_address0 <= zext_ln43_reg_124(4 - 1 downto 0);

    work_x_prev_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            work_x_prev_ce0 <= ap_const_logic_1;
        else 
            work_x_prev_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    work_x_prev_d0 <= qdata_q0;

    work_x_prev_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            work_x_prev_we0 <= ap_const_logic_1;
        else 
            work_x_prev_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln43_fu_97_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_69),64));
    zext_ln85_fu_108_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_73_reg_80),64));
end behav;
