// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myFunction_check_termination (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        approximate,
        info_pri_res,
        info_status_val,
        info_status_val_ap_vld,
        work_z_address0,
        work_z_ce0,
        work_z_q0,
        work_Ax_address0,
        work_Ax_ce0,
        work_Ax_q0,
        udata_address0,
        udata_ce0,
        udata_q0,
        ldata_address0,
        ldata_ce0,
        ldata_q0,
        work_delta_y_address0,
        work_delta_y_ce0,
        work_delta_y_we0,
        work_delta_y_d0,
        work_delta_y_q0,
        Adata_x_address0,
        Adata_x_ce0,
        Adata_x_q0,
        qdata_address0,
        qdata_ce0,
        qdata_q0,
        work_Px_address0,
        work_Px_ce0,
        work_Px_q0,
        work_delta_x_address0,
        work_delta_x_ce0,
        work_delta_x_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 58'd1;
parameter    ap_ST_fsm_state2 = 58'd2;
parameter    ap_ST_fsm_state3 = 58'd4;
parameter    ap_ST_fsm_state4 = 58'd8;
parameter    ap_ST_fsm_state5 = 58'd16;
parameter    ap_ST_fsm_state6 = 58'd32;
parameter    ap_ST_fsm_state7 = 58'd64;
parameter    ap_ST_fsm_state8 = 58'd128;
parameter    ap_ST_fsm_state9 = 58'd256;
parameter    ap_ST_fsm_state10 = 58'd512;
parameter    ap_ST_fsm_state11 = 58'd1024;
parameter    ap_ST_fsm_state12 = 58'd2048;
parameter    ap_ST_fsm_state13 = 58'd4096;
parameter    ap_ST_fsm_state14 = 58'd8192;
parameter    ap_ST_fsm_state15 = 58'd16384;
parameter    ap_ST_fsm_state16 = 58'd32768;
parameter    ap_ST_fsm_state17 = 58'd65536;
parameter    ap_ST_fsm_state18 = 58'd131072;
parameter    ap_ST_fsm_state19 = 58'd262144;
parameter    ap_ST_fsm_state20 = 58'd524288;
parameter    ap_ST_fsm_state21 = 58'd1048576;
parameter    ap_ST_fsm_state22 = 58'd2097152;
parameter    ap_ST_fsm_state23 = 58'd4194304;
parameter    ap_ST_fsm_state24 = 58'd8388608;
parameter    ap_ST_fsm_state25 = 58'd16777216;
parameter    ap_ST_fsm_state26 = 58'd33554432;
parameter    ap_ST_fsm_state27 = 58'd67108864;
parameter    ap_ST_fsm_state28 = 58'd134217728;
parameter    ap_ST_fsm_state29 = 58'd268435456;
parameter    ap_ST_fsm_state30 = 58'd536870912;
parameter    ap_ST_fsm_state31 = 58'd1073741824;
parameter    ap_ST_fsm_state32 = 58'd2147483648;
parameter    ap_ST_fsm_state33 = 58'd4294967296;
parameter    ap_ST_fsm_state34 = 58'd8589934592;
parameter    ap_ST_fsm_state35 = 58'd17179869184;
parameter    ap_ST_fsm_state36 = 58'd34359738368;
parameter    ap_ST_fsm_state37 = 58'd68719476736;
parameter    ap_ST_fsm_state38 = 58'd137438953472;
parameter    ap_ST_fsm_state39 = 58'd274877906944;
parameter    ap_ST_fsm_state40 = 58'd549755813888;
parameter    ap_ST_fsm_state41 = 58'd1099511627776;
parameter    ap_ST_fsm_state42 = 58'd2199023255552;
parameter    ap_ST_fsm_state43 = 58'd4398046511104;
parameter    ap_ST_fsm_state44 = 58'd8796093022208;
parameter    ap_ST_fsm_state45 = 58'd17592186044416;
parameter    ap_ST_fsm_state46 = 58'd35184372088832;
parameter    ap_ST_fsm_state47 = 58'd70368744177664;
parameter    ap_ST_fsm_state48 = 58'd140737488355328;
parameter    ap_ST_fsm_state49 = 58'd281474976710656;
parameter    ap_ST_fsm_state50 = 58'd562949953421312;
parameter    ap_ST_fsm_state51 = 58'd1125899906842624;
parameter    ap_ST_fsm_state52 = 58'd2251799813685248;
parameter    ap_ST_fsm_state53 = 58'd4503599627370496;
parameter    ap_ST_fsm_state54 = 58'd9007199254740992;
parameter    ap_ST_fsm_state55 = 58'd18014398509481984;
parameter    ap_ST_fsm_state56 = 58'd36028797018963968;
parameter    ap_ST_fsm_state57 = 58'd72057594037927936;
parameter    ap_ST_fsm_state58 = 58'd144115188075855872;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] approximate;
input  [31:0] info_pri_res;
output  [4:0] info_status_val;
output   info_status_val_ap_vld;
output  [4:0] work_z_address0;
output   work_z_ce0;
input  [31:0] work_z_q0;
output  [4:0] work_Ax_address0;
output   work_Ax_ce0;
input  [31:0] work_Ax_q0;
output  [4:0] udata_address0;
output   udata_ce0;
input  [31:0] udata_q0;
output  [4:0] ldata_address0;
output   ldata_ce0;
input  [31:0] ldata_q0;
output  [4:0] work_delta_y_address0;
output   work_delta_y_ce0;
output   work_delta_y_we0;
output  [31:0] work_delta_y_d0;
input  [31:0] work_delta_y_q0;
output  [5:0] Adata_x_address0;
output   Adata_x_ce0;
input  [31:0] Adata_x_q0;
output  [3:0] qdata_address0;
output   qdata_ce0;
input  [31:0] qdata_q0;
output  [3:0] work_Px_address0;
output   work_Px_ce0;
input  [31:0] work_Px_q0;
output  [3:0] work_delta_x_address0;
output   work_delta_x_ce0;
input  [31:0] work_delta_x_q0;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] info_status_val;
reg info_status_val_ap_vld;
reg work_z_ce0;
reg work_Ax_ce0;
reg[3:0] qdata_address0;
reg qdata_ce0;
reg work_Px_ce0;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [57:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] info_dua_res;
wire   [31:0] grp_fu_350_p2;
reg   [31:0] reg_374;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state49;
wire   [31:0] grp_fu_346_p2;
reg   [31:0] reg_379;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state54;
wire   [0:0] approximate_read_read_fu_98_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] or_ln229_1_fu_423_p2;
reg   [0:0] or_ln229_1_reg_1628;
wire   [0:0] or_ln229_2_fu_464_p2;
reg   [0:0] or_ln229_2_reg_1633;
wire   [0:0] or_ln229_fu_476_p2;
reg   [0:0] or_ln229_reg_1638;
wire   [4:0] i_75_fu_482_p2;
reg   [4:0] i_75_reg_1642;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln14_fu_493_p2;
reg   [31:0] work_z_load_reg_1655;
wire    ap_CS_fsm_state4;
wire   [31:0] abs_v_i_fu_550_p3;
reg   [31:0] abs_v_i_reg_1662;
wire    ap_CS_fsm_state6;
wire   [31:0] max_rel_eps_5_fu_640_p3;
wire    ap_CS_fsm_state8;
wire   [4:0] i_77_fu_647_p2;
reg   [4:0] i_77_reg_1674;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln14_3_fu_658_p2;
reg   [31:0] work_Ax_load_reg_1687;
wire    ap_CS_fsm_state10;
wire   [31:0] abs_v_i_2_fu_715_p3;
reg   [31:0] abs_v_i_2_reg_1694;
wire    ap_CS_fsm_state12;
wire   [31:0] max_14_fu_805_p3;
wire    ap_CS_fsm_state14;
wire   [0:0] and_ln83_1_fu_890_p2;
reg   [0:0] and_ln83_1_reg_1706;
wire    ap_CS_fsm_state15;
wire   [31:0] eps_rel_fu_896_p3;
reg   [31:0] eps_rel_reg_1711;
wire    ap_CS_fsm_state16;
wire   [31:0] max_rel_eps_fu_904_p3;
wire   [0:0] icmp_ln237_fu_930_p2;
reg   [0:0] icmp_ln237_reg_1722;
wire    ap_CS_fsm_state25;
wire   [0:0] icmp_ln237_1_fu_936_p2;
reg   [0:0] icmp_ln237_1_reg_1727;
wire   [0:0] and_ln237_1_fu_951_p2;
reg   [0:0] and_ln237_1_reg_1732;
wire    ap_CS_fsm_state26;
wire   [31:0] eps_dual_inf_fu_957_p3;
reg   [31:0] eps_dual_inf_reg_1736;
wire    ap_CS_fsm_state27;
wire   [3:0] i_79_fu_965_p2;
reg   [3:0] i_79_reg_1742;
wire    ap_CS_fsm_state29;
wire   [0:0] icmp_ln14_4_fu_976_p2;
reg   [31:0] qdata_load_reg_1755;
wire    ap_CS_fsm_state30;
wire   [31:0] abs_v_i_3_fu_1033_p3;
reg   [31:0] abs_v_i_3_reg_1762;
wire    ap_CS_fsm_state32;
wire   [31:0] max_rel_eps_6_fu_1123_p3;
wire    ap_CS_fsm_state34;
wire   [3:0] i_81_fu_1130_p2;
reg   [3:0] i_81_reg_1774;
wire    ap_CS_fsm_state35;
wire   [31:0] temp_rel_eps_fu_1184_p3;
wire    ap_CS_fsm_state36;
wire   [3:0] i_83_fu_1192_p2;
reg   [3:0] i_83_reg_1787;
wire    ap_CS_fsm_state37;
wire   [0:0] icmp_ln14_6_fu_1203_p2;
reg   [31:0] work_Px_load_reg_1800;
wire    ap_CS_fsm_state38;
wire   [31:0] abs_v_i_4_fu_1260_p3;
reg   [31:0] abs_v_i_4_reg_1807;
wire    ap_CS_fsm_state40;
wire   [31:0] max_22_fu_1350_p3;
wire    ap_CS_fsm_state42;
wire   [31:0] max_rel_eps_3_fu_1441_p3;
reg   [31:0] max_rel_eps_3_reg_1819;
wire    ap_CS_fsm_state43;
wire   [31:0] max_rel_eps_4_fu_1532_p3;
reg   [31:0] max_rel_eps_4_reg_1826;
wire    ap_CS_fsm_state45;
wire   [0:0] icmp_ln241_fu_1557_p2;
reg   [0:0] icmp_ln241_reg_1831;
wire    ap_CS_fsm_state55;
wire   [0:0] icmp_ln241_1_fu_1563_p2;
reg   [0:0] icmp_ln241_1_reg_1836;
wire   [0:0] and_ln241_1_fu_1578_p2;
reg   [0:0] and_ln241_1_reg_1841;
wire    ap_CS_fsm_state56;
wire    grp_is_primal_infeasible_fu_317_ap_start;
wire    grp_is_primal_infeasible_fu_317_ap_done;
wire    grp_is_primal_infeasible_fu_317_ap_idle;
wire    grp_is_primal_infeasible_fu_317_ap_ready;
wire   [4:0] grp_is_primal_infeasible_fu_317_udata_address0;
wire    grp_is_primal_infeasible_fu_317_udata_ce0;
wire   [4:0] grp_is_primal_infeasible_fu_317_ldata_address0;
wire    grp_is_primal_infeasible_fu_317_ldata_ce0;
wire   [4:0] grp_is_primal_infeasible_fu_317_work_delta_y_address0;
wire    grp_is_primal_infeasible_fu_317_work_delta_y_ce0;
wire    grp_is_primal_infeasible_fu_317_work_delta_y_we0;
wire   [31:0] grp_is_primal_infeasible_fu_317_work_delta_y_d0;
wire   [5:0] grp_is_primal_infeasible_fu_317_Adata_x_address0;
wire    grp_is_primal_infeasible_fu_317_Adata_x_ce0;
wire   [0:0] grp_is_primal_infeasible_fu_317_ap_return;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_346_p_din0;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_346_p_din1;
wire   [1:0] grp_is_primal_infeasible_fu_317_grp_fu_346_p_opcode;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_346_p_dout0;
wire    grp_is_primal_infeasible_fu_317_grp_fu_346_p_ce;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_350_p_din0;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_350_p_din1;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_350_p_dout0;
wire    grp_is_primal_infeasible_fu_317_grp_fu_350_p_ce;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_1845_p_din0;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_1845_p_din1;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_1845_p_dout0;
wire    grp_is_primal_infeasible_fu_317_grp_fu_1845_p_ce;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_354_p_din0;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_354_p_din1;
wire   [4:0] grp_is_primal_infeasible_fu_317_grp_fu_354_p_opcode;
wire   [0:0] grp_is_primal_infeasible_fu_317_grp_fu_354_p_dout0;
wire    grp_is_primal_infeasible_fu_317_grp_fu_354_p_ce;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_359_p_din0;
wire   [31:0] grp_is_primal_infeasible_fu_317_grp_fu_359_p_din1;
wire   [4:0] grp_is_primal_infeasible_fu_317_grp_fu_359_p_opcode;
wire   [0:0] grp_is_primal_infeasible_fu_317_grp_fu_359_p_dout0;
wire    grp_is_primal_infeasible_fu_317_grp_fu_359_p_ce;
wire    grp_is_dual_infeasible_fu_337_ap_start;
wire    grp_is_dual_infeasible_fu_337_ap_done;
wire    grp_is_dual_infeasible_fu_337_ap_idle;
wire    grp_is_dual_infeasible_fu_337_ap_ready;
wire   [3:0] grp_is_dual_infeasible_fu_337_work_delta_x_address0;
wire    grp_is_dual_infeasible_fu_337_work_delta_x_ce0;
wire   [3:0] grp_is_dual_infeasible_fu_337_qdata_address0;
wire    grp_is_dual_infeasible_fu_337_qdata_ce0;
wire   [31:0] grp_is_dual_infeasible_fu_337_grp_fu_350_p_din0;
wire   [31:0] grp_is_dual_infeasible_fu_337_grp_fu_350_p_din1;
wire   [31:0] grp_is_dual_infeasible_fu_337_grp_fu_350_p_dout0;
wire    grp_is_dual_infeasible_fu_337_grp_fu_350_p_ce;
wire   [31:0] grp_is_dual_infeasible_fu_337_grp_fu_359_p_din0;
wire   [31:0] grp_is_dual_infeasible_fu_337_grp_fu_359_p_din1;
wire   [4:0] grp_is_dual_infeasible_fu_337_grp_fu_359_p_opcode;
wire   [0:0] grp_is_dual_infeasible_fu_337_grp_fu_359_p_dout0;
wire    grp_is_dual_infeasible_fu_337_grp_fu_359_p_ce;
reg   [31:0] max_reg_156;
reg   [4:0] i_reg_168;
wire   [31:0] ap_phi_mux_max_12_phi_fu_183_p4;
reg   [31:0] max_12_reg_179;
reg   [4:0] i_76_reg_191;
reg   [0:0] prim_inf_check_1_reg_202;
wire    ap_CS_fsm_state28;
reg    ap_block_state28_on_subcall_done;
reg   [0:0] prim_res_check_reg_214;
reg   [31:0] max_15_reg_227;
reg   [3:0] i_78_reg_239;
reg   [31:0] max_18_reg_250;
reg   [3:0] i_80_reg_262;
reg   [31:0] max_20_reg_273;
wire   [0:0] icmp_ln14_5_fu_1136_p2;
reg   [3:0] i_82_reg_285;
reg   [0:0] ap_phi_mux_retval_0_phi_fu_300_p10;
reg   [0:0] retval_0_reg_296;
wire    ap_CS_fsm_state58;
wire    ap_CS_fsm_state57;
reg    ap_predicate_op370_call_state57;
reg    ap_block_state57_on_subcall_done;
reg    grp_is_primal_infeasible_fu_317_ap_start_reg;
reg    grp_is_dual_infeasible_fu_337_ap_start_reg;
wire   [63:0] zext_ln14_fu_488_p1;
wire   [63:0] zext_ln14_1_fu_653_p1;
wire   [63:0] zext_ln14_2_fu_971_p1;
wire   [63:0] zext_ln14_3_fu_1198_p1;
wire   [4:0] select_ln210_fu_1584_p3;
reg   [31:0] grp_fu_346_p0;
reg   [31:0] grp_fu_346_p1;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state50;
reg   [31:0] grp_fu_350_p0;
reg   [31:0] grp_fu_350_p1;
wire    ap_CS_fsm_state46;
reg   [31:0] grp_fu_354_p0;
reg   [31:0] grp_fu_354_p1;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state44;
reg   [31:0] grp_fu_359_p0;
reg   [31:0] grp_fu_359_p1;
wire   [31:0] bitcast_ln229_fu_394_p1;
wire   [7:0] tmp_fu_397_p4;
wire   [22:0] trunc_ln229_fu_407_p1;
wire   [0:0] icmp_ln229_1_fu_417_p2;
wire   [0:0] icmp_ln229_fu_411_p2;
wire   [0:0] grp_fu_354_p2;
wire   [31:0] bitcast_ln229_1_fu_435_p1;
wire   [7:0] tmp_48_fu_438_p4;
wire   [22:0] trunc_ln229_1_fu_448_p1;
wire   [0:0] icmp_ln229_3_fu_458_p2;
wire   [0:0] icmp_ln229_2_fu_452_p2;
wire   [0:0] grp_fu_359_p2;
wire   [0:0] and_ln229_fu_429_p2;
wire   [0:0] and_ln229_1_fu_470_p2;
wire   [31:0] bitcast_ln14_fu_499_p1;
wire   [7:0] tmp_50_fu_502_p4;
wire   [22:0] trunc_ln14_fu_512_p1;
wire   [0:0] icmp_ln14_26_fu_522_p2;
wire   [0:0] icmp_ln14_25_fu_516_p2;
wire   [0:0] or_ln14_fu_528_p2;
wire   [31:0] xor_ln14_fu_540_p2;
wire   [0:0] and_ln14_fu_534_p2;
wire   [31:0] bitcast_ln14_9_fu_546_p1;
wire   [31:0] bitcast_ln14_12_fu_557_p1;
wire   [31:0] bitcast_ln14_14_fu_574_p1;
wire   [7:0] tmp_52_fu_560_p4;
wire   [22:0] trunc_ln14_10_fu_570_p1;
wire   [0:0] icmp_ln14_28_fu_598_p2;
wire   [0:0] icmp_ln14_27_fu_592_p2;
wire   [7:0] tmp_53_fu_578_p4;
wire   [22:0] trunc_ln14_11_fu_588_p1;
wire   [0:0] icmp_ln14_30_fu_616_p2;
wire   [0:0] icmp_ln14_29_fu_610_p2;
wire   [0:0] or_ln14_10_fu_604_p2;
wire   [0:0] or_ln14_11_fu_622_p2;
wire   [0:0] and_ln14_10_fu_628_p2;
wire   [0:0] and_ln14_11_fu_634_p2;
wire   [31:0] bitcast_ln14_15_fu_664_p1;
wire   [7:0] tmp_60_fu_667_p4;
wire   [22:0] trunc_ln14_12_fu_677_p1;
wire   [0:0] icmp_ln14_32_fu_687_p2;
wire   [0:0] icmp_ln14_31_fu_681_p2;
wire   [0:0] or_ln14_12_fu_693_p2;
wire   [31:0] xor_ln14_2_fu_705_p2;
wire   [0:0] and_ln14_12_fu_699_p2;
wire   [31:0] bitcast_ln14_11_fu_711_p1;
wire   [31:0] bitcast_ln14_16_fu_722_p1;
wire   [31:0] bitcast_ln14_18_fu_739_p1;
wire   [7:0] tmp_62_fu_725_p4;
wire   [22:0] trunc_ln14_13_fu_735_p1;
wire   [0:0] icmp_ln14_34_fu_763_p2;
wire   [0:0] icmp_ln14_33_fu_757_p2;
wire   [7:0] tmp_63_fu_743_p4;
wire   [22:0] trunc_ln14_14_fu_753_p1;
wire   [0:0] icmp_ln14_36_fu_781_p2;
wire   [0:0] icmp_ln14_35_fu_775_p2;
wire   [0:0] or_ln14_13_fu_769_p2;
wire   [0:0] or_ln14_14_fu_787_p2;
wire   [0:0] and_ln14_13_fu_793_p2;
wire   [0:0] and_ln14_14_fu_799_p2;
wire   [31:0] bitcast_ln83_fu_812_p1;
wire   [31:0] bitcast_ln83_1_fu_830_p1;
wire   [7:0] tmp_55_fu_816_p4;
wire   [22:0] trunc_ln83_fu_826_p1;
wire   [0:0] icmp_ln83_1_fu_854_p2;
wire   [0:0] icmp_ln83_fu_848_p2;
wire   [7:0] tmp_56_fu_834_p4;
wire   [22:0] trunc_ln83_1_fu_844_p1;
wire   [0:0] icmp_ln83_3_fu_872_p2;
wire   [0:0] icmp_ln83_2_fu_866_p2;
wire   [0:0] or_ln83_fu_860_p2;
wire   [0:0] or_ln83_1_fu_878_p2;
wire   [0:0] and_ln83_fu_884_p2;
wire   [31:0] bitcast_ln237_fu_912_p1;
wire   [7:0] tmp_58_fu_916_p4;
wire   [22:0] trunc_ln237_fu_926_p1;
wire   [0:0] or_ln237_fu_942_p2;
wire   [0:0] and_ln237_fu_946_p2;
wire   [31:0] bitcast_ln14_19_fu_982_p1;
wire   [7:0] tmp_65_fu_985_p4;
wire   [22:0] trunc_ln14_15_fu_995_p1;
wire   [0:0] icmp_ln14_38_fu_1005_p2;
wire   [0:0] icmp_ln14_37_fu_999_p2;
wire   [0:0] or_ln14_15_fu_1011_p2;
wire   [31:0] xor_ln14_3_fu_1023_p2;
wire   [0:0] and_ln14_15_fu_1017_p2;
wire   [31:0] bitcast_ln14_13_fu_1029_p1;
wire   [31:0] bitcast_ln14_20_fu_1040_p1;
wire   [31:0] bitcast_ln14_21_fu_1057_p1;
wire   [7:0] tmp_67_fu_1043_p4;
wire   [22:0] trunc_ln14_16_fu_1053_p1;
wire   [0:0] icmp_ln14_40_fu_1081_p2;
wire   [0:0] icmp_ln14_39_fu_1075_p2;
wire   [7:0] tmp_68_fu_1061_p4;
wire   [22:0] trunc_ln14_17_fu_1071_p1;
wire   [0:0] icmp_ln14_42_fu_1099_p2;
wire   [0:0] icmp_ln14_41_fu_1093_p2;
wire   [0:0] or_ln14_16_fu_1087_p2;
wire   [0:0] or_ln14_17_fu_1105_p2;
wire   [0:0] and_ln14_16_fu_1111_p2;
wire   [0:0] and_ln14_17_fu_1117_p2;
wire   [31:0] bitcast_ln14_22_fu_1142_p1;
wire   [7:0] tmp_70_fu_1146_p4;
wire   [22:0] trunc_ln14_18_fu_1156_p1;
wire   [0:0] icmp_ln14_44_fu_1166_p2;
wire   [0:0] icmp_ln14_43_fu_1160_p2;
wire   [0:0] or_ln14_18_fu_1172_p2;
wire   [0:0] and_ln14_18_fu_1178_p2;
wire   [31:0] bitcast_ln14_23_fu_1209_p1;
wire   [7:0] tmp_80_fu_1212_p4;
wire   [22:0] trunc_ln14_19_fu_1222_p1;
wire   [0:0] icmp_ln14_46_fu_1232_p2;
wire   [0:0] icmp_ln14_45_fu_1226_p2;
wire   [0:0] or_ln14_19_fu_1238_p2;
wire   [31:0] xor_ln14_4_fu_1250_p2;
wire   [0:0] and_ln14_19_fu_1244_p2;
wire   [31:0] bitcast_ln14_17_fu_1256_p1;
wire   [31:0] bitcast_ln14_24_fu_1267_p1;
wire   [31:0] bitcast_ln14_25_fu_1284_p1;
wire   [7:0] tmp_82_fu_1270_p4;
wire   [22:0] trunc_ln14_20_fu_1280_p1;
wire   [0:0] icmp_ln14_48_fu_1308_p2;
wire   [0:0] icmp_ln14_47_fu_1302_p2;
wire   [7:0] tmp_83_fu_1288_p4;
wire   [22:0] trunc_ln14_21_fu_1298_p1;
wire   [0:0] icmp_ln14_50_fu_1326_p2;
wire   [0:0] icmp_ln14_49_fu_1320_p2;
wire   [0:0] or_ln14_20_fu_1314_p2;
wire   [0:0] or_ln14_21_fu_1332_p2;
wire   [0:0] and_ln14_20_fu_1338_p2;
wire   [0:0] and_ln14_21_fu_1344_p2;
wire   [31:0] bitcast_ln117_fu_1357_p1;
wire   [31:0] bitcast_ln117_1_fu_1375_p1;
wire   [7:0] tmp_72_fu_1361_p4;
wire   [22:0] trunc_ln117_fu_1371_p1;
wire   [0:0] icmp_ln117_1_fu_1399_p2;
wire   [0:0] icmp_ln117_fu_1393_p2;
wire   [7:0] tmp_73_fu_1379_p4;
wire   [22:0] trunc_ln117_1_fu_1389_p1;
wire   [0:0] icmp_ln117_3_fu_1417_p2;
wire   [0:0] icmp_ln117_2_fu_1411_p2;
wire   [0:0] or_ln117_fu_1405_p2;
wire   [0:0] or_ln117_1_fu_1423_p2;
wire   [0:0] and_ln117_fu_1429_p2;
wire   [0:0] and_ln117_1_fu_1435_p2;
wire   [31:0] bitcast_ln119_fu_1449_p1;
wire   [31:0] bitcast_ln119_1_fu_1466_p1;
wire   [7:0] tmp_75_fu_1452_p4;
wire   [22:0] trunc_ln119_fu_1462_p1;
wire   [0:0] icmp_ln119_1_fu_1490_p2;
wire   [0:0] icmp_ln119_fu_1484_p2;
wire   [7:0] tmp_76_fu_1470_p4;
wire   [22:0] trunc_ln119_1_fu_1480_p1;
wire   [0:0] icmp_ln119_3_fu_1508_p2;
wire   [0:0] icmp_ln119_2_fu_1502_p2;
wire   [0:0] or_ln119_fu_1496_p2;
wire   [0:0] or_ln119_1_fu_1514_p2;
wire   [0:0] and_ln119_fu_1520_p2;
wire   [0:0] and_ln119_1_fu_1526_p2;
wire   [31:0] bitcast_ln241_fu_1539_p1;
wire   [7:0] tmp_78_fu_1543_p4;
wire   [22:0] trunc_ln241_fu_1553_p1;
wire   [0:0] or_ln241_fu_1569_p2;
wire   [0:0] and_ln241_fu_1573_p2;
reg    grp_fu_346_ce;
reg    grp_fu_350_ce;
reg    grp_fu_354_ce;
reg   [4:0] grp_fu_354_opcode;
reg    grp_fu_359_ce;
reg   [4:0] grp_fu_359_opcode;
wire   [31:0] grp_fu_1845_p2;
wire   [31:0] grp_fu_1845_p0;
wire   [31:0] grp_fu_1845_p1;
reg    grp_fu_1845_ce;
reg   [0:0] ap_return_preg;
reg   [57:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 58'd1;
#0 info_dua_res = 32'd0;
#0 grp_is_primal_infeasible_fu_317_ap_start_reg = 1'b0;
#0 grp_is_dual_infeasible_fu_337_ap_start_reg = 1'b0;
#0 ap_return_preg = 1'd0;
end

myFunction_is_primal_infeasible grp_is_primal_infeasible_fu_317(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_is_primal_infeasible_fu_317_ap_start),
    .ap_done(grp_is_primal_infeasible_fu_317_ap_done),
    .ap_idle(grp_is_primal_infeasible_fu_317_ap_idle),
    .ap_ready(grp_is_primal_infeasible_fu_317_ap_ready),
    .eps_prim_inf(eps_dual_inf_reg_1736),
    .udata_address0(grp_is_primal_infeasible_fu_317_udata_address0),
    .udata_ce0(grp_is_primal_infeasible_fu_317_udata_ce0),
    .udata_q0(udata_q0),
    .ldata_address0(grp_is_primal_infeasible_fu_317_ldata_address0),
    .ldata_ce0(grp_is_primal_infeasible_fu_317_ldata_ce0),
    .ldata_q0(ldata_q0),
    .work_delta_y_address0(grp_is_primal_infeasible_fu_317_work_delta_y_address0),
    .work_delta_y_ce0(grp_is_primal_infeasible_fu_317_work_delta_y_ce0),
    .work_delta_y_we0(grp_is_primal_infeasible_fu_317_work_delta_y_we0),
    .work_delta_y_d0(grp_is_primal_infeasible_fu_317_work_delta_y_d0),
    .work_delta_y_q0(work_delta_y_q0),
    .Adata_x_address0(grp_is_primal_infeasible_fu_317_Adata_x_address0),
    .Adata_x_ce0(grp_is_primal_infeasible_fu_317_Adata_x_ce0),
    .Adata_x_q0(Adata_x_q0),
    .ap_return(grp_is_primal_infeasible_fu_317_ap_return),
    .grp_fu_346_p_din0(grp_is_primal_infeasible_fu_317_grp_fu_346_p_din0),
    .grp_fu_346_p_din1(grp_is_primal_infeasible_fu_317_grp_fu_346_p_din1),
    .grp_fu_346_p_opcode(grp_is_primal_infeasible_fu_317_grp_fu_346_p_opcode),
    .grp_fu_346_p_dout0(grp_is_primal_infeasible_fu_317_grp_fu_346_p_dout0),
    .grp_fu_346_p_ce(grp_is_primal_infeasible_fu_317_grp_fu_346_p_ce),
    .grp_fu_350_p_din0(grp_is_primal_infeasible_fu_317_grp_fu_350_p_din0),
    .grp_fu_350_p_din1(grp_is_primal_infeasible_fu_317_grp_fu_350_p_din1),
    .grp_fu_350_p_dout0(grp_is_primal_infeasible_fu_317_grp_fu_350_p_dout0),
    .grp_fu_350_p_ce(grp_is_primal_infeasible_fu_317_grp_fu_350_p_ce),
    .grp_fu_1845_p_din0(grp_is_primal_infeasible_fu_317_grp_fu_1845_p_din0),
    .grp_fu_1845_p_din1(grp_is_primal_infeasible_fu_317_grp_fu_1845_p_din1),
    .grp_fu_1845_p_dout0(grp_is_primal_infeasible_fu_317_grp_fu_1845_p_dout0),
    .grp_fu_1845_p_ce(grp_is_primal_infeasible_fu_317_grp_fu_1845_p_ce),
    .grp_fu_354_p_din0(grp_is_primal_infeasible_fu_317_grp_fu_354_p_din0),
    .grp_fu_354_p_din1(grp_is_primal_infeasible_fu_317_grp_fu_354_p_din1),
    .grp_fu_354_p_opcode(grp_is_primal_infeasible_fu_317_grp_fu_354_p_opcode),
    .grp_fu_354_p_dout0(grp_is_primal_infeasible_fu_317_grp_fu_354_p_dout0),
    .grp_fu_354_p_ce(grp_is_primal_infeasible_fu_317_grp_fu_354_p_ce),
    .grp_fu_359_p_din0(grp_is_primal_infeasible_fu_317_grp_fu_359_p_din0),
    .grp_fu_359_p_din1(grp_is_primal_infeasible_fu_317_grp_fu_359_p_din1),
    .grp_fu_359_p_opcode(grp_is_primal_infeasible_fu_317_grp_fu_359_p_opcode),
    .grp_fu_359_p_dout0(grp_is_primal_infeasible_fu_317_grp_fu_359_p_dout0),
    .grp_fu_359_p_ce(grp_is_primal_infeasible_fu_317_grp_fu_359_p_ce)
);

myFunction_is_dual_infeasible grp_is_dual_infeasible_fu_337(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_is_dual_infeasible_fu_337_ap_start),
    .ap_done(grp_is_dual_infeasible_fu_337_ap_done),
    .ap_idle(grp_is_dual_infeasible_fu_337_ap_idle),
    .ap_ready(grp_is_dual_infeasible_fu_337_ap_ready),
    .eps_dual_inf(eps_dual_inf_reg_1736),
    .work_delta_x_address0(grp_is_dual_infeasible_fu_337_work_delta_x_address0),
    .work_delta_x_ce0(grp_is_dual_infeasible_fu_337_work_delta_x_ce0),
    .work_delta_x_q0(work_delta_x_q0),
    .qdata_address0(grp_is_dual_infeasible_fu_337_qdata_address0),
    .qdata_ce0(grp_is_dual_infeasible_fu_337_qdata_ce0),
    .qdata_q0(qdata_q0),
    .grp_fu_350_p_din0(grp_is_dual_infeasible_fu_337_grp_fu_350_p_din0),
    .grp_fu_350_p_din1(grp_is_dual_infeasible_fu_337_grp_fu_350_p_din1),
    .grp_fu_350_p_dout0(grp_is_dual_infeasible_fu_337_grp_fu_350_p_dout0),
    .grp_fu_350_p_ce(grp_is_dual_infeasible_fu_337_grp_fu_350_p_ce),
    .grp_fu_359_p_din0(grp_is_dual_infeasible_fu_337_grp_fu_359_p_din0),
    .grp_fu_359_p_din1(grp_is_dual_infeasible_fu_337_grp_fu_359_p_din1),
    .grp_fu_359_p_opcode(grp_is_dual_infeasible_fu_337_grp_fu_359_p_opcode),
    .grp_fu_359_p_dout0(grp_is_dual_infeasible_fu_337_grp_fu_359_p_dout0),
    .grp_fu_359_p_ce(grp_is_dual_infeasible_fu_337_grp_fu_359_p_ce)
);

myFunction_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U100(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_346_p0),
    .din1(grp_fu_346_p1),
    .ce(grp_fu_346_ce),
    .dout(grp_fu_346_p2)
);

myFunction_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U101(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_350_p0),
    .din1(grp_fu_350_p1),
    .ce(grp_fu_350_ce),
    .dout(grp_fu_350_p2)
);

myFunction_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U102(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_354_p0),
    .din1(grp_fu_354_p1),
    .ce(grp_fu_354_ce),
    .opcode(grp_fu_354_opcode),
    .dout(grp_fu_354_p2)
);

myFunction_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U103(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_359_p0),
    .din1(grp_fu_359_p1),
    .ce(grp_fu_359_ce),
    .opcode(grp_fu_359_opcode),
    .dout(grp_fu_359_p2)
);

myFunction_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U104(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1845_p0),
    .din1(grp_fu_1845_p1),
    .ce(grp_fu_1845_ce),
    .dout(grp_fu_1845_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if (((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57))) begin
            ap_return_preg <= ap_phi_mux_retval_0_phi_fu_300_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_is_dual_infeasible_fu_337_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state56) & (1'd0 == and_ln241_1_fu_1578_p2))) begin
            grp_is_dual_infeasible_fu_337_ap_start_reg <= 1'b1;
        end else if ((grp_is_dual_infeasible_fu_337_ap_ready == 1'b1)) begin
            grp_is_dual_infeasible_fu_337_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_is_primal_infeasible_fu_317_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state27) & (1'd0 == and_ln237_1_reg_1732))) begin
            grp_is_primal_infeasible_fu_317_ap_start_reg <= 1'b1;
        end else if ((grp_is_primal_infeasible_fu_317_ap_ready == 1'b1)) begin
            grp_is_primal_infeasible_fu_317_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln14_fu_493_p2 == 1'd1))) begin
        i_76_reg_191 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        i_76_reg_191 <= i_77_reg_1674;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        i_78_reg_239 <= i_79_reg_1742;
    end else if (((1'b0 == ap_block_state28_on_subcall_done) & (1'b1 == ap_CS_fsm_state28))) begin
        i_78_reg_239 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_4_fu_976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
        i_80_reg_262 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        i_80_reg_262 <= i_81_reg_1774;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_5_fu_1136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state35))) begin
        i_82_reg_285 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        i_82_reg_285 <= i_83_reg_1787;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (or_ln229_fu_476_p2 == 1'd0))) begin
        i_reg_168 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i_reg_168 <= i_75_reg_1642;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln14_fu_493_p2 == 1'd1))) begin
        max_12_reg_179 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        max_12_reg_179 <= max_14_fu_805_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        max_15_reg_227 <= max_rel_eps_6_fu_1123_p3;
    end else if (((1'b0 == ap_block_state28_on_subcall_done) & (1'b1 == ap_CS_fsm_state28))) begin
        max_15_reg_227 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_4_fu_976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
        max_18_reg_250 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        max_18_reg_250 <= temp_rel_eps_fu_1184_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_5_fu_1136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state35))) begin
        max_20_reg_273 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        max_20_reg_273 <= max_22_fu_1350_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (or_ln229_fu_476_p2 == 1'd0))) begin
        max_reg_156 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        max_reg_156 <= max_rel_eps_5_fu_640_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln237_1_reg_1732) & (1'b1 == ap_CS_fsm_state27))) begin
        prim_inf_check_1_reg_202 <= 1'd0;
    end else if (((1'b0 == ap_block_state28_on_subcall_done) & (1'b1 == ap_CS_fsm_state28) & (1'd0 == and_ln237_1_reg_1732))) begin
        prim_inf_check_1_reg_202 <= grp_is_primal_infeasible_fu_317_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln237_1_reg_1732) & (1'b1 == ap_CS_fsm_state27))) begin
        prim_res_check_reg_214 <= 1'd1;
    end else if (((1'b0 == ap_block_state28_on_subcall_done) & (1'b1 == ap_CS_fsm_state28) & (1'd0 == and_ln237_1_reg_1732))) begin
        prim_res_check_reg_214 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57) & (((prim_inf_check_1_reg_202 == 1'd0) & (1'd0 == and_ln241_1_reg_1841) & (or_ln229_reg_1638 == 1'd0)) | ((prim_res_check_reg_214 == 1'd0) & (prim_inf_check_1_reg_202 == 1'd0) & (or_ln229_reg_1638 == 1'd0))))) begin
        retval_0_reg_296 <= 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state58) | ((prim_res_check_reg_214 == 1'd1) & (1'b0 == ap_block_state57_on_subcall_done) & (1'd1 == and_ln241_1_reg_1841) & (1'b1 == ap_CS_fsm_state57) & (or_ln229_reg_1638 == 1'd0) & (approximate_read_read_fu_98_p2 == 1'd1)) | ((prim_res_check_reg_214 == 1'd1) & (1'b0 == ap_block_state57_on_subcall_done) & (1'd1 == and_ln241_1_reg_1841) & (1'b1 == ap_CS_fsm_state57) & (or_ln229_reg_1638 == 1'd0) & (approximate_read_read_fu_98_p2 == 1'd0)) | ((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57) & (((prim_inf_check_1_reg_202 == 1'd1) & (1'd0 == and_ln241_1_reg_1841) & (or_ln229_reg_1638 == 1'd0)) | ((prim_res_check_reg_214 == 1'd0) & (prim_inf_check_1_reg_202 == 1'd1) & (or_ln229_reg_1638 == 1'd0)))))) begin
        retval_0_reg_296 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        abs_v_i_2_reg_1694 <= abs_v_i_2_fu_715_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        abs_v_i_3_reg_1762 <= abs_v_i_3_fu_1033_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        abs_v_i_4_reg_1807 <= abs_v_i_4_fu_1260_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        abs_v_i_reg_1662 <= abs_v_i_fu_550_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        and_ln237_1_reg_1732 <= and_ln237_1_fu_951_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        and_ln241_1_reg_1841 <= and_ln241_1_fu_1578_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        and_ln83_1_reg_1706 <= and_ln83_1_fu_890_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        eps_dual_inf_reg_1736[0] <= eps_dual_inf_fu_957_p3[0];
eps_dual_inf_reg_1736[6 : 3] <= eps_dual_inf_fu_957_p3[6 : 3];
eps_dual_inf_reg_1736[8] <= eps_dual_inf_fu_957_p3[8];
eps_dual_inf_reg_1736[10] <= eps_dual_inf_fu_957_p3[10];
eps_dual_inf_reg_1736[13] <= eps_dual_inf_fu_957_p3[13];
eps_dual_inf_reg_1736[15] <= eps_dual_inf_fu_957_p3[15];
eps_dual_inf_reg_1736[17] <= eps_dual_inf_fu_957_p3[17];
eps_dual_inf_reg_1736[20] <= eps_dual_inf_fu_957_p3[20];
eps_dual_inf_reg_1736[22] <= eps_dual_inf_fu_957_p3[22];
eps_dual_inf_reg_1736[25] <= eps_dual_inf_fu_957_p3[25];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        eps_rel_reg_1711[2] <= eps_rel_fu_896_p3[2];
eps_rel_reg_1711[6 : 5] <= eps_rel_fu_896_p3[6 : 5];
eps_rel_reg_1711[8] <= eps_rel_fu_896_p3[8];
eps_rel_reg_1711[10] <= eps_rel_fu_896_p3[10];
eps_rel_reg_1711[15 : 14] <= eps_rel_fu_896_p3[15 : 14];
eps_rel_reg_1711[21] <= eps_rel_fu_896_p3[21];
eps_rel_reg_1711[23] <= eps_rel_fu_896_p3[23];
eps_rel_reg_1711[26 : 25] <= eps_rel_fu_896_p3[26 : 25];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_75_reg_1642 <= i_75_fu_482_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_77_reg_1674 <= i_77_fu_647_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        i_79_reg_1742 <= i_79_fu_965_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        i_81_reg_1774 <= i_81_fu_1130_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        i_83_reg_1787 <= i_83_fu_1192_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        icmp_ln237_1_reg_1727 <= icmp_ln237_1_fu_936_p2;
        icmp_ln237_reg_1722 <= icmp_ln237_fu_930_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        icmp_ln241_1_reg_1836 <= icmp_ln241_1_fu_1563_p2;
        icmp_ln241_reg_1831 <= icmp_ln241_fu_1557_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        max_rel_eps_3_reg_1819 <= max_rel_eps_3_fu_1441_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        max_rel_eps_4_reg_1826 <= max_rel_eps_4_fu_1532_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        or_ln229_1_reg_1628 <= or_ln229_1_fu_423_p2;
        or_ln229_2_reg_1633 <= or_ln229_2_fu_464_p2;
        or_ln229_reg_1638 <= or_ln229_fu_476_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        qdata_load_reg_1755 <= qdata_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state19))) begin
        reg_374 <= grp_fu_350_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state24))) begin
        reg_379 <= grp_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        work_Ax_load_reg_1687 <= work_Ax_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        work_Px_load_reg_1800 <= work_Px_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        work_z_load_reg_1655 <= work_z_q0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) & (((prim_inf_check_1_reg_202 == 1'd0) & (1'd0 == and_ln241_1_reg_1841) & (or_ln229_reg_1638 == 1'd0)) | ((prim_res_check_reg_214 == 1'd0) & (prim_inf_check_1_reg_202 == 1'd0) & (or_ln229_reg_1638 == 1'd0))))) begin
        ap_phi_mux_retval_0_phi_fu_300_p10 = 1'd0;
    end else if ((((prim_res_check_reg_214 == 1'd1) & (1'd1 == and_ln241_1_reg_1841) & (1'b1 == ap_CS_fsm_state57) & (or_ln229_reg_1638 == 1'd0) & (approximate_read_read_fu_98_p2 == 1'd1)) | ((prim_res_check_reg_214 == 1'd1) & (1'd1 == and_ln241_1_reg_1841) & (1'b1 == ap_CS_fsm_state57) & (or_ln229_reg_1638 == 1'd0) & (approximate_read_read_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_fsm_state57) & (((prim_inf_check_1_reg_202 == 1'd1) & (1'd0 == and_ln241_1_reg_1841) & (or_ln229_reg_1638 == 1'd0)) | ((prim_res_check_reg_214 == 1'd0) & (prim_inf_check_1_reg_202 == 1'd1) & (or_ln229_reg_1638 == 1'd0)))))) begin
        ap_phi_mux_retval_0_phi_fu_300_p10 = 1'd1;
    end else begin
        ap_phi_mux_retval_0_phi_fu_300_p10 = retval_0_reg_296;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57))) begin
        ap_return = ap_phi_mux_retval_0_phi_fu_300_p10;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_1845_ce = grp_is_primal_infeasible_fu_317_grp_fu_1845_p_ce;
    end else begin
        grp_fu_1845_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_346_ce = grp_is_primal_infeasible_fu_317_grp_fu_346_p_ce;
    end else begin
        grp_fu_346_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_346_p0 = grp_is_primal_infeasible_fu_317_grp_fu_346_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_346_p0 = eps_rel_reg_1711;
    end else begin
        grp_fu_346_p0 = eps_rel_reg_1711;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_346_p1 = grp_is_primal_infeasible_fu_317_grp_fu_346_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state20))) begin
        grp_fu_346_p1 = reg_374;
    end else begin
        grp_fu_346_p1 = reg_374;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56))) begin
        grp_fu_350_ce = grp_is_dual_infeasible_fu_337_grp_fu_350_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_350_ce = grp_is_primal_infeasible_fu_317_grp_fu_350_p_ce;
    end else begin
        grp_fu_350_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56))) begin
        grp_fu_350_p0 = grp_is_dual_infeasible_fu_337_grp_fu_350_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_350_p0 = grp_is_primal_infeasible_fu_317_grp_fu_350_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_350_p0 = eps_rel_reg_1711;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_350_p0 = eps_rel_fu_896_p3;
    end else begin
        grp_fu_350_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56))) begin
        grp_fu_350_p1 = grp_is_dual_infeasible_fu_337_grp_fu_350_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_350_p1 = grp_is_primal_infeasible_fu_317_grp_fu_350_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_350_p1 = max_rel_eps_4_reg_1826;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_350_p1 = max_rel_eps_fu_904_p3;
    end else begin
        grp_fu_350_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_354_ce = grp_is_primal_infeasible_fu_317_grp_fu_354_p_ce;
    end else begin
        grp_fu_354_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_354_opcode = grp_is_primal_infeasible_fu_317_grp_fu_354_p_opcode;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state25) | ((icmp_ln14_5_fu_1136_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state35)))) begin
        grp_fu_354_opcode = 5'd4;
    end else if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state7) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((icmp_ln14_6_fu_1203_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state37)) | ((icmp_ln14_3_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9)))) begin
        grp_fu_354_opcode = 5'd2;
    end else begin
        grp_fu_354_opcode = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_354_p0 = grp_is_primal_infeasible_fu_317_grp_fu_354_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state55)) begin
        grp_fu_354_p0 = info_dua_res;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_354_p0 = max_rel_eps_3_reg_1819;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_354_p0 = abs_v_i_4_reg_1807;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_fu_354_p0 = work_Px_load_reg_1800;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        grp_fu_354_p0 = max_15_reg_227;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_354_p0 = max_18_reg_250;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_354_p0 = abs_v_i_3_reg_1762;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_354_p0 = qdata_load_reg_1755;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_354_p0 = abs_v_i_2_reg_1694;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_354_p0 = work_Ax_load_reg_1687;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_354_p0 = max_reg_156;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_354_p0 = abs_v_i_reg_1662;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_354_p0 = work_z_load_reg_1655;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_fu_354_p0 = info_pri_res;
    end else begin
        grp_fu_354_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_354_p1 = grp_is_primal_infeasible_fu_317_grp_fu_354_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state41))) begin
        grp_fu_354_p1 = max_20_reg_273;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        grp_fu_354_p1 = max_18_reg_250;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_354_p1 = max_15_reg_227;
    end else if (((1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_fu_354_p1 = reg_379;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_354_p1 = max_12_reg_179;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_354_p1 = ap_phi_mux_max_12_phi_fu_183_p4;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_354_p1 = max_reg_156;
    end else if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state35))) begin
        grp_fu_354_p1 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_354_p1 = 32'd1900671690;
    end else begin
        grp_fu_354_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56))) begin
        grp_fu_359_ce = grp_is_dual_infeasible_fu_337_grp_fu_359_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_359_ce = grp_is_primal_infeasible_fu_317_grp_fu_359_p_ce;
    end else begin
        grp_fu_359_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56))) begin
        grp_fu_359_opcode = grp_is_dual_infeasible_fu_337_grp_fu_359_p_opcode;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_359_opcode = grp_is_primal_infeasible_fu_317_grp_fu_359_p_opcode;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_359_opcode = 5'd2;
    end else begin
        grp_fu_359_opcode = 5'd2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56))) begin
        grp_fu_359_p0 = grp_is_dual_infeasible_fu_337_grp_fu_359_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_359_p0 = grp_is_primal_infeasible_fu_317_grp_fu_359_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_359_p0 = info_dua_res;
    end else begin
        grp_fu_359_p0 = info_dua_res;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56))) begin
        grp_fu_359_p1 = grp_is_dual_infeasible_fu_337_grp_fu_359_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_359_p1 = grp_is_primal_infeasible_fu_317_grp_fu_359_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_359_p1 = 32'd1900671690;
    end else begin
        grp_fu_359_p1 = 32'd1900671690;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        info_status_val = 5'd25;
    end else if (((prim_res_check_reg_214 == 1'd1) & (1'b0 == ap_block_state57_on_subcall_done) & (1'd1 == and_ln241_1_reg_1841) & (1'b1 == ap_CS_fsm_state57) & (or_ln229_reg_1638 == 1'd0) & (approximate_read_read_fu_98_p2 == 1'd1))) begin
        info_status_val = 5'd2;
    end else if (((prim_res_check_reg_214 == 1'd1) & (1'b0 == ap_block_state57_on_subcall_done) & (1'd1 == and_ln241_1_reg_1841) & (1'b1 == ap_CS_fsm_state57) & (or_ln229_reg_1638 == 1'd0) & (approximate_read_read_fu_98_p2 == 1'd0))) begin
        info_status_val = 5'd1;
    end else if (((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57) & (((prim_inf_check_1_reg_202 == 1'd1) & (1'd0 == and_ln241_1_reg_1841) & (or_ln229_reg_1638 == 1'd0)) | ((prim_res_check_reg_214 == 1'd0) & (prim_inf_check_1_reg_202 == 1'd1) & (or_ln229_reg_1638 == 1'd0))))) begin
        info_status_val = select_ln210_fu_1584_p3;
    end else begin
        info_status_val = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state58) | ((prim_res_check_reg_214 == 1'd1) & (1'b0 == ap_block_state57_on_subcall_done) & (1'd1 == and_ln241_1_reg_1841) & (1'b1 == ap_CS_fsm_state57) & (or_ln229_reg_1638 == 1'd0) & (approximate_read_read_fu_98_p2 == 1'd1)) | ((prim_res_check_reg_214 == 1'd1) & (1'b0 == ap_block_state57_on_subcall_done) & (1'd1 == and_ln241_1_reg_1841) & (1'b1 == ap_CS_fsm_state57) & (or_ln229_reg_1638 == 1'd0) & (approximate_read_read_fu_98_p2 == 1'd0)) | ((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57) & (((prim_inf_check_1_reg_202 == 1'd1) & (1'd0 == and_ln241_1_reg_1841) & (or_ln229_reg_1638 == 1'd0)) | ((prim_res_check_reg_214 == 1'd0) & (prim_inf_check_1_reg_202 == 1'd1) & (or_ln229_reg_1638 == 1'd0)))))) begin
        info_status_val_ap_vld = 1'b1;
    end else begin
        info_status_val_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        qdata_address0 = zext_ln14_2_fu_971_p1;
    end else if (((ap_predicate_op370_call_state57 == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
        qdata_address0 = grp_is_dual_infeasible_fu_337_qdata_address0;
    end else begin
        qdata_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        qdata_ce0 = 1'b1;
    end else if (((ap_predicate_op370_call_state57 == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
        qdata_ce0 = grp_is_dual_infeasible_fu_337_qdata_ce0;
    end else begin
        qdata_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        work_Ax_ce0 = 1'b1;
    end else begin
        work_Ax_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        work_Px_ce0 = 1'b1;
    end else begin
        work_Px_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        work_z_ce0 = 1'b1;
    end else begin
        work_z_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (or_ln229_fu_476_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln14_fu_493_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln14_3_fu_658_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((1'b0 == ap_block_state28_on_subcall_done) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            if (((icmp_ln14_4_fu_976_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state35 : begin
            if (((icmp_ln14_5_fu_1136_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state37 : begin
            if (((icmp_ln14_6_fu_1203_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            if (((1'b0 == ap_block_state57_on_subcall_done) & (1'b1 == ap_CS_fsm_state57))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Adata_x_address0 = grp_is_primal_infeasible_fu_317_Adata_x_address0;

assign Adata_x_ce0 = grp_is_primal_infeasible_fu_317_Adata_x_ce0;

assign abs_v_i_2_fu_715_p3 = ((and_ln14_12_fu_699_p2[0:0] == 1'b1) ? bitcast_ln14_11_fu_711_p1 : work_Ax_load_reg_1687);

assign abs_v_i_3_fu_1033_p3 = ((and_ln14_15_fu_1017_p2[0:0] == 1'b1) ? bitcast_ln14_13_fu_1029_p1 : qdata_load_reg_1755);

assign abs_v_i_4_fu_1260_p3 = ((and_ln14_19_fu_1244_p2[0:0] == 1'b1) ? bitcast_ln14_17_fu_1256_p1 : work_Px_load_reg_1800);

assign abs_v_i_fu_550_p3 = ((and_ln14_fu_534_p2[0:0] == 1'b1) ? bitcast_ln14_9_fu_546_p1 : work_z_load_reg_1655);

assign and_ln117_1_fu_1435_p2 = (grp_fu_354_p2 & and_ln117_fu_1429_p2);

assign and_ln117_fu_1429_p2 = (or_ln117_fu_1405_p2 & or_ln117_1_fu_1423_p2);

assign and_ln119_1_fu_1526_p2 = (grp_fu_354_p2 & and_ln119_fu_1520_p2);

assign and_ln119_fu_1520_p2 = (or_ln119_fu_1496_p2 & or_ln119_1_fu_1514_p2);

assign and_ln14_10_fu_628_p2 = (or_ln14_11_fu_622_p2 & or_ln14_10_fu_604_p2);

assign and_ln14_11_fu_634_p2 = (grp_fu_354_p2 & and_ln14_10_fu_628_p2);

assign and_ln14_12_fu_699_p2 = (or_ln14_12_fu_693_p2 & grp_fu_354_p2);

assign and_ln14_13_fu_793_p2 = (or_ln14_14_fu_787_p2 & or_ln14_13_fu_769_p2);

assign and_ln14_14_fu_799_p2 = (grp_fu_354_p2 & and_ln14_13_fu_793_p2);

assign and_ln14_15_fu_1017_p2 = (or_ln14_15_fu_1011_p2 & grp_fu_354_p2);

assign and_ln14_16_fu_1111_p2 = (or_ln14_17_fu_1105_p2 & or_ln14_16_fu_1087_p2);

assign and_ln14_17_fu_1117_p2 = (grp_fu_354_p2 & and_ln14_16_fu_1111_p2);

assign and_ln14_18_fu_1178_p2 = (or_ln14_18_fu_1172_p2 & grp_fu_354_p2);

assign and_ln14_19_fu_1244_p2 = (or_ln14_19_fu_1238_p2 & grp_fu_354_p2);

assign and_ln14_20_fu_1338_p2 = (or_ln14_21_fu_1332_p2 & or_ln14_20_fu_1314_p2);

assign and_ln14_21_fu_1344_p2 = (grp_fu_354_p2 & and_ln14_20_fu_1338_p2);

assign and_ln14_fu_534_p2 = (or_ln14_fu_528_p2 & grp_fu_354_p2);

assign and_ln229_1_fu_470_p2 = (or_ln229_2_fu_464_p2 & grp_fu_359_p2);

assign and_ln229_fu_429_p2 = (or_ln229_1_fu_423_p2 & grp_fu_354_p2);

assign and_ln237_1_fu_951_p2 = (grp_fu_354_p2 & and_ln237_fu_946_p2);

assign and_ln237_fu_946_p2 = (or_ln237_fu_942_p2 & or_ln229_1_reg_1628);

assign and_ln241_1_fu_1578_p2 = (grp_fu_354_p2 & and_ln241_fu_1573_p2);

assign and_ln241_fu_1573_p2 = (or_ln241_fu_1569_p2 & or_ln229_2_reg_1633);

assign and_ln83_1_fu_890_p2 = (grp_fu_354_p2 & and_ln83_fu_884_p2);

assign and_ln83_fu_884_p2 = (or_ln83_fu_860_p2 & or_ln83_1_fu_878_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state28_on_subcall_done = ((grp_is_primal_infeasible_fu_317_ap_done == 1'b0) & (1'd0 == and_ln237_1_reg_1732));
end

always @ (*) begin
    ap_block_state57_on_subcall_done = ((ap_predicate_op370_call_state57 == 1'b1) & (grp_is_dual_infeasible_fu_337_ap_done == 1'b0));
end

assign ap_phi_mux_max_12_phi_fu_183_p4 = max_12_reg_179;

always @ (*) begin
    ap_predicate_op370_call_state57 = ((1'd0 == and_ln241_1_reg_1841) & (or_ln229_reg_1638 == 1'd0));
end

assign approximate_read_read_fu_98_p2 = approximate;

assign bitcast_ln117_1_fu_1375_p1 = max_18_reg_250;

assign bitcast_ln117_fu_1357_p1 = max_15_reg_227;

assign bitcast_ln119_1_fu_1466_p1 = max_20_reg_273;

assign bitcast_ln119_fu_1449_p1 = max_rel_eps_3_reg_1819;

assign bitcast_ln14_11_fu_711_p1 = xor_ln14_2_fu_705_p2;

assign bitcast_ln14_12_fu_557_p1 = abs_v_i_reg_1662;

assign bitcast_ln14_13_fu_1029_p1 = xor_ln14_3_fu_1023_p2;

assign bitcast_ln14_14_fu_574_p1 = max_reg_156;

assign bitcast_ln14_15_fu_664_p1 = work_Ax_load_reg_1687;

assign bitcast_ln14_16_fu_722_p1 = abs_v_i_2_reg_1694;

assign bitcast_ln14_17_fu_1256_p1 = xor_ln14_4_fu_1250_p2;

assign bitcast_ln14_18_fu_739_p1 = max_12_reg_179;

assign bitcast_ln14_19_fu_982_p1 = qdata_load_reg_1755;

assign bitcast_ln14_20_fu_1040_p1 = abs_v_i_3_reg_1762;

assign bitcast_ln14_21_fu_1057_p1 = max_15_reg_227;

assign bitcast_ln14_22_fu_1142_p1 = max_18_reg_250;

assign bitcast_ln14_23_fu_1209_p1 = work_Px_load_reg_1800;

assign bitcast_ln14_24_fu_1267_p1 = abs_v_i_4_reg_1807;

assign bitcast_ln14_25_fu_1284_p1 = max_20_reg_273;

assign bitcast_ln14_9_fu_546_p1 = xor_ln14_fu_540_p2;

assign bitcast_ln14_fu_499_p1 = work_z_load_reg_1655;

assign bitcast_ln229_1_fu_435_p1 = info_dua_res;

assign bitcast_ln229_fu_394_p1 = info_pri_res;

assign bitcast_ln237_fu_912_p1 = reg_379;

assign bitcast_ln241_fu_1539_p1 = reg_379;

assign bitcast_ln83_1_fu_830_p1 = max_12_reg_179;

assign bitcast_ln83_fu_812_p1 = max_reg_156;

assign eps_dual_inf_fu_957_p3 = ((approximate[0:0] == 1'b1) ? 32'd981668462 : 32'd953267991);

assign eps_rel_fu_896_p3 = ((approximate[0:0] == 1'b1) ? 32'd1008981771 : 32'd981668463);

assign grp_fu_1845_p0 = grp_is_primal_infeasible_fu_317_grp_fu_1845_p_din0;

assign grp_fu_1845_p1 = grp_is_primal_infeasible_fu_317_grp_fu_1845_p_din1;

assign grp_is_dual_infeasible_fu_337_ap_start = grp_is_dual_infeasible_fu_337_ap_start_reg;

assign grp_is_dual_infeasible_fu_337_grp_fu_350_p_dout0 = grp_fu_350_p2;

assign grp_is_dual_infeasible_fu_337_grp_fu_359_p_dout0 = grp_fu_359_p2;

assign grp_is_primal_infeasible_fu_317_ap_start = grp_is_primal_infeasible_fu_317_ap_start_reg;

assign grp_is_primal_infeasible_fu_317_grp_fu_1845_p_dout0 = grp_fu_1845_p2;

assign grp_is_primal_infeasible_fu_317_grp_fu_346_p_dout0 = grp_fu_346_p2;

assign grp_is_primal_infeasible_fu_317_grp_fu_350_p_dout0 = grp_fu_350_p2;

assign grp_is_primal_infeasible_fu_317_grp_fu_354_p_dout0 = grp_fu_354_p2;

assign grp_is_primal_infeasible_fu_317_grp_fu_359_p_dout0 = grp_fu_359_p2;

assign i_75_fu_482_p2 = (i_reg_168 + 5'd1);

assign i_77_fu_647_p2 = (i_76_reg_191 + 5'd1);

assign i_79_fu_965_p2 = (i_78_reg_239 + 4'd1);

assign i_81_fu_1130_p2 = (i_80_reg_262 + 4'd1);

assign i_83_fu_1192_p2 = (i_82_reg_285 + 4'd1);

assign icmp_ln117_1_fu_1399_p2 = ((trunc_ln117_fu_1371_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln117_2_fu_1411_p2 = ((tmp_73_fu_1379_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln117_3_fu_1417_p2 = ((trunc_ln117_1_fu_1389_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_1393_p2 = ((tmp_72_fu_1361_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln119_1_fu_1490_p2 = ((trunc_ln119_fu_1462_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln119_2_fu_1502_p2 = ((tmp_76_fu_1470_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln119_3_fu_1508_p2 = ((trunc_ln119_1_fu_1480_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_1484_p2 = ((tmp_75_fu_1452_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_25_fu_516_p2 = ((tmp_50_fu_502_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_26_fu_522_p2 = ((trunc_ln14_fu_512_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_27_fu_592_p2 = ((tmp_52_fu_560_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_28_fu_598_p2 = ((trunc_ln14_10_fu_570_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_29_fu_610_p2 = ((tmp_53_fu_578_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_30_fu_616_p2 = ((trunc_ln14_11_fu_588_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_31_fu_681_p2 = ((tmp_60_fu_667_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_32_fu_687_p2 = ((trunc_ln14_12_fu_677_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_33_fu_757_p2 = ((tmp_62_fu_725_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_34_fu_763_p2 = ((trunc_ln14_13_fu_735_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_35_fu_775_p2 = ((tmp_63_fu_743_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_36_fu_781_p2 = ((trunc_ln14_14_fu_753_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_37_fu_999_p2 = ((tmp_65_fu_985_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_38_fu_1005_p2 = ((trunc_ln14_15_fu_995_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_39_fu_1075_p2 = ((tmp_67_fu_1043_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_3_fu_658_p2 = ((i_76_reg_191 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln14_40_fu_1081_p2 = ((trunc_ln14_16_fu_1053_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_41_fu_1093_p2 = ((tmp_68_fu_1061_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_42_fu_1099_p2 = ((trunc_ln14_17_fu_1071_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_43_fu_1160_p2 = ((tmp_70_fu_1146_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_44_fu_1166_p2 = ((trunc_ln14_18_fu_1156_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_45_fu_1226_p2 = ((tmp_80_fu_1212_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_46_fu_1232_p2 = ((trunc_ln14_19_fu_1222_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_47_fu_1302_p2 = ((tmp_82_fu_1270_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_48_fu_1308_p2 = ((trunc_ln14_20_fu_1280_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_49_fu_1320_p2 = ((tmp_83_fu_1288_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_4_fu_976_p2 = ((i_78_reg_239 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln14_50_fu_1326_p2 = ((trunc_ln14_21_fu_1298_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_5_fu_1136_p2 = ((i_80_reg_262 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln14_6_fu_1203_p2 = ((i_82_reg_285 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_493_p2 = ((i_reg_168 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln229_1_fu_417_p2 = ((trunc_ln229_fu_407_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln229_2_fu_452_p2 = ((tmp_48_fu_438_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln229_3_fu_458_p2 = ((trunc_ln229_1_fu_448_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln229_fu_411_p2 = ((tmp_fu_397_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln237_1_fu_936_p2 = ((trunc_ln237_fu_926_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_930_p2 = ((tmp_58_fu_916_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln241_1_fu_1563_p2 = ((trunc_ln241_fu_1553_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_1557_p2 = ((tmp_78_fu_1543_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln83_1_fu_854_p2 = ((trunc_ln83_fu_826_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln83_2_fu_866_p2 = ((tmp_56_fu_834_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln83_3_fu_872_p2 = ((trunc_ln83_1_fu_844_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_848_p2 = ((tmp_55_fu_816_p4 != 8'd255) ? 1'b1 : 1'b0);

assign ldata_address0 = grp_is_primal_infeasible_fu_317_ldata_address0;

assign ldata_ce0 = grp_is_primal_infeasible_fu_317_ldata_ce0;

assign max_14_fu_805_p3 = ((and_ln14_14_fu_799_p2[0:0] == 1'b1) ? abs_v_i_2_reg_1694 : max_12_reg_179);

assign max_22_fu_1350_p3 = ((and_ln14_21_fu_1344_p2[0:0] == 1'b1) ? abs_v_i_4_reg_1807 : max_20_reg_273);

assign max_rel_eps_3_fu_1441_p3 = ((and_ln117_1_fu_1435_p2[0:0] == 1'b1) ? max_15_reg_227 : max_18_reg_250);

assign max_rel_eps_4_fu_1532_p3 = ((and_ln119_1_fu_1526_p2[0:0] == 1'b1) ? max_rel_eps_3_reg_1819 : max_20_reg_273);

assign max_rel_eps_5_fu_640_p3 = ((and_ln14_11_fu_634_p2[0:0] == 1'b1) ? abs_v_i_reg_1662 : max_reg_156);

assign max_rel_eps_6_fu_1123_p3 = ((and_ln14_17_fu_1117_p2[0:0] == 1'b1) ? abs_v_i_3_reg_1762 : max_15_reg_227);

assign max_rel_eps_fu_904_p3 = ((and_ln83_1_reg_1706[0:0] == 1'b1) ? max_reg_156 : max_12_reg_179);

assign or_ln117_1_fu_1423_p2 = (icmp_ln117_3_fu_1417_p2 | icmp_ln117_2_fu_1411_p2);

assign or_ln117_fu_1405_p2 = (icmp_ln117_fu_1393_p2 | icmp_ln117_1_fu_1399_p2);

assign or_ln119_1_fu_1514_p2 = (icmp_ln119_3_fu_1508_p2 | icmp_ln119_2_fu_1502_p2);

assign or_ln119_fu_1496_p2 = (icmp_ln119_fu_1484_p2 | icmp_ln119_1_fu_1490_p2);

assign or_ln14_10_fu_604_p2 = (icmp_ln14_28_fu_598_p2 | icmp_ln14_27_fu_592_p2);

assign or_ln14_11_fu_622_p2 = (icmp_ln14_30_fu_616_p2 | icmp_ln14_29_fu_610_p2);

assign or_ln14_12_fu_693_p2 = (icmp_ln14_32_fu_687_p2 | icmp_ln14_31_fu_681_p2);

assign or_ln14_13_fu_769_p2 = (icmp_ln14_34_fu_763_p2 | icmp_ln14_33_fu_757_p2);

assign or_ln14_14_fu_787_p2 = (icmp_ln14_36_fu_781_p2 | icmp_ln14_35_fu_775_p2);

assign or_ln14_15_fu_1011_p2 = (icmp_ln14_38_fu_1005_p2 | icmp_ln14_37_fu_999_p2);

assign or_ln14_16_fu_1087_p2 = (icmp_ln14_40_fu_1081_p2 | icmp_ln14_39_fu_1075_p2);

assign or_ln14_17_fu_1105_p2 = (icmp_ln14_42_fu_1099_p2 | icmp_ln14_41_fu_1093_p2);

assign or_ln14_18_fu_1172_p2 = (icmp_ln14_44_fu_1166_p2 | icmp_ln14_43_fu_1160_p2);

assign or_ln14_19_fu_1238_p2 = (icmp_ln14_46_fu_1232_p2 | icmp_ln14_45_fu_1226_p2);

assign or_ln14_20_fu_1314_p2 = (icmp_ln14_48_fu_1308_p2 | icmp_ln14_47_fu_1302_p2);

assign or_ln14_21_fu_1332_p2 = (icmp_ln14_50_fu_1326_p2 | icmp_ln14_49_fu_1320_p2);

assign or_ln14_fu_528_p2 = (icmp_ln14_26_fu_522_p2 | icmp_ln14_25_fu_516_p2);

assign or_ln229_1_fu_423_p2 = (icmp_ln229_fu_411_p2 | icmp_ln229_1_fu_417_p2);

assign or_ln229_2_fu_464_p2 = (icmp_ln229_3_fu_458_p2 | icmp_ln229_2_fu_452_p2);

assign or_ln229_fu_476_p2 = (and_ln229_fu_429_p2 | and_ln229_1_fu_470_p2);

assign or_ln237_fu_942_p2 = (icmp_ln237_reg_1722 | icmp_ln237_1_reg_1727);

assign or_ln241_fu_1569_p2 = (icmp_ln241_reg_1831 | icmp_ln241_1_reg_1836);

assign or_ln83_1_fu_878_p2 = (icmp_ln83_3_fu_872_p2 | icmp_ln83_2_fu_866_p2);

assign or_ln83_fu_860_p2 = (icmp_ln83_fu_848_p2 | icmp_ln83_1_fu_854_p2);

assign select_ln210_fu_1584_p3 = ((approximate[0:0] == 1'b1) ? 5'd3 : 5'd29);

assign temp_rel_eps_fu_1184_p3 = ((and_ln14_18_fu_1178_p2[0:0] == 1'b1) ? 32'd0 : max_18_reg_250);

assign tmp_48_fu_438_p4 = {{bitcast_ln229_1_fu_435_p1[30:23]}};

assign tmp_50_fu_502_p4 = {{bitcast_ln14_fu_499_p1[30:23]}};

assign tmp_52_fu_560_p4 = {{bitcast_ln14_12_fu_557_p1[30:23]}};

assign tmp_53_fu_578_p4 = {{bitcast_ln14_14_fu_574_p1[30:23]}};

assign tmp_55_fu_816_p4 = {{bitcast_ln83_fu_812_p1[30:23]}};

assign tmp_56_fu_834_p4 = {{bitcast_ln83_1_fu_830_p1[30:23]}};

assign tmp_58_fu_916_p4 = {{bitcast_ln237_fu_912_p1[30:23]}};

assign tmp_60_fu_667_p4 = {{bitcast_ln14_15_fu_664_p1[30:23]}};

assign tmp_62_fu_725_p4 = {{bitcast_ln14_16_fu_722_p1[30:23]}};

assign tmp_63_fu_743_p4 = {{bitcast_ln14_18_fu_739_p1[30:23]}};

assign tmp_65_fu_985_p4 = {{bitcast_ln14_19_fu_982_p1[30:23]}};

assign tmp_67_fu_1043_p4 = {{bitcast_ln14_20_fu_1040_p1[30:23]}};

assign tmp_68_fu_1061_p4 = {{bitcast_ln14_21_fu_1057_p1[30:23]}};

assign tmp_70_fu_1146_p4 = {{bitcast_ln14_22_fu_1142_p1[30:23]}};

assign tmp_72_fu_1361_p4 = {{bitcast_ln117_fu_1357_p1[30:23]}};

assign tmp_73_fu_1379_p4 = {{bitcast_ln117_1_fu_1375_p1[30:23]}};

assign tmp_75_fu_1452_p4 = {{bitcast_ln119_fu_1449_p1[30:23]}};

assign tmp_76_fu_1470_p4 = {{bitcast_ln119_1_fu_1466_p1[30:23]}};

assign tmp_78_fu_1543_p4 = {{bitcast_ln241_fu_1539_p1[30:23]}};

assign tmp_80_fu_1212_p4 = {{bitcast_ln14_23_fu_1209_p1[30:23]}};

assign tmp_82_fu_1270_p4 = {{bitcast_ln14_24_fu_1267_p1[30:23]}};

assign tmp_83_fu_1288_p4 = {{bitcast_ln14_25_fu_1284_p1[30:23]}};

assign tmp_fu_397_p4 = {{bitcast_ln229_fu_394_p1[30:23]}};

assign trunc_ln117_1_fu_1389_p1 = bitcast_ln117_1_fu_1375_p1[22:0];

assign trunc_ln117_fu_1371_p1 = bitcast_ln117_fu_1357_p1[22:0];

assign trunc_ln119_1_fu_1480_p1 = bitcast_ln119_1_fu_1466_p1[22:0];

assign trunc_ln119_fu_1462_p1 = bitcast_ln119_fu_1449_p1[22:0];

assign trunc_ln14_10_fu_570_p1 = bitcast_ln14_12_fu_557_p1[22:0];

assign trunc_ln14_11_fu_588_p1 = bitcast_ln14_14_fu_574_p1[22:0];

assign trunc_ln14_12_fu_677_p1 = bitcast_ln14_15_fu_664_p1[22:0];

assign trunc_ln14_13_fu_735_p1 = bitcast_ln14_16_fu_722_p1[22:0];

assign trunc_ln14_14_fu_753_p1 = bitcast_ln14_18_fu_739_p1[22:0];

assign trunc_ln14_15_fu_995_p1 = bitcast_ln14_19_fu_982_p1[22:0];

assign trunc_ln14_16_fu_1053_p1 = bitcast_ln14_20_fu_1040_p1[22:0];

assign trunc_ln14_17_fu_1071_p1 = bitcast_ln14_21_fu_1057_p1[22:0];

assign trunc_ln14_18_fu_1156_p1 = bitcast_ln14_22_fu_1142_p1[22:0];

assign trunc_ln14_19_fu_1222_p1 = bitcast_ln14_23_fu_1209_p1[22:0];

assign trunc_ln14_20_fu_1280_p1 = bitcast_ln14_24_fu_1267_p1[22:0];

assign trunc_ln14_21_fu_1298_p1 = bitcast_ln14_25_fu_1284_p1[22:0];

assign trunc_ln14_fu_512_p1 = bitcast_ln14_fu_499_p1[22:0];

assign trunc_ln229_1_fu_448_p1 = bitcast_ln229_1_fu_435_p1[22:0];

assign trunc_ln229_fu_407_p1 = bitcast_ln229_fu_394_p1[22:0];

assign trunc_ln237_fu_926_p1 = bitcast_ln237_fu_912_p1[22:0];

assign trunc_ln241_fu_1553_p1 = bitcast_ln241_fu_1539_p1[22:0];

assign trunc_ln83_1_fu_844_p1 = bitcast_ln83_1_fu_830_p1[22:0];

assign trunc_ln83_fu_826_p1 = bitcast_ln83_fu_812_p1[22:0];

assign udata_address0 = grp_is_primal_infeasible_fu_317_udata_address0;

assign udata_ce0 = grp_is_primal_infeasible_fu_317_udata_ce0;

assign work_Ax_address0 = zext_ln14_1_fu_653_p1;

assign work_Px_address0 = zext_ln14_3_fu_1198_p1;

assign work_delta_x_address0 = grp_is_dual_infeasible_fu_337_work_delta_x_address0;

assign work_delta_x_ce0 = grp_is_dual_infeasible_fu_337_work_delta_x_ce0;

assign work_delta_y_address0 = grp_is_primal_infeasible_fu_317_work_delta_y_address0;

assign work_delta_y_ce0 = grp_is_primal_infeasible_fu_317_work_delta_y_ce0;

assign work_delta_y_d0 = grp_is_primal_infeasible_fu_317_work_delta_y_d0;

assign work_delta_y_we0 = grp_is_primal_infeasible_fu_317_work_delta_y_we0;

assign work_z_address0 = zext_ln14_fu_488_p1;

assign xor_ln14_2_fu_705_p2 = (bitcast_ln14_15_fu_664_p1 ^ 32'd2147483648);

assign xor_ln14_3_fu_1023_p2 = (bitcast_ln14_19_fu_982_p1 ^ 32'd2147483648);

assign xor_ln14_4_fu_1250_p2 = (bitcast_ln14_23_fu_1209_p1 ^ 32'd2147483648);

assign xor_ln14_fu_540_p2 = (bitcast_ln14_fu_499_p1 ^ 32'd2147483648);

assign zext_ln14_1_fu_653_p1 = i_76_reg_191;

assign zext_ln14_2_fu_971_p1 = i_78_reg_239;

assign zext_ln14_3_fu_1198_p1 = i_82_reg_285;

assign zext_ln14_fu_488_p1 = i_reg_168;

always @ (posedge ap_clk) begin
    eps_rel_reg_1711[1:0] <= 2'b11;
    eps_rel_reg_1711[4:3] <= 2'b01;
    eps_rel_reg_1711[7:7] <= 1'b0;
    eps_rel_reg_1711[9:9] <= 1'b1;
    eps_rel_reg_1711[13:11] <= 3'b010;
    eps_rel_reg_1711[20:16] <= 5'b00011;
    eps_rel_reg_1711[22:22] <= 1'b0;
    eps_rel_reg_1711[24:24] <= 1'b0;
    eps_rel_reg_1711[31:27] <= 5'b00111;
    eps_dual_inf_reg_1736[2:1] <= 2'b11;
    eps_dual_inf_reg_1736[7:7] <= 1'b0;
    eps_dual_inf_reg_1736[9:9] <= 1'b1;
    eps_dual_inf_reg_1736[12:11] <= 2'b10;
    eps_dual_inf_reg_1736[14:14] <= 1'b0;
    eps_dual_inf_reg_1736[16:16] <= 1'b1;
    eps_dual_inf_reg_1736[19:18] <= 2'b00;
    eps_dual_inf_reg_1736[21:21] <= 1'b0;
    eps_dual_inf_reg_1736[24:23] <= 2'b01;
    eps_dual_inf_reg_1736[31:26] <= 6'b001110;
end

endmodule //myFunction_check_termination
