// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myFunction_is_primal_infeasible (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        eps_prim_inf,
        udata_address0,
        udata_ce0,
        udata_q0,
        ldata_address0,
        ldata_ce0,
        ldata_q0,
        work_delta_y_address0,
        work_delta_y_ce0,
        work_delta_y_we0,
        work_delta_y_d0,
        work_delta_y_q0,
        Adata_x_address0,
        Adata_x_ce0,
        Adata_x_q0,
        ap_return,
        grp_fu_346_p_din0,
        grp_fu_346_p_din1,
        grp_fu_346_p_opcode,
        grp_fu_346_p_dout0,
        grp_fu_346_p_ce,
        grp_fu_350_p_din0,
        grp_fu_350_p_din1,
        grp_fu_350_p_dout0,
        grp_fu_350_p_ce,
        grp_fu_1845_p_din0,
        grp_fu_1845_p_din1,
        grp_fu_1845_p_dout0,
        grp_fu_1845_p_ce,
        grp_fu_354_p_din0,
        grp_fu_354_p_din1,
        grp_fu_354_p_opcode,
        grp_fu_354_p_dout0,
        grp_fu_354_p_ce,
        grp_fu_359_p_din0,
        grp_fu_359_p_din1,
        grp_fu_359_p_opcode,
        grp_fu_359_p_dout0,
        grp_fu_359_p_ce
);

parameter    ap_ST_fsm_state1 = 62'd1;
parameter    ap_ST_fsm_state2 = 62'd2;
parameter    ap_ST_fsm_state3 = 62'd4;
parameter    ap_ST_fsm_state4 = 62'd8;
parameter    ap_ST_fsm_state5 = 62'd16;
parameter    ap_ST_fsm_state6 = 62'd32;
parameter    ap_ST_fsm_state7 = 62'd64;
parameter    ap_ST_fsm_state8 = 62'd128;
parameter    ap_ST_fsm_state9 = 62'd256;
parameter    ap_ST_fsm_state10 = 62'd512;
parameter    ap_ST_fsm_state11 = 62'd1024;
parameter    ap_ST_fsm_state12 = 62'd2048;
parameter    ap_ST_fsm_state13 = 62'd4096;
parameter    ap_ST_fsm_state14 = 62'd8192;
parameter    ap_ST_fsm_state15 = 62'd16384;
parameter    ap_ST_fsm_state16 = 62'd32768;
parameter    ap_ST_fsm_state17 = 62'd65536;
parameter    ap_ST_fsm_state18 = 62'd131072;
parameter    ap_ST_fsm_state19 = 62'd262144;
parameter    ap_ST_fsm_state20 = 62'd524288;
parameter    ap_ST_fsm_state21 = 62'd1048576;
parameter    ap_ST_fsm_state22 = 62'd2097152;
parameter    ap_ST_fsm_state23 = 62'd4194304;
parameter    ap_ST_fsm_state24 = 62'd8388608;
parameter    ap_ST_fsm_state25 = 62'd16777216;
parameter    ap_ST_fsm_state26 = 62'd33554432;
parameter    ap_ST_fsm_state27 = 62'd67108864;
parameter    ap_ST_fsm_state28 = 62'd134217728;
parameter    ap_ST_fsm_state29 = 62'd268435456;
parameter    ap_ST_fsm_state30 = 62'd536870912;
parameter    ap_ST_fsm_state31 = 62'd1073741824;
parameter    ap_ST_fsm_state32 = 62'd2147483648;
parameter    ap_ST_fsm_state33 = 62'd4294967296;
parameter    ap_ST_fsm_state34 = 62'd8589934592;
parameter    ap_ST_fsm_state35 = 62'd17179869184;
parameter    ap_ST_fsm_state36 = 62'd34359738368;
parameter    ap_ST_fsm_state37 = 62'd68719476736;
parameter    ap_ST_fsm_state38 = 62'd137438953472;
parameter    ap_ST_fsm_state39 = 62'd274877906944;
parameter    ap_ST_fsm_state40 = 62'd549755813888;
parameter    ap_ST_fsm_state41 = 62'd1099511627776;
parameter    ap_ST_fsm_state42 = 62'd2199023255552;
parameter    ap_ST_fsm_state43 = 62'd4398046511104;
parameter    ap_ST_fsm_state44 = 62'd8796093022208;
parameter    ap_ST_fsm_state45 = 62'd17592186044416;
parameter    ap_ST_fsm_state46 = 62'd35184372088832;
parameter    ap_ST_fsm_state47 = 62'd70368744177664;
parameter    ap_ST_fsm_state48 = 62'd140737488355328;
parameter    ap_ST_fsm_state49 = 62'd281474976710656;
parameter    ap_ST_fsm_state50 = 62'd562949953421312;
parameter    ap_ST_fsm_state51 = 62'd1125899906842624;
parameter    ap_ST_fsm_pp0_stage0 = 62'd2251799813685248;
parameter    ap_ST_fsm_pp0_stage1 = 62'd4503599627370496;
parameter    ap_ST_fsm_pp0_stage2 = 62'd9007199254740992;
parameter    ap_ST_fsm_pp0_stage3 = 62'd18014398509481984;
parameter    ap_ST_fsm_state64 = 62'd36028797018963968;
parameter    ap_ST_fsm_pp1_stage0 = 62'd72057594037927936;
parameter    ap_ST_fsm_pp1_stage1 = 62'd144115188075855872;
parameter    ap_ST_fsm_state72 = 62'd288230376151711744;
parameter    ap_ST_fsm_state73 = 62'd576460752303423488;
parameter    ap_ST_fsm_state74 = 62'd1152921504606846976;
parameter    ap_ST_fsm_state75 = 62'd2305843009213693952;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] eps_prim_inf;
output  [4:0] udata_address0;
output   udata_ce0;
input  [31:0] udata_q0;
output  [4:0] ldata_address0;
output   ldata_ce0;
input  [31:0] ldata_q0;
output  [4:0] work_delta_y_address0;
output   work_delta_y_ce0;
output   work_delta_y_we0;
output  [31:0] work_delta_y_d0;
input  [31:0] work_delta_y_q0;
output  [5:0] Adata_x_address0;
output   Adata_x_ce0;
input  [31:0] Adata_x_q0;
output  [0:0] ap_return;
output  [31:0] grp_fu_346_p_din0;
output  [31:0] grp_fu_346_p_din1;
output  [1:0] grp_fu_346_p_opcode;
input  [31:0] grp_fu_346_p_dout0;
output   grp_fu_346_p_ce;
output  [31:0] grp_fu_350_p_din0;
output  [31:0] grp_fu_350_p_din1;
input  [31:0] grp_fu_350_p_dout0;
output   grp_fu_350_p_ce;
output  [31:0] grp_fu_1845_p_din0;
output  [31:0] grp_fu_1845_p_din1;
input  [31:0] grp_fu_1845_p_dout0;
output   grp_fu_1845_p_ce;
output  [31:0] grp_fu_354_p_din0;
output  [31:0] grp_fu_354_p_din1;
output  [4:0] grp_fu_354_p_opcode;
input  [0:0] grp_fu_354_p_dout0;
output   grp_fu_354_p_ce;
output  [31:0] grp_fu_359_p_din0;
output  [31:0] grp_fu_359_p_din1;
output  [4:0] grp_fu_359_p_opcode;
input  [0:0] grp_fu_359_p_dout0;
output   grp_fu_359_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] udata_address0;
reg udata_ce0;
reg[4:0] ldata_address0;
reg ldata_ce0;
reg[4:0] work_delta_y_address0;
reg work_delta_y_ce0;
reg work_delta_y_we0;
reg[31:0] work_delta_y_d0;
reg Adata_x_ce0;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [61:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [3:0] work_Atdelta_y_address0;
reg    work_Atdelta_y_ce0;
reg    work_Atdelta_y_we0;
reg   [31:0] work_Atdelta_y_d0;
wire   [31:0] work_Atdelta_y_q0;
wire   [3:0] Adata_p_address0;
reg    Adata_p_ce0;
wire   [5:0] Adata_p_q0;
wire   [3:0] Adata_p_address1;
reg    Adata_p_ce1;
wire   [5:0] Adata_p_q1;
wire   [5:0] Adata_i_address0;
reg    Adata_i_ce0;
wire   [4:0] Adata_i_q0;
reg   [63:0] k_1_reg_353;
reg   [31:0] empty_110_reg_365;
reg   [3:0] i_66_reg_376;
reg   [31:0] max_5_reg_387;
reg   [31:0] reg_461;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state26;
reg   [31:0] reg_467;
reg   [31:0] reg_473;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state54_pp0_stage2_iter0;
wire    ap_block_state58_pp0_stage2_iter1;
wire    ap_block_state62_pp0_stage2_iter2;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] icmp_ln106_1_reg_1599;
wire   [31:0] grp_fu_418_p2;
reg   [31:0] reg_480;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state44;
wire   [31:0] grp_fu_413_p2;
reg   [31:0] reg_486;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_state55_pp0_stage3_iter0;
wire    ap_block_state59_pp0_stage3_iter1;
wire    ap_block_state63_pp0_stage3_iter2;
wire    ap_block_pp0_stage3_11001;
reg   [0:0] icmp_ln106_1_reg_1599_pp0_iter2_reg;
reg   [31:0] reg_491;
wire    ap_CS_fsm_state51;
reg   [31:0] reg_491_pp1_iter1_reg;
wire    ap_CS_fsm_pp1_stage1;
wire    ap_block_state66_pp1_stage1_iter0;
wire    ap_block_state68_pp1_stage1_iter1;
wire    ap_block_state70_pp1_stage1_iter2;
wire    ap_block_pp1_stage1_11001;
reg    ap_enable_reg_pp1_iter0;
reg   [0:0] icmp_ln14_1_reg_1638;
wire   [4:0] i_62_fu_497_p2;
reg   [4:0] i_62_reg_1352;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln126_fu_503_p1;
reg   [63:0] zext_ln126_reg_1357;
wire   [0:0] icmp_ln126_fu_509_p2;
wire   [63:0] grp_fu_427_p1;
reg   [63:0] conv_reg_1376;
wire    ap_CS_fsm_state4;
wire   [63:0] grp_fu_431_p1;
reg   [63:0] conv3_reg_1382;
wire   [0:0] icmp_ln127_fu_532_p2;
reg   [0:0] icmp_ln127_reg_1388;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln127_1_fu_538_p2;
reg   [0:0] icmp_ln127_1_reg_1393;
wire   [0:0] notlhs27_fu_561_p2;
reg   [0:0] notlhs27_reg_1398;
wire   [0:0] notrhs28_fu_567_p2;
reg   [0:0] notrhs28_reg_1403;
wire   [0:0] and_ln127_fu_577_p2;
reg   [0:0] and_ln127_reg_1408;
wire    ap_CS_fsm_state6;
wire   [0:0] empty_105_fu_587_p2;
reg   [0:0] empty_105_reg_1412;
reg   [4:0] work_delta_y_addr_2_reg_1416;
wire   [4:0] work_delta_y_addr_gep_fu_145_p3;
reg   [4:0] work_delta_y_addr_reg_1421;
wire   [31:0] select_ln130_fu_635_p3;
reg   [31:0] select_ln130_reg_1426;
wire    ap_CS_fsm_state9;
wire   [31:0] select_ln129_fu_685_p3;
reg   [31:0] select_ln129_reg_1431;
wire    ap_CS_fsm_state13;
wire   [4:0] i_61_fu_693_p2;
reg   [4:0] i_61_reg_1436;
wire    ap_CS_fsm_state15;
wire   [0:0] icmp_ln14_fu_704_p2;
wire   [31:0] abs_v_i_fu_762_p3;
reg   [31:0] abs_v_i_reg_1449;
wire    ap_CS_fsm_state18;
wire   [31:0] max_4_fu_853_p3;
wire    ap_CS_fsm_state20;
wire   [0:0] grp_fu_435_p2;
reg   [0:0] tmp_17_reg_1461;
wire    ap_CS_fsm_state21;
wire   [4:0] i_63_fu_901_p2;
reg   [4:0] i_63_reg_1469;
wire    ap_CS_fsm_state23;
wire   [63:0] zext_ln139_fu_907_p1;
reg   [63:0] zext_ln139_reg_1474;
wire   [0:0] icmp_ln139_fu_912_p2;
wire   [0:0] icmp_ln139_3_fu_918_p2;
reg   [0:0] icmp_ln139_3_reg_1488;
wire    ap_CS_fsm_state25;
wire   [0:0] or_ln139_fu_954_p2;
reg   [0:0] or_ln139_reg_1503;
reg   [0:0] tmp_31_reg_1509;
wire   [0:0] grp_fu_443_p2;
reg   [0:0] tmp_32_reg_1514;
wire   [31:0] select_ln139_fu_964_p3;
wire    ap_CS_fsm_state27;
wire   [31:0] select_ln139_1_fu_977_p3;
wire   [31:0] grp_fu_423_p2;
reg   [31:0] mul24_reg_1529;
wire   [31:0] grp_fu_986_p3;
wire    ap_CS_fsm_state41;
wire   [0:0] icmp_ln140_fu_1011_p2;
reg   [0:0] icmp_ln140_reg_1539;
wire    ap_CS_fsm_state45;
wire   [0:0] icmp_ln140_1_fu_1017_p2;
reg   [0:0] icmp_ln140_1_reg_1544;
wire   [0:0] and_ln140_1_fu_1069_p2;
reg   [0:0] and_ln140_1_reg_1549;
wire    ap_CS_fsm_state46;
wire   [3:0] i_65_fu_1075_p2;
wire    ap_CS_fsm_state48;
wire   [3:0] j_14_fu_1092_p2;
reg   [3:0] j_14_reg_1561;
wire    ap_CS_fsm_state49;
wire   [0:0] icmp_ln105_fu_1098_p2;
reg   [3:0] work_Atdelta_y_addr_1_reg_1580;
wire   [63:0] zext_ln99_fu_1115_p1;
reg   [63:0] zext_ln99_reg_1585;
wire    ap_CS_fsm_state50;
wire   [63:0] Adata_p_load_cast2_fu_1119_p1;
reg   [63:0] Adata_p_load_cast2_reg_1590;
wire   [0:0] icmp_ln106_fu_1123_p2;
reg   [0:0] icmp_ln106_reg_1595;
wire   [0:0] icmp_ln106_1_fu_1129_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state52_pp0_stage0_iter0;
wire    ap_block_state56_pp0_stage0_iter1;
wire    ap_block_state60_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln106_1_reg_1599_pp0_iter1_reg;
reg   [31:0] Adata_x_load_reg_1613;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state53_pp0_stage1_iter0;
wire    ap_block_state57_pp0_stage1_iter1;
wire    ap_block_state61_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
wire   [63:0] k_2_fu_1139_p2;
reg   [63:0] k_2_reg_1623;
reg   [31:0] mul16_i_reg_1628;
reg    ap_enable_reg_pp0_iter1;
wire   [3:0] i_67_fu_1145_p2;
reg   [3:0] i_67_reg_1633;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state65_pp1_stage0_iter0;
wire    ap_block_state67_pp1_stage0_iter1;
wire    ap_block_state69_pp1_stage0_iter2;
wire    ap_block_state71_pp1_stage0_iter3;
wire    ap_block_pp1_stage0_11001;
wire   [0:0] icmp_ln14_1_fu_1151_p2;
reg   [0:0] icmp_ln14_1_reg_1638_pp1_iter1_reg;
reg   [0:0] icmp_ln14_1_reg_1638_pp1_iter2_reg;
reg   [0:0] tmp_36_reg_1647;
reg    ap_enable_reg_pp1_iter1;
wire   [31:0] bitcast_ln14_7_fu_1162_p1;
reg   [31:0] bitcast_ln14_7_reg_1652;
wire   [0:0] icmp_ln14_13_fu_1180_p2;
reg   [0:0] icmp_ln14_13_reg_1657;
wire   [0:0] icmp_ln14_14_fu_1186_p2;
reg   [0:0] icmp_ln14_14_reg_1662;
wire   [31:0] abs_v_i_1_fu_1210_p3;
reg   [31:0] abs_v_i_1_reg_1667;
wire   [0:0] icmp_ln14_17_fu_1237_p2;
reg   [0:0] icmp_ln14_17_reg_1674;
wire   [0:0] icmp_ln14_18_fu_1243_p2;
reg   [0:0] icmp_ln14_18_reg_1679;
wire   [31:0] max_7_fu_1300_p3;
reg    ap_enable_reg_pp1_iter3;
wire   [0:0] icmp_ln143_fu_1325_p2;
reg   [0:0] icmp_ln143_reg_1689;
wire    ap_CS_fsm_state72;
wire   [0:0] icmp_ln143_1_fu_1331_p2;
reg   [0:0] icmp_ln143_1_reg_1694;
wire   [0:0] and_ln143_fu_1341_p2;
reg   [0:0] and_ln143_reg_1699;
wire    ap_CS_fsm_state73;
wire    ap_block_pp0_stage3_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_condition_pp0_exit_iter1_state58;
wire    ap_block_pp1_stage1_subdone;
reg    ap_condition_pp1_flush_enable;
reg    ap_enable_reg_pp1_iter2;
reg    ap_condition_pp1_exit_iter2_state70;
reg   [4:0] i_03_reg_274;
wire    ap_CS_fsm_state10;
reg   [31:0] max_reg_285;
reg   [4:0] i_reg_297;
reg   [31:0] ineq_lhs_reg_308;
wire    ap_CS_fsm_state22;
wire   [0:0] and_ln138_fu_896_p2;
reg   [4:0] i_11_reg_320;
reg   [3:0] i_64_reg_331;
wire   [0:0] icmp_ln101_fu_1086_p2;
wire    ap_CS_fsm_state47;
reg   [3:0] j_reg_342;
wire    ap_CS_fsm_state64;
reg   [63:0] ap_phi_mux_k_1_phi_fu_356_p4;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_empty_110_phi_fu_369_p4;
wire    ap_block_pp0_stage3;
reg   [3:0] ap_phi_mux_i_66_phi_fu_380_p4;
wire    ap_block_pp1_stage0;
reg   [0:0] retval_0_reg_399;
wire    ap_CS_fsm_state74;
wire   [63:0] zext_ln14_fu_699_p1;
wire   [63:0] zext_ln101_fu_1081_p1;
wire   [63:0] zext_ln105_fu_1104_p1;
wire   [63:0] j_14_cast_fu_1110_p1;
wire   [63:0] zext_ln99_1_fu_1134_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] i_66_cast_fu_1157_p1;
wire    ap_CS_fsm_state14;
reg   [31:0] grp_fu_413_p0;
reg   [31:0] grp_fu_413_p1;
wire    ap_CS_fsm_state31;
reg   [31:0] grp_fu_418_p0;
reg   [31:0] grp_fu_418_p1;
wire   [31:0] grp_fu_423_p0;
wire   [31:0] grp_fu_423_p1;
reg   [31:0] grp_fu_435_p0;
reg   [31:0] grp_fu_435_p1;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state19;
wire    ap_block_pp1_stage1;
wire   [31:0] grp_fu_443_p0;
wire   [31:0] grp_fu_443_p1;
wire   [63:0] bitcast_ln127_fu_515_p1;
wire   [10:0] tmp_fu_518_p4;
wire   [51:0] trunc_ln127_fu_528_p1;
wire   [63:0] conv3_to_int_fu_544_p1;
wire   [10:0] tmp_14_fu_547_p4;
wire   [51:0] empty_103_fu_557_p1;
wire   [0:0] or_ln127_fu_573_p2;
wire   [0:0] grp_fu_451_p2;
wire   [0:0] empty_104_fu_583_p2;
wire   [0:0] grp_fu_456_p2;
wire   [31:0] bitcast_ln130_fu_593_p1;
wire   [7:0] tmp_25_fu_597_p4;
wire   [22:0] trunc_ln130_fu_607_p1;
wire   [0:0] icmp_ln130_1_fu_617_p2;
wire   [0:0] icmp_ln130_fu_611_p2;
wire   [0:0] or_ln130_fu_623_p2;
wire   [0:0] and_ln130_fu_629_p2;
wire   [31:0] bitcast_ln129_fu_643_p1;
wire   [7:0] tmp_23_fu_647_p4;
wire   [22:0] trunc_ln129_fu_657_p1;
wire   [0:0] icmp_ln129_1_fu_667_p2;
wire   [0:0] icmp_ln129_fu_661_p2;
wire   [0:0] or_ln129_fu_673_p2;
wire   [0:0] and_ln129_fu_679_p2;
wire   [31:0] bitcast_ln14_fu_710_p1;
wire   [7:0] tmp_18_fu_714_p4;
wire   [22:0] trunc_ln14_fu_724_p1;
wire   [0:0] icmp_ln14_8_fu_734_p2;
wire   [0:0] icmp_ln14_7_fu_728_p2;
wire   [0:0] or_ln14_fu_740_p2;
wire   [31:0] xor_ln14_fu_752_p2;
wire   [0:0] and_ln14_fu_746_p2;
wire   [31:0] bitcast_ln14_2_fu_758_p1;
wire   [31:0] bitcast_ln14_5_fu_770_p1;
wire   [31:0] bitcast_ln14_6_fu_787_p1;
wire   [7:0] tmp_20_fu_773_p4;
wire   [22:0] trunc_ln14_3_fu_783_p1;
wire   [0:0] icmp_ln14_10_fu_811_p2;
wire   [0:0] icmp_ln14_9_fu_805_p2;
wire   [7:0] tmp_21_fu_791_p4;
wire   [22:0] trunc_ln14_4_fu_801_p1;
wire   [0:0] icmp_ln14_12_fu_829_p2;
wire   [0:0] icmp_ln14_11_fu_823_p2;
wire   [0:0] or_ln14_3_fu_817_p2;
wire   [0:0] or_ln14_4_fu_835_p2;
wire   [0:0] and_ln14_3_fu_841_p2;
wire   [0:0] and_ln14_4_fu_847_p2;
wire   [31:0] bitcast_ln138_fu_860_p1;
wire   [7:0] tmp_16_fu_864_p4;
wire   [22:0] trunc_ln138_fu_874_p1;
wire   [0:0] icmp_ln138_1_fu_884_p2;
wire   [0:0] icmp_ln138_fu_878_p2;
wire   [0:0] or_ln138_fu_890_p2;
wire   [31:0] bitcast_ln139_fu_924_p1;
wire   [7:0] tmp_30_fu_928_p4;
wire   [22:0] trunc_ln139_fu_938_p1;
wire   [0:0] icmp_ln139_2_fu_948_p2;
wire   [0:0] icmp_ln139_1_fu_942_p2;
wire   [0:0] and_ln139_fu_960_p2;
wire   [0:0] and_ln139_1_fu_973_p2;
wire    ap_CS_fsm_state36;
wire   [31:0] bitcast_ln140_fu_993_p1;
wire   [7:0] tmp_27_fu_997_p4;
wire   [22:0] trunc_ln140_fu_1007_p1;
wire   [31:0] bitcast_ln140_1_fu_1023_p1;
wire   [7:0] tmp_28_fu_1027_p4;
wire   [22:0] trunc_ln140_1_fu_1037_p1;
wire   [0:0] icmp_ln140_3_fu_1051_p2;
wire   [0:0] icmp_ln140_2_fu_1045_p2;
wire   [0:0] or_ln140_fu_1041_p2;
wire   [0:0] or_ln140_1_fu_1057_p2;
wire   [0:0] and_ln140_fu_1063_p2;
wire   [7:0] tmp_35_fu_1166_p4;
wire   [22:0] trunc_ln14_5_fu_1176_p1;
wire   [0:0] or_ln14_5_fu_1192_p2;
wire   [31:0] xor_ln14_1_fu_1201_p2;
wire   [0:0] and_ln14_5_fu_1196_p2;
wire   [31:0] bitcast_ln14_4_fu_1206_p1;
wire   [31:0] bitcast_ln14_9_fu_1219_p1;
wire   [7:0] tmp_38_fu_1223_p4;
wire   [22:0] trunc_ln14_7_fu_1233_p1;
wire   [31:0] bitcast_ln14_8_fu_1249_p1;
wire   [7:0] tmp_37_fu_1252_p4;
wire   [22:0] trunc_ln14_6_fu_1262_p1;
wire   [0:0] icmp_ln14_16_fu_1272_p2;
wire   [0:0] icmp_ln14_15_fu_1266_p2;
wire   [0:0] or_ln14_6_fu_1278_p2;
wire   [0:0] or_ln14_7_fu_1284_p2;
wire   [0:0] and_ln14_6_fu_1288_p2;
wire   [0:0] and_ln14_7_fu_1294_p2;
wire   [31:0] bitcast_ln143_fu_1307_p1;
wire   [7:0] tmp_33_fu_1311_p4;
wire   [22:0] trunc_ln143_fu_1321_p1;
wire   [0:0] or_ln143_fu_1337_p2;
wire    grp_fu_413_ce;
wire    grp_fu_418_ce;
wire    grp_fu_423_ce;
wire    grp_fu_435_ce;
reg   [4:0] grp_fu_435_opcode;
wire    ap_block_pp1_stage0_00001;
wire    ap_block_pp1_stage1_00001;
wire    grp_fu_443_ce;
wire   [4:0] grp_fu_443_opcode;
reg    grp_fu_986_in_valid;
reg   [0:0] ap_return_preg;
wire    ap_CS_fsm_state75;
reg   [61:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp1_stage0_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    ap_block_pp0_stage3_00001;
wire   [31:0] grp_fu_986_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 62'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_return_preg = 1'd0;
end

myFunction_is_primal_infeasible_work_Atdelta_y #(
    .DataWidth( 32 ),
    .AddressRange( 15 ),
    .AddressWidth( 4 ))
work_Atdelta_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(work_Atdelta_y_address0),
    .ce0(work_Atdelta_y_ce0),
    .we0(work_Atdelta_y_we0),
    .d0(work_Atdelta_y_d0),
    .q0(work_Atdelta_y_q0)
);

myFunction_is_primal_infeasible_Adata_p #(
    .DataWidth( 6 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
Adata_p_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Adata_p_address0),
    .ce0(Adata_p_ce0),
    .q0(Adata_p_q0),
    .address1(Adata_p_address1),
    .ce1(Adata_p_ce1),
    .q1(Adata_p_q1)
);

myFunction_is_primal_infeasible_Adata_i #(
    .DataWidth( 5 ),
    .AddressRange( 43 ),
    .AddressWidth( 6 ))
Adata_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Adata_i_address0),
    .ce0(Adata_i_ce0),
    .q0(Adata_i_q0)
);

myFunction_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U78(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(udata_q0),
    .ce(1'b1),
    .dout(grp_fu_427_p1)
);

myFunction_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U79(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ldata_q0),
    .ce(1'b1),
    .dout(grp_fu_431_p1)
);

myFunction_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv_reg_1376),
    .din1(64'd4995809153305444090),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_451_p2)
);

myFunction_dcmp_64ns_64ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 1 ))
dcmp_64ns_64ns_1_2_no_dsp_1_U83(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv3_reg_1382),
    .din1(64'd14219181190160219898),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_456_p2)
);

myFunction_facc_32ns_32ns_1ns_32_6_no_dsp_1 #(
    .DWIDTH( 32 ))
facc_32ns_32ns_1ns_32_6_no_dsp_1_U84(
    .clk(ap_clk),
    .reset(ap_rst),
    .ce(1'b1),
    .in_data(reg_486),
    .in_last(icmp_ln139_3_reg_1488),
    .in_valid(grp_fu_986_in_valid),
    .out_data(grp_fu_986_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state51)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            if (((1'b1 == ap_condition_pp0_exit_iter1_state58) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_enable_reg_pp0_iter1 <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter1_state58) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state51)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp1_flush_enable)) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((icmp_ln105_fu_1098_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state49))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if ((((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b1 == ap_condition_pp1_exit_iter2_state70) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone)) | ((icmp_ln105_fu_1098_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state49)))) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter2_state70) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter1;
        end else if (((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end else if (((icmp_ln105_fu_1098_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state49))) begin
            ap_enable_reg_pp1_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state75)) begin
            ap_return_preg <= retval_0_reg_399;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln106_1_reg_1599_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001))) begin
        empty_110_reg_365 <= grp_fu_346_p_dout0;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        empty_110_reg_365 <= work_Atdelta_y_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        i_03_reg_274 <= i_62_reg_1352;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_03_reg_274 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln138_fu_896_p2) & (1'b1 == ap_CS_fsm_state22))) begin
        i_11_reg_320 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        i_11_reg_320 <= i_63_reg_1469;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln140_1_reg_1549) & (1'b1 == ap_CS_fsm_state47))) begin
        i_64_reg_331 <= 4'd0;
    end else if (((icmp_ln101_fu_1086_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state48))) begin
        i_64_reg_331 <= i_65_fu_1075_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln105_fu_1098_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state49))) begin
        i_66_reg_376 <= 4'd0;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln14_1_reg_1638 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        i_66_reg_376 <= i_67_reg_1633;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln126_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_297 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        i_reg_297 <= i_61_reg_1436;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln138_fu_896_p2) & (1'b1 == ap_CS_fsm_state22))) begin
        ineq_lhs_reg_308 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        ineq_lhs_reg_308 <= grp_fu_986_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln101_fu_1086_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state48))) begin
        j_reg_342 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state64)) begin
        j_reg_342 <= j_14_reg_1561;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln106_1_reg_1599 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_1_reg_353 <= k_2_reg_1623;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        k_1_reg_353 <= zext_ln99_reg_1585;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln105_fu_1098_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state49))) begin
        max_5_reg_387 <= 32'd0;
    end else if (((ap_enable_reg_pp1_iter3 == 1'b1) & (icmp_ln14_1_reg_1638_pp1_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        max_5_reg_387 <= max_7_fu_1300_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln126_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        max_reg_285 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        max_reg_285 <= max_4_fu_853_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'd0 == and_ln140_1_reg_1549) & (1'b1 == ap_CS_fsm_state47)) | ((1'd0 == and_ln138_fu_896_p2) & (1'b1 == ap_CS_fsm_state22)))) begin
        retval_0_reg_399 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state74)) begin
        retval_0_reg_399 <= and_ln143_reg_1699;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        Adata_p_load_cast2_reg_1590[5 : 0] <= Adata_p_load_cast2_fu_1119_p1[5 : 0];
        icmp_ln106_reg_1595 <= icmp_ln106_fu_1123_p2;
        zext_ln99_reg_1585[5 : 0] <= zext_ln99_fu_1115_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln106_1_reg_1599 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        Adata_x_load_reg_1613 <= Adata_x_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_1_reg_1638_pp1_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        abs_v_i_1_reg_1667 <= abs_v_i_1_fu_1210_p3;
        icmp_ln14_17_reg_1674 <= icmp_ln14_17_fu_1237_p2;
        icmp_ln14_18_reg_1679 <= icmp_ln14_18_fu_1243_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        abs_v_i_reg_1449 <= abs_v_i_fu_762_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        and_ln127_reg_1408 <= and_ln127_fu_577_p2;
        empty_105_reg_1412 <= empty_105_fu_587_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        and_ln140_1_reg_1549 <= and_ln140_1_fu_1069_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        and_ln143_reg_1699 <= and_ln143_fu_1341_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_1_reg_1638_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        bitcast_ln14_7_reg_1652 <= bitcast_ln14_7_fu_1162_p1;
        icmp_ln14_13_reg_1657 <= icmp_ln14_13_fu_1180_p2;
        icmp_ln14_14_reg_1662 <= icmp_ln14_14_fu_1186_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv3_reg_1382 <= grp_fu_431_p1;
        conv_reg_1376 <= grp_fu_427_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        i_61_reg_1436 <= i_61_fu_693_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_62_reg_1352 <= i_62_fu_497_p2;
        zext_ln126_reg_1357[4 : 0] <= zext_ln126_fu_503_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        i_63_reg_1469 <= i_63_fu_901_p2;
        zext_ln139_reg_1474[4 : 0] <= zext_ln139_fu_907_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        i_67_reg_1633 <= i_67_fu_1145_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln106_1_reg_1599 <= icmp_ln106_1_fu_1129_p2;
        icmp_ln106_1_reg_1599_pp0_iter1_reg <= icmp_ln106_1_reg_1599;
        icmp_ln106_1_reg_1599_pp0_iter2_reg <= icmp_ln106_1_reg_1599_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln127_1_reg_1393 <= icmp_ln127_1_fu_538_p2;
        icmp_ln127_reg_1388 <= icmp_ln127_fu_532_p2;
        notlhs27_reg_1398 <= notlhs27_fu_561_p2;
        notrhs28_reg_1403 <= notrhs28_fu_567_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln139_fu_912_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state23))) begin
        icmp_ln139_3_reg_1488 <= icmp_ln139_3_fu_918_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        icmp_ln140_1_reg_1544 <= icmp_ln140_1_fu_1017_p2;
        icmp_ln140_reg_1539 <= icmp_ln140_fu_1011_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state72)) begin
        icmp_ln143_1_reg_1694 <= icmp_ln143_1_fu_1331_p2;
        icmp_ln143_reg_1689 <= icmp_ln143_fu_1325_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln14_1_reg_1638 <= icmp_ln14_1_fu_1151_p2;
        icmp_ln14_1_reg_1638_pp1_iter1_reg <= icmp_ln14_1_reg_1638;
        icmp_ln14_1_reg_1638_pp1_iter2_reg <= icmp_ln14_1_reg_1638_pp1_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        j_14_reg_1561 <= j_14_fu_1092_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln106_1_reg_1599 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        k_2_reg_1623 <= k_2_fu_1139_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln106_1_reg_1599_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        mul16_i_reg_1628 <= grp_fu_350_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        mul24_reg_1529 <= grp_fu_1845_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        or_ln139_reg_1503 <= or_ln139_fu_954_p2;
        tmp_31_reg_1509 <= grp_fu_354_p_dout0;
        tmp_32_reg_1514 <= grp_fu_359_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_461 <= udata_q0;
        reg_467 <= ldata_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln106_1_reg_1599 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
        reg_473 <= work_delta_y_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state30))) begin
        reg_480 <= grp_fu_350_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) | ((icmp_ln106_1_reg_1599_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001)))) begin
        reg_486 <= grp_fu_346_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state51) | ((icmp_ln14_1_reg_1638 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)))) begin
        reg_491 <= work_Atdelta_y_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        reg_491_pp1_iter1_reg <= reg_491;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        select_ln129_reg_1431 <= select_ln129_fu_685_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        select_ln130_reg_1426 <= select_ln130_fu_635_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        tmp_17_reg_1461 <= grp_fu_354_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln14_1_reg_1638_pp1_iter1_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001))) begin
        tmp_36_reg_1647 <= grp_fu_354_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln105_fu_1098_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state49))) begin
        work_Atdelta_y_addr_1_reg_1580 <= zext_ln105_fu_1104_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((empty_105_fu_587_p2 == 1'd1) & (1'd0 == and_ln127_fu_577_p2) & (1'b1 == ap_CS_fsm_state6))) begin
        work_delta_y_addr_2_reg_1416 <= zext_ln126_reg_1357;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln127_fu_577_p2) & (1'b1 == ap_CS_fsm_state6))) begin
        work_delta_y_addr_reg_1421 <= zext_ln126_reg_1357;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        Adata_i_ce0 = 1'b1;
    end else begin
        Adata_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        Adata_p_ce0 = 1'b1;
    end else begin
        Adata_p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        Adata_p_ce1 = 1'b1;
    end else begin
        Adata_p_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        Adata_x_ce0 = 1'b1;
    end else begin
        Adata_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state58 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state58 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln106_1_reg_1599 == 1'd1) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_condition_pp1_exit_iter2_state70 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter2_state70 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_1_reg_1638 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
        ap_condition_pp1_flush_enable = 1'b1;
    end else begin
        ap_condition_pp1_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state75) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln106_1_reg_1599_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
        ap_phi_mux_empty_110_phi_fu_369_p4 = grp_fu_346_p_dout0;
    end else begin
        ap_phi_mux_empty_110_phi_fu_369_p4 = empty_110_reg_365;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln14_1_reg_1638 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        ap_phi_mux_i_66_phi_fu_380_p4 = i_67_reg_1633;
    end else begin
        ap_phi_mux_i_66_phi_fu_380_p4 = i_66_reg_376;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln106_1_reg_1599 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_k_1_phi_fu_356_p4 = k_2_reg_1623;
    end else begin
        ap_phi_mux_k_1_phi_fu_356_p4 = k_1_reg_353;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        ap_return = retval_0_reg_399;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_413_p0 = ap_phi_mux_empty_110_phi_fu_369_p4;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_413_p0 = reg_480;
    end else begin
        grp_fu_413_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_413_p1 = mul16_i_reg_1628;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_413_p1 = mul24_reg_1529;
    end else begin
        grp_fu_413_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_418_p0 = Adata_x_load_reg_1613;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_418_p0 = reg_461;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_418_p0 = max_reg_285;
    end else begin
        grp_fu_418_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_418_p1 = reg_473;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        grp_fu_418_p1 = select_ln139_fu_964_p3;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_418_p1 = eps_prim_inf;
    end else begin
        grp_fu_418_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state45) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (icmp_ln14_1_reg_1638 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_00001)))) begin
        grp_fu_435_opcode = 5'd4;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state25) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln14_1_reg_1638_pp1_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_00001)) | ((icmp_ln14_fu_704_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)))) begin
        grp_fu_435_opcode = 5'd2;
    end else begin
        grp_fu_435_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state72)) begin
        grp_fu_435_p0 = max_5_reg_387;
    end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1))) begin
        grp_fu_435_p0 = abs_v_i_1_fu_1210_p3;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        grp_fu_435_p0 = reg_491;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_435_p0 = ineq_lhs_reg_308;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_435_p0 = abs_v_i_reg_1449;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_435_p0 = max_reg_285;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_fu_435_p0 = reg_473;
    end else begin
        grp_fu_435_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1))) begin
        grp_fu_435_p1 = max_5_reg_387;
    end else if (((1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state45))) begin
        grp_fu_435_p1 = reg_480;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_435_p1 = max_reg_285;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_435_p1 = 32'd228737632;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state25) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0)))) begin
        grp_fu_435_p1 = 32'd0;
    end else begin
        grp_fu_435_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_986_in_valid = 1'b1;
    end else begin
        grp_fu_986_in_valid = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ldata_address0 = zext_ln139_reg_1474;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ldata_address0 = zext_ln126_fu_503_p1;
    end else begin
        ldata_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state2))) begin
        ldata_ce0 = 1'b1;
    end else begin
        ldata_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        udata_address0 = zext_ln139_reg_1474;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        udata_address0 = zext_ln126_fu_503_p1;
    end else begin
        udata_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state2))) begin
        udata_ce0 = 1'b1;
    end else begin
        udata_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        work_Atdelta_y_address0 = i_66_cast_fu_1157_p1;
    end else if (((1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state50))) begin
        work_Atdelta_y_address0 = work_Atdelta_y_addr_1_reg_1580;
    end else if ((1'b1 == ap_CS_fsm_state48)) begin
        work_Atdelta_y_address0 = zext_ln101_fu_1081_p1;
    end else begin
        work_Atdelta_y_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state48) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        work_Atdelta_y_ce0 = 1'b1;
    end else begin
        work_Atdelta_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        work_Atdelta_y_d0 = empty_110_reg_365;
    end else if ((1'b1 == ap_CS_fsm_state48)) begin
        work_Atdelta_y_d0 = 32'd0;
    end else begin
        work_Atdelta_y_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln106_reg_1595 == 1'd1) & (1'b1 == ap_CS_fsm_state64)) | ((icmp_ln101_fu_1086_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state48)))) begin
        work_Atdelta_y_we0 = 1'b1;
    end else begin
        work_Atdelta_y_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        work_delta_y_address0 = zext_ln99_1_fu_1134_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        work_delta_y_address0 = zext_ln139_fu_907_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        work_delta_y_address0 = zext_ln14_fu_699_p1;
    end else if (((1'b1 == ap_CS_fsm_state14) | ((1'd1 == and_ln127_reg_1408) & (empty_105_reg_1412 == 1'd0) & (1'b1 == ap_CS_fsm_state10)))) begin
        work_delta_y_address0 = work_delta_y_addr_reg_1421;
    end else if (((empty_105_reg_1412 == 1'd1) & (1'd0 == and_ln127_reg_1408) & (1'b1 == ap_CS_fsm_state10))) begin
        work_delta_y_address0 = work_delta_y_addr_2_reg_1416;
    end else if (((1'd1 == and_ln127_fu_577_p2) & (empty_105_fu_587_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        work_delta_y_address0 = work_delta_y_addr_gep_fu_145_p3;
    end else if (((empty_105_fu_587_p2 == 1'd1) & (1'd0 == and_ln127_fu_577_p2) & (1'b1 == ap_CS_fsm_state6))) begin
        work_delta_y_address0 = zext_ln126_reg_1357;
    end else begin
        work_delta_y_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state15) | ((1'd1 == and_ln127_reg_1408) & (empty_105_reg_1412 == 1'd0) & (1'b1 == ap_CS_fsm_state10)) | ((empty_105_reg_1412 == 1'd1) & (1'd0 == and_ln127_reg_1408) & (1'b1 == ap_CS_fsm_state10)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'd1 == and_ln127_fu_577_p2) & (empty_105_fu_587_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((empty_105_fu_587_p2 == 1'd1) & (1'd0 == and_ln127_fu_577_p2) & (1'b1 == ap_CS_fsm_state6)))) begin
        work_delta_y_ce0 = 1'b1;
    end else begin
        work_delta_y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        work_delta_y_d0 = 32'd0;
    end else if (((1'd1 == and_ln127_reg_1408) & (empty_105_reg_1412 == 1'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        work_delta_y_d0 = select_ln129_reg_1431;
    end else if (((empty_105_reg_1412 == 1'd1) & (1'd0 == and_ln127_reg_1408) & (1'b1 == ap_CS_fsm_state10))) begin
        work_delta_y_d0 = select_ln130_reg_1426;
    end else begin
        work_delta_y_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((1'd1 == and_ln127_reg_1408) & (empty_105_reg_1412 == 1'd0) & (1'b1 == ap_CS_fsm_state10)) | ((empty_105_reg_1412 == 1'd1) & (1'd0 == and_ln127_reg_1408) & (1'b1 == ap_CS_fsm_state10)))) begin
        work_delta_y_we0 = 1'b1;
    end else begin
        work_delta_y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln126_fu_509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'd1 == and_ln127_fu_577_p2) & (empty_105_fu_587_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((1'd1 == and_ln127_fu_577_p2) & (empty_105_fu_587_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if (((empty_105_fu_587_p2 == 1'd0) & (1'd0 == and_ln127_fu_577_p2) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln14_fu_704_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((1'd1 == and_ln138_fu_896_p2) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((icmp_ln139_fu_912_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            if (((1'd1 == and_ln140_1_reg_1549) & (1'b1 == ap_CS_fsm_state47))) begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        ap_ST_fsm_state48 : begin
            if (((icmp_ln101_fu_1086_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state48))) begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end
        end
        ap_ST_fsm_state49 : begin
            if (((icmp_ln105_fu_1098_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state49))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end
        end
        ap_ST_fsm_state50 : begin
            if (((icmp_ln106_fu_1123_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0)) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((~((1'b1 == ap_condition_pp0_exit_iter1_state58) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone)) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_condition_pp0_exit_iter1_state58) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((~((ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone)) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state72;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Adata_i_address0 = ap_phi_mux_k_1_phi_fu_356_p4;

assign Adata_p_address0 = j_14_cast_fu_1110_p1;

assign Adata_p_address1 = zext_ln105_fu_1104_p1;

assign Adata_p_load_cast2_fu_1119_p1 = Adata_p_q0;

assign Adata_x_address0 = ap_phi_mux_k_1_phi_fu_356_p4;

assign abs_v_i_1_fu_1210_p3 = ((and_ln14_5_fu_1196_p2[0:0] == 1'b1) ? bitcast_ln14_4_fu_1206_p1 : reg_491_pp1_iter1_reg);

assign abs_v_i_fu_762_p3 = ((and_ln14_fu_746_p2[0:0] == 1'b1) ? bitcast_ln14_2_fu_758_p1 : reg_473);

assign and_ln127_fu_577_p2 = (or_ln127_fu_573_p2 & grp_fu_451_p2);

assign and_ln129_fu_679_p2 = (or_ln129_fu_673_p2 & grp_fu_354_p_dout0);

assign and_ln130_fu_629_p2 = (or_ln130_fu_623_p2 & grp_fu_354_p_dout0);

assign and_ln138_fu_896_p2 = (tmp_17_reg_1461 & or_ln138_fu_890_p2);

assign and_ln139_1_fu_973_p2 = (tmp_32_reg_1514 & or_ln139_reg_1503);

assign and_ln139_fu_960_p2 = (tmp_31_reg_1509 & or_ln139_reg_1503);

assign and_ln140_1_fu_1069_p2 = (grp_fu_354_p_dout0 & and_ln140_fu_1063_p2);

assign and_ln140_fu_1063_p2 = (or_ln140_fu_1041_p2 & or_ln140_1_fu_1057_p2);

assign and_ln143_fu_1341_p2 = (or_ln143_fu_1337_p2 & grp_fu_354_p_dout0);

assign and_ln14_3_fu_841_p2 = (or_ln14_4_fu_835_p2 & or_ln14_3_fu_817_p2);

assign and_ln14_4_fu_847_p2 = (grp_fu_354_p_dout0 & and_ln14_3_fu_841_p2);

assign and_ln14_5_fu_1196_p2 = (tmp_36_reg_1647 & or_ln14_5_fu_1192_p2);

assign and_ln14_6_fu_1288_p2 = (or_ln14_7_fu_1284_p2 & or_ln14_6_fu_1278_p2);

assign and_ln14_7_fu_1294_p2 = (grp_fu_354_p_dout0 & and_ln14_6_fu_1288_p2);

assign and_ln14_fu_746_p2 = (or_ln14_fu_740_p2 & grp_fu_354_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state61_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state62_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state63_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state65_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state66_pp1_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state67_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state68_pp1_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state69_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state70_pp1_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state71_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign bitcast_ln127_fu_515_p1 = conv_reg_1376;

assign bitcast_ln129_fu_643_p1 = reg_473;

assign bitcast_ln130_fu_593_p1 = reg_473;

assign bitcast_ln138_fu_860_p1 = max_reg_285;

assign bitcast_ln139_fu_924_p1 = reg_473;

assign bitcast_ln140_1_fu_1023_p1 = reg_480;

assign bitcast_ln140_fu_993_p1 = ineq_lhs_reg_308;

assign bitcast_ln143_fu_1307_p1 = max_5_reg_387;

assign bitcast_ln14_2_fu_758_p1 = xor_ln14_fu_752_p2;

assign bitcast_ln14_4_fu_1206_p1 = xor_ln14_1_fu_1201_p2;

assign bitcast_ln14_5_fu_770_p1 = abs_v_i_reg_1449;

assign bitcast_ln14_6_fu_787_p1 = max_reg_285;

assign bitcast_ln14_7_fu_1162_p1 = reg_491_pp1_iter1_reg;

assign bitcast_ln14_8_fu_1249_p1 = abs_v_i_1_reg_1667;

assign bitcast_ln14_9_fu_1219_p1 = max_5_reg_387;

assign bitcast_ln14_fu_710_p1 = reg_473;

assign conv3_to_int_fu_544_p1 = conv3_reg_1382;

assign empty_103_fu_557_p1 = conv3_to_int_fu_544_p1[51:0];

assign empty_104_fu_583_p2 = (notrhs28_reg_1403 | notlhs27_reg_1398);

assign empty_105_fu_587_p2 = (grp_fu_456_p2 & empty_104_fu_583_p2);

assign grp_fu_1845_p_ce = 1'b1;

assign grp_fu_1845_p_din0 = reg_467;

assign grp_fu_1845_p_din1 = select_ln139_1_fu_977_p3;

assign grp_fu_346_p_ce = 1'b1;

assign grp_fu_346_p_din0 = grp_fu_413_p0;

assign grp_fu_346_p_din1 = grp_fu_413_p1;

assign grp_fu_346_p_opcode = 2'd0;

assign grp_fu_350_p_ce = 1'b1;

assign grp_fu_350_p_din0 = grp_fu_418_p0;

assign grp_fu_350_p_din1 = grp_fu_418_p1;

assign grp_fu_354_p_ce = 1'b1;

assign grp_fu_354_p_din0 = grp_fu_435_p0;

assign grp_fu_354_p_din1 = grp_fu_435_p1;

assign grp_fu_354_p_opcode = grp_fu_435_opcode;

assign grp_fu_359_p_ce = 1'b1;

assign grp_fu_359_p_din0 = reg_473;

assign grp_fu_359_p_din1 = 32'd0;

assign grp_fu_359_p_opcode = 5'd4;

assign grp_fu_413_ce = 1'b1;

assign grp_fu_413_p2 = grp_fu_346_p_dout0;

assign grp_fu_418_ce = 1'b1;

assign grp_fu_418_p2 = grp_fu_350_p_dout0;

assign grp_fu_423_ce = 1'b1;

assign grp_fu_423_p0 = reg_467;

assign grp_fu_423_p1 = select_ln139_1_fu_977_p3;

assign grp_fu_423_p2 = grp_fu_1845_p_dout0;

assign grp_fu_435_ce = 1'b1;

assign grp_fu_435_p2 = grp_fu_354_p_dout0;

assign grp_fu_443_ce = 1'b1;

assign grp_fu_443_opcode = 5'd4;

assign grp_fu_443_p0 = reg_473;

assign grp_fu_443_p1 = 32'd0;

assign grp_fu_443_p2 = grp_fu_359_p_dout0;

assign i_61_fu_693_p2 = (i_reg_297 + 5'd1);

assign i_62_fu_497_p2 = (i_03_reg_274 + 5'd1);

assign i_63_fu_901_p2 = (i_11_reg_320 + 5'd1);

assign i_65_fu_1075_p2 = (i_64_reg_331 + 4'd1);

assign i_66_cast_fu_1157_p1 = ap_phi_mux_i_66_phi_fu_380_p4;

assign i_67_fu_1145_p2 = (ap_phi_mux_i_66_phi_fu_380_p4 + 4'd1);

assign icmp_ln101_fu_1086_p2 = ((i_64_reg_331 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln105_fu_1098_p2 = ((j_reg_342 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln106_1_fu_1129_p2 = ((ap_phi_mux_k_1_phi_fu_356_p4 == Adata_p_load_cast2_reg_1590) ? 1'b1 : 1'b0);

assign icmp_ln106_fu_1123_p2 = ((Adata_p_q1 < Adata_p_q0) ? 1'b1 : 1'b0);

assign icmp_ln126_fu_509_p2 = ((i_03_reg_274 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln127_1_fu_538_p2 = ((trunc_ln127_fu_528_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln127_fu_532_p2 = ((tmp_fu_518_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln129_1_fu_667_p2 = ((trunc_ln129_fu_657_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln129_fu_661_p2 = ((tmp_23_fu_647_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln130_1_fu_617_p2 = ((trunc_ln130_fu_607_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln130_fu_611_p2 = ((tmp_25_fu_597_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln138_1_fu_884_p2 = ((trunc_ln138_fu_874_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln138_fu_878_p2 = ((tmp_16_fu_864_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln139_1_fu_942_p2 = ((tmp_30_fu_928_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln139_2_fu_948_p2 = ((trunc_ln139_fu_938_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln139_3_fu_918_p2 = ((i_63_fu_901_p2 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln139_fu_912_p2 = ((i_11_reg_320 == 5'd19) ? 1'b1 : 1'b0);

assign icmp_ln140_1_fu_1017_p2 = ((trunc_ln140_fu_1007_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln140_2_fu_1045_p2 = ((tmp_28_fu_1027_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln140_3_fu_1051_p2 = ((trunc_ln140_1_fu_1037_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln140_fu_1011_p2 = ((tmp_27_fu_997_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln143_1_fu_1331_p2 = ((trunc_ln143_fu_1321_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln143_fu_1325_p2 = ((tmp_33_fu_1311_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_10_fu_811_p2 = ((trunc_ln14_3_fu_783_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_11_fu_823_p2 = ((tmp_21_fu_791_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_12_fu_829_p2 = ((trunc_ln14_4_fu_801_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_13_fu_1180_p2 = ((tmp_35_fu_1166_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_14_fu_1186_p2 = ((trunc_ln14_5_fu_1176_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_15_fu_1266_p2 = ((tmp_37_fu_1252_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_16_fu_1272_p2 = ((trunc_ln14_6_fu_1262_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_17_fu_1237_p2 = ((tmp_38_fu_1223_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_18_fu_1243_p2 = ((trunc_ln14_7_fu_1233_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_1_fu_1151_p2 = ((ap_phi_mux_i_66_phi_fu_380_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln14_7_fu_728_p2 = ((tmp_18_fu_714_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_8_fu_734_p2 = ((trunc_ln14_fu_724_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_9_fu_805_p2 = ((tmp_20_fu_773_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_704_p2 = ((i_reg_297 == 5'd19) ? 1'b1 : 1'b0);

assign j_14_cast_fu_1110_p1 = j_14_fu_1092_p2;

assign j_14_fu_1092_p2 = (j_reg_342 + 4'd1);

assign k_2_fu_1139_p2 = (k_1_reg_353 + 64'd1);

assign max_4_fu_853_p3 = ((and_ln14_4_fu_847_p2[0:0] == 1'b1) ? abs_v_i_reg_1449 : max_reg_285);

assign max_7_fu_1300_p3 = ((and_ln14_7_fu_1294_p2[0:0] == 1'b1) ? abs_v_i_1_reg_1667 : max_5_reg_387);

assign notlhs27_fu_561_p2 = ((tmp_14_fu_547_p4 != 11'd2047) ? 1'b1 : 1'b0);

assign notrhs28_fu_567_p2 = ((empty_103_fu_557_p1 == 52'd0) ? 1'b1 : 1'b0);

assign or_ln127_fu_573_p2 = (icmp_ln127_reg_1388 | icmp_ln127_1_reg_1393);

assign or_ln129_fu_673_p2 = (icmp_ln129_fu_661_p2 | icmp_ln129_1_fu_667_p2);

assign or_ln130_fu_623_p2 = (icmp_ln130_fu_611_p2 | icmp_ln130_1_fu_617_p2);

assign or_ln138_fu_890_p2 = (icmp_ln138_fu_878_p2 | icmp_ln138_1_fu_884_p2);

assign or_ln139_fu_954_p2 = (icmp_ln139_2_fu_948_p2 | icmp_ln139_1_fu_942_p2);

assign or_ln140_1_fu_1057_p2 = (icmp_ln140_3_fu_1051_p2 | icmp_ln140_2_fu_1045_p2);

assign or_ln140_fu_1041_p2 = (icmp_ln140_reg_1539 | icmp_ln140_1_reg_1544);

assign or_ln143_fu_1337_p2 = (icmp_ln143_reg_1689 | icmp_ln143_1_reg_1694);

assign or_ln14_3_fu_817_p2 = (icmp_ln14_9_fu_805_p2 | icmp_ln14_10_fu_811_p2);

assign or_ln14_4_fu_835_p2 = (icmp_ln14_12_fu_829_p2 | icmp_ln14_11_fu_823_p2);

assign or_ln14_5_fu_1192_p2 = (icmp_ln14_14_reg_1662 | icmp_ln14_13_reg_1657);

assign or_ln14_6_fu_1278_p2 = (icmp_ln14_16_fu_1272_p2 | icmp_ln14_15_fu_1266_p2);

assign or_ln14_7_fu_1284_p2 = (icmp_ln14_18_reg_1679 | icmp_ln14_17_reg_1674);

assign or_ln14_fu_740_p2 = (icmp_ln14_8_fu_734_p2 | icmp_ln14_7_fu_728_p2);

assign select_ln129_fu_685_p3 = ((and_ln129_fu_679_p2[0:0] == 1'b1) ? reg_473 : 32'd0);

assign select_ln130_fu_635_p3 = ((and_ln130_fu_629_p2[0:0] == 1'b1) ? reg_473 : 32'd0);

assign select_ln139_1_fu_977_p3 = ((and_ln139_1_fu_973_p2[0:0] == 1'b1) ? reg_473 : 32'd0);

assign select_ln139_fu_964_p3 = ((and_ln139_fu_960_p2[0:0] == 1'b1) ? reg_473 : 32'd0);

assign tmp_14_fu_547_p4 = {{conv3_to_int_fu_544_p1[62:52]}};

assign tmp_16_fu_864_p4 = {{bitcast_ln138_fu_860_p1[30:23]}};

assign tmp_18_fu_714_p4 = {{bitcast_ln14_fu_710_p1[30:23]}};

assign tmp_20_fu_773_p4 = {{bitcast_ln14_5_fu_770_p1[30:23]}};

assign tmp_21_fu_791_p4 = {{bitcast_ln14_6_fu_787_p1[30:23]}};

assign tmp_23_fu_647_p4 = {{bitcast_ln129_fu_643_p1[30:23]}};

assign tmp_25_fu_597_p4 = {{bitcast_ln130_fu_593_p1[30:23]}};

assign tmp_27_fu_997_p4 = {{bitcast_ln140_fu_993_p1[30:23]}};

assign tmp_28_fu_1027_p4 = {{bitcast_ln140_1_fu_1023_p1[30:23]}};

assign tmp_30_fu_928_p4 = {{bitcast_ln139_fu_924_p1[30:23]}};

assign tmp_33_fu_1311_p4 = {{bitcast_ln143_fu_1307_p1[30:23]}};

assign tmp_35_fu_1166_p4 = {{bitcast_ln14_7_fu_1162_p1[30:23]}};

assign tmp_37_fu_1252_p4 = {{bitcast_ln14_8_fu_1249_p1[30:23]}};

assign tmp_38_fu_1223_p4 = {{bitcast_ln14_9_fu_1219_p1[30:23]}};

assign tmp_fu_518_p4 = {{bitcast_ln127_fu_515_p1[62:52]}};

assign trunc_ln127_fu_528_p1 = bitcast_ln127_fu_515_p1[51:0];

assign trunc_ln129_fu_657_p1 = bitcast_ln129_fu_643_p1[22:0];

assign trunc_ln130_fu_607_p1 = bitcast_ln130_fu_593_p1[22:0];

assign trunc_ln138_fu_874_p1 = bitcast_ln138_fu_860_p1[22:0];

assign trunc_ln139_fu_938_p1 = bitcast_ln139_fu_924_p1[22:0];

assign trunc_ln140_1_fu_1037_p1 = bitcast_ln140_1_fu_1023_p1[22:0];

assign trunc_ln140_fu_1007_p1 = bitcast_ln140_fu_993_p1[22:0];

assign trunc_ln143_fu_1321_p1 = bitcast_ln143_fu_1307_p1[22:0];

assign trunc_ln14_3_fu_783_p1 = bitcast_ln14_5_fu_770_p1[22:0];

assign trunc_ln14_4_fu_801_p1 = bitcast_ln14_6_fu_787_p1[22:0];

assign trunc_ln14_5_fu_1176_p1 = bitcast_ln14_7_fu_1162_p1[22:0];

assign trunc_ln14_6_fu_1262_p1 = bitcast_ln14_8_fu_1249_p1[22:0];

assign trunc_ln14_7_fu_1233_p1 = bitcast_ln14_9_fu_1219_p1[22:0];

assign trunc_ln14_fu_724_p1 = bitcast_ln14_fu_710_p1[22:0];

assign work_delta_y_addr_gep_fu_145_p3 = zext_ln126_reg_1357;

assign xor_ln14_1_fu_1201_p2 = (bitcast_ln14_7_reg_1652 ^ 32'd2147483648);

assign xor_ln14_fu_752_p2 = (bitcast_ln14_fu_710_p1 ^ 32'd2147483648);

assign zext_ln101_fu_1081_p1 = i_64_reg_331;

assign zext_ln105_fu_1104_p1 = j_reg_342;

assign zext_ln126_fu_503_p1 = i_03_reg_274;

assign zext_ln139_fu_907_p1 = i_11_reg_320;

assign zext_ln14_fu_699_p1 = i_reg_297;

assign zext_ln99_1_fu_1134_p1 = Adata_i_q0;

assign zext_ln99_fu_1115_p1 = Adata_p_q1;

always @ (posedge ap_clk) begin
    zext_ln126_reg_1357[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln139_reg_1474[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    zext_ln99_reg_1585[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    Adata_p_load_cast2_reg_1590[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //myFunction_is_primal_infeasible
