// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myFunction_compute_dua_res (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        qdata_address0,
        qdata_ce0,
        qdata_q0,
        work_x_prev_address0,
        work_x_prev_ce0,
        work_x_prev_we0,
        work_x_prev_d0,
        work_Px_address0,
        work_Px_ce0,
        work_Px_we0,
        work_Px_d0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] qdata_address0;
output   qdata_ce0;
input  [31:0] qdata_q0;
output  [3:0] work_x_prev_address0;
output   work_x_prev_ce0;
output   work_x_prev_we0;
output  [31:0] work_x_prev_d0;
output  [3:0] work_Px_address0;
output   work_Px_ce0;
output   work_Px_we0;
output  [31:0] work_Px_d0;

reg ap_done;
reg ap_idle;
reg qdata_ce0;
reg work_x_prev_ce0;
reg work_x_prev_we0;
reg work_Px_ce0;
reg work_Px_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] i_72_fu_91_p2;
reg   [3:0] i_72_reg_119;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln43_fu_97_p1;
reg   [63:0] zext_ln43_reg_124;
wire   [0:0] icmp_ln43_fu_102_p2;
wire   [3:0] i_74_fu_113_p2;
wire    ap_CS_fsm_state4;
reg   [3:0] i_reg_69;
wire    ap_CS_fsm_state3;
reg   [3:0] i_73_reg_80;
wire   [63:0] zext_ln85_fu_108_p1;
reg   [3:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln43_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_73_reg_80 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i_73_reg_80 <= i_74_fu_113_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_69 <= i_72_reg_119;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_69 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_72_reg_119 <= i_72_fu_91_p2;
        zext_ln43_reg_124[3 : 0] <= zext_ln43_fu_97_p1[3 : 0];
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        qdata_ce0 = 1'b1;
    end else begin
        qdata_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        work_Px_ce0 = 1'b1;
    end else begin
        work_Px_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        work_Px_we0 = 1'b1;
    end else begin
        work_Px_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        work_x_prev_ce0 = 1'b1;
    end else begin
        work_x_prev_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        work_x_prev_we0 = 1'b1;
    end else begin
        work_x_prev_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln43_fu_102_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_ready = 1'b0;

assign i_72_fu_91_p2 = (i_reg_69 + 4'd1);

assign i_74_fu_113_p2 = (i_73_reg_80 + 4'd1);

assign icmp_ln43_fu_102_p2 = ((i_reg_69 == 4'd15) ? 1'b1 : 1'b0);

assign qdata_address0 = zext_ln43_fu_97_p1;

assign work_Px_address0 = zext_ln85_fu_108_p1;

assign work_Px_d0 = 32'd0;

assign work_x_prev_address0 = zext_ln43_reg_124;

assign work_x_prev_d0 = qdata_q0;

assign zext_ln43_fu_97_p1 = i_reg_69;

assign zext_ln85_fu_108_p1 = i_73_reg_80;

always @ (posedge ap_clk) begin
    zext_ln43_reg_124[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //myFunction_compute_dua_res
