// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myFunction_solve_linsys_qdldl (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        work_xz_tilde_address0,
        work_xz_tilde_ce0,
        work_xz_tilde_we0,
        work_xz_tilde_d0,
        work_xz_tilde_q0,
        work_xz_tilde_address1,
        work_xz_tilde_ce1,
        work_xz_tilde_q1,
        linsys_solver_L_p_address0,
        linsys_solver_L_p_ce0,
        linsys_solver_L_p_q0,
        linsys_solver_L_p_address1,
        linsys_solver_L_p_ce1,
        linsys_solver_L_p_q1,
        linsys_solver_L_x_address0,
        linsys_solver_L_x_ce0,
        linsys_solver_L_x_q0,
        linsys_solver_L_i_address0,
        linsys_solver_L_i_ce0,
        linsys_solver_L_i_q0,
        linsys_solver_Dinv_address0,
        linsys_solver_Dinv_ce0,
        linsys_solver_Dinv_q0,
        linsys_solver_rho_inv_vec_address0,
        linsys_solver_rho_inv_vec_ce0,
        linsys_solver_rho_inv_vec_q0,
        grp_fu_1008_p_din0,
        grp_fu_1008_p_din1,
        grp_fu_1008_p_opcode,
        grp_fu_1008_p_dout0,
        grp_fu_1008_p_ce,
        grp_fu_1020_p_din0,
        grp_fu_1020_p_din1,
        grp_fu_1020_p_dout0,
        grp_fu_1020_p_ce
);

parameter    ap_ST_fsm_state1 = 28'd1;
parameter    ap_ST_fsm_state2 = 28'd2;
parameter    ap_ST_fsm_state3 = 28'd4;
parameter    ap_ST_fsm_state4 = 28'd8;
parameter    ap_ST_fsm_state5 = 28'd16;
parameter    ap_ST_fsm_state6 = 28'd32;
parameter    ap_ST_fsm_pp0_stage0 = 28'd64;
parameter    ap_ST_fsm_pp0_stage1 = 28'd128;
parameter    ap_ST_fsm_pp0_stage2 = 28'd256;
parameter    ap_ST_fsm_pp0_stage3 = 28'd512;
parameter    ap_ST_fsm_pp0_stage4 = 28'd1024;
parameter    ap_ST_fsm_pp0_stage5 = 28'd2048;
parameter    ap_ST_fsm_state19 = 28'd4096;
parameter    ap_ST_fsm_pp1_stage0 = 28'd8192;
parameter    ap_ST_fsm_state27 = 28'd16384;
parameter    ap_ST_fsm_state28 = 28'd32768;
parameter    ap_ST_fsm_state29 = 28'd65536;
parameter    ap_ST_fsm_pp2_stage0 = 28'd131072;
parameter    ap_ST_fsm_pp2_stage1 = 28'd262144;
parameter    ap_ST_fsm_pp2_stage2 = 28'd524288;
parameter    ap_ST_fsm_pp2_stage3 = 28'd1048576;
parameter    ap_ST_fsm_state42 = 28'd2097152;
parameter    ap_ST_fsm_pp3_stage0 = 28'd4194304;
parameter    ap_ST_fsm_state45 = 28'd8388608;
parameter    ap_ST_fsm_pp4_stage0 = 28'd16777216;
parameter    ap_ST_fsm_state48 = 28'd33554432;
parameter    ap_ST_fsm_pp5_stage0 = 28'd67108864;
parameter    ap_ST_fsm_state61 = 28'd134217728;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] work_xz_tilde_address0;
output   work_xz_tilde_ce0;
output   work_xz_tilde_we0;
output  [31:0] work_xz_tilde_d0;
input  [31:0] work_xz_tilde_q0;
output  [5:0] work_xz_tilde_address1;
output   work_xz_tilde_ce1;
input  [31:0] work_xz_tilde_q1;
output  [5:0] linsys_solver_L_p_address0;
output   linsys_solver_L_p_ce0;
input  [5:0] linsys_solver_L_p_q0;
output  [5:0] linsys_solver_L_p_address1;
output   linsys_solver_L_p_ce1;
input  [5:0] linsys_solver_L_p_q1;
output  [5:0] linsys_solver_L_x_address0;
output   linsys_solver_L_x_ce0;
input  [31:0] linsys_solver_L_x_q0;
output  [5:0] linsys_solver_L_i_address0;
output   linsys_solver_L_i_ce0;
input  [5:0] linsys_solver_L_i_q0;
output  [5:0] linsys_solver_Dinv_address0;
output   linsys_solver_Dinv_ce0;
input  [31:0] linsys_solver_Dinv_q0;
output  [4:0] linsys_solver_rho_inv_vec_address0;
output   linsys_solver_rho_inv_vec_ce0;
input  [31:0] linsys_solver_rho_inv_vec_q0;
output  [31:0] grp_fu_1008_p_din0;
output  [31:0] grp_fu_1008_p_din1;
output  [1:0] grp_fu_1008_p_opcode;
input  [31:0] grp_fu_1008_p_dout0;
output   grp_fu_1008_p_ce;
output  [31:0] grp_fu_1020_p_din0;
output  [31:0] grp_fu_1020_p_din1;
input  [31:0] grp_fu_1020_p_dout0;
output   grp_fu_1020_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] work_xz_tilde_address0;
reg work_xz_tilde_ce0;
reg work_xz_tilde_we0;
reg[31:0] work_xz_tilde_d0;
reg work_xz_tilde_ce1;
reg[5:0] linsys_solver_L_p_address0;
reg linsys_solver_L_p_ce0;
reg[5:0] linsys_solver_L_p_address1;
reg linsys_solver_L_p_ce1;
reg[5:0] linsys_solver_L_x_address0;
reg linsys_solver_L_x_ce0;
reg[5:0] linsys_solver_L_i_address0;
reg linsys_solver_L_i_ce0;
reg linsys_solver_Dinv_ce0;
reg linsys_solver_rho_inv_vec_ce0;

(* fsm_encoding = "none" *) reg   [27:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [5:0] linsys_solver_P_address0;
reg    linsys_solver_P_ce0;
wire   [5:0] linsys_solver_P_q0;
reg   [5:0] linsys_solver_bp_address0;
reg    linsys_solver_bp_ce0;
reg    linsys_solver_bp_we0;
reg   [31:0] linsys_solver_bp_d0;
wire   [31:0] linsys_solver_bp_q0;
reg   [5:0] linsys_solver_bp_address1;
reg    linsys_solver_bp_ce1;
reg    linsys_solver_bp_we1;
wire   [31:0] linsys_solver_bp_q1;
reg   [5:0] linsys_solver_sol_address0;
reg    linsys_solver_sol_ce0;
reg    linsys_solver_sol_we0;
wire   [31:0] linsys_solver_sol_q0;
reg   [63:0] j_3_reg_391;
reg   [5:0] i_1_reg_403;
reg   [63:0] j_6_reg_426;
reg   [31:0] val_2_reg_438;
reg   [5:0] j_8_reg_449;
reg   [3:0] j_04_reg_460;
reg   [4:0] j_11_reg_471;
reg   [31:0] reg_491;
wire    ap_CS_fsm_state6;
wire    ap_block_state20_pp1_stage0_iter0;
wire    ap_block_state21_pp1_stage0_iter1;
wire    ap_block_state22_pp1_stage0_iter2;
wire    ap_block_state23_pp1_stage0_iter3;
wire    ap_block_state24_pp1_stage0_iter4;
wire    ap_block_state25_pp1_stage0_iter5;
wire    ap_block_state26_pp1_stage0_iter6;
wire    ap_block_pp1_stage0_11001;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
reg   [0:0] icmp_ln279_reg_891;
wire    ap_CS_fsm_state29;
reg   [31:0] reg_499;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state8_pp0_stage1_iter0;
wire    ap_block_state14_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
reg   [0:0] icmp_ln245_reg_852;
wire    ap_CS_fsm_pp2_stage1;
wire    ap_block_state31_pp2_stage1_iter0;
wire    ap_block_state35_pp2_stage1_iter1;
wire    ap_block_state39_pp2_stage1_iter2;
wire    ap_block_pp2_stage1_11001;
reg    ap_enable_reg_pp2_iter0;
reg   [0:0] icmp_ln261_reg_940;
reg   [31:0] reg_504;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state9_pp0_stage2_iter0;
wire    ap_block_state15_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp2_stage2;
wire    ap_block_state32_pp2_stage2_iter0;
wire    ap_block_state36_pp2_stage2_iter1;
wire    ap_block_state40_pp2_stage2_iter2;
wire    ap_block_pp2_stage2_11001;
wire   [31:0] grp_fu_487_p2;
reg   [31:0] reg_510;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state12_pp0_stage5_iter0;
wire    ap_block_state18_pp0_stage5_iter1;
wire    ap_block_pp0_stage5_11001;
wire    ap_block_state49_pp5_stage0_iter0;
wire    ap_block_state50_pp5_stage0_iter1;
wire    ap_block_state51_pp5_stage0_iter2;
wire    ap_block_state52_pp5_stage0_iter3;
wire    ap_block_state53_pp5_stage0_iter4;
wire    ap_block_state54_pp5_stage0_iter5;
wire    ap_block_state55_pp5_stage0_iter6;
wire    ap_block_state56_pp5_stage0_iter7;
wire    ap_block_state57_pp5_stage0_iter8;
wire    ap_block_state58_pp5_stage0_iter9;
wire    ap_block_state59_pp5_stage0_iter10;
wire    ap_block_state60_pp5_stage0_iter11;
wire    ap_block_pp5_stage0_11001;
reg    ap_enable_reg_pp1_iter5;
reg   [0:0] icmp_ln279_reg_891_pp1_iter4_reg;
reg    ap_enable_reg_pp2_iter1;
reg   [0:0] icmp_ln261_reg_940_pp2_iter1_reg;
reg    ap_enable_reg_pp5_iter5;
reg   [0:0] icmp_ln41_reg_1012;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter4_reg;
wire   [31:0] grp_fu_482_p2;
reg   [31:0] reg_516;
wire    ap_CS_fsm_pp0_stage4;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state11_pp0_stage4_iter0;
wire    ap_block_state17_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_11001;
reg   [0:0] icmp_ln245_reg_852_pp0_iter1_reg;
wire    ap_CS_fsm_pp2_stage3;
reg    ap_enable_reg_pp2_iter2;
wire    ap_block_state33_pp2_stage3_iter0;
wire    ap_block_state37_pp2_stage3_iter1;
wire    ap_block_state41_pp2_stage3_iter2;
wire    ap_block_pp2_stage3_11001;
reg   [0:0] icmp_ln261_reg_940_pp2_iter2_reg;
reg    ap_enable_reg_pp5_iter10;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter9_reg;
wire   [5:0] j_1_fu_523_p2;
reg   [5:0] j_1_reg_795;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln12_fu_529_p1;
reg   [63:0] zext_ln12_reg_800;
wire   [0:0] icmp_ln12_fu_534_p2;
wire    ap_CS_fsm_state3;
wire   [5:0] i_3_fu_545_p2;
reg   [5:0] i_3_reg_818;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln243_fu_551_p2;
wire   [63:0] zext_ln242_fu_578_p1;
wire   [63:0] zext_ln245_fu_582_p1;
reg   [63:0] zext_ln245_reg_847;
wire   [0:0] icmp_ln245_fu_586_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state7_pp0_stage0_iter0;
wire    ap_block_state13_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] linsys_solver_bp_addr_3_reg_866;
reg   [5:0] linsys_solver_bp_addr_3_reg_866_pp0_iter1_reg;
wire   [0:0] addr_cmp_fu_599_p2;
reg   [0:0] addr_cmp_reg_871;
wire   [31:0] reuse_select_fu_613_p3;
reg   [31:0] reuse_select_reg_876;
wire   [63:0] j_4_fu_620_p2;
reg   [63:0] j_4_reg_881;
wire   [5:0] i_2_fu_631_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] icmp_ln279_fu_637_p2;
reg   [0:0] icmp_ln279_reg_891_pp1_iter1_reg;
reg   [0:0] icmp_ln279_reg_891_pp1_iter2_reg;
reg   [0:0] icmp_ln279_reg_891_pp1_iter3_reg;
reg   [0:0] icmp_ln279_reg_891_pp1_iter5_reg;
reg   [5:0] linsys_solver_bp_addr_2_reg_900;
reg   [5:0] linsys_solver_bp_addr_2_reg_900_pp1_iter1_reg;
reg   [5:0] linsys_solver_bp_addr_2_reg_900_pp1_iter2_reg;
reg   [5:0] linsys_solver_bp_addr_2_reg_900_pp1_iter3_reg;
reg   [5:0] linsys_solver_bp_addr_2_reg_900_pp1_iter4_reg;
reg   [5:0] linsys_solver_bp_addr_2_reg_900_pp1_iter5_reg;
reg   [31:0] linsys_solver_Dinv_load_reg_906;
wire   [0:0] tmp_fu_649_p3;
wire    ap_CS_fsm_state28;
reg   [5:0] linsys_solver_bp_addr_4_reg_915;
wire   [63:0] zext_ln258_fu_678_p1;
wire   [63:0] zext_ln261_fu_682_p1;
reg   [63:0] zext_ln261_reg_935;
wire   [0:0] icmp_ln261_fu_686_p2;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state30_pp2_stage0_iter0;
wire    ap_block_state34_pp2_stage0_iter1;
wire    ap_block_state38_pp2_stage0_iter2;
wire    ap_block_pp2_stage0_11001;
wire   [63:0] j_13_fu_696_p2;
reg   [63:0] j_13_reg_959;
wire   [6:0] i_5_fu_702_p2;
wire    ap_CS_fsm_state42;
wire   [5:0] j_9_fu_708_p2;
wire    ap_CS_fsm_pp3_stage0;
reg    ap_enable_reg_pp3_iter0;
wire    ap_block_state43_pp3_stage0_iter0;
wire    ap_block_state44_pp3_stage0_iter1;
wire    ap_block_pp3_stage0_11001;
wire   [0:0] icmp_ln17_fu_714_p2;
reg   [0:0] icmp_ln17_reg_974;
wire   [3:0] j_14_fu_731_p2;
wire    ap_CS_fsm_pp4_stage0;
reg    ap_enable_reg_pp4_iter0;
wire    ap_block_state46_pp4_stage0_iter0;
wire    ap_block_state47_pp4_stage0_iter1;
wire    ap_block_pp4_stage0_11001;
wire   [0:0] icmp_ln37_fu_737_p2;
reg   [0:0] icmp_ln37_reg_993;
wire   [63:0] j_04_cast_fu_743_p1;
reg   [63:0] j_04_cast_reg_997;
wire   [4:0] j_15_fu_748_p2;
wire    ap_CS_fsm_pp5_stage0;
reg    ap_enable_reg_pp5_iter0;
wire   [0:0] icmp_ln41_fu_754_p2;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter1_reg;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter2_reg;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter3_reg;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter5_reg;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter6_reg;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter7_reg;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter8_reg;
reg   [0:0] icmp_ln41_reg_1012_pp5_iter10_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter1_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter2_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter3_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter4_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter5_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter6_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter7_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter8_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter9_reg;
reg   [5:0] work_xz_tilde_addr_2_reg_1026_pp5_iter10_reg;
reg   [31:0] linsys_solver_rho_inv_vec_load_reg_1032;
reg   [31:0] linsys_solver_sol_load_1_reg_1037;
reg    ap_enable_reg_pp5_iter1;
reg   [31:0] work_xz_tilde_load_1_reg_1042;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state7;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state20;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter6;
wire    ap_block_pp2_stage3_subdone;
reg    ap_condition_pp2_flush_enable;
reg    ap_condition_pp2_exit_iter1_state36;
wire    ap_block_pp3_stage0_subdone;
reg    ap_condition_pp3_exit_iter0_state43;
reg    ap_enable_reg_pp3_iter1;
wire    ap_CS_fsm_state45;
wire    ap_block_pp4_stage0_subdone;
reg    ap_condition_pp4_exit_iter0_state46;
reg    ap_enable_reg_pp4_iter1;
wire    ap_CS_fsm_state48;
wire    ap_block_pp5_stage0_subdone;
reg    ap_condition_pp5_exit_iter0_state49;
reg    ap_enable_reg_pp5_iter2;
reg    ap_enable_reg_pp5_iter3;
reg    ap_enable_reg_pp5_iter4;
reg    ap_enable_reg_pp5_iter6;
reg    ap_enable_reg_pp5_iter7;
reg    ap_enable_reg_pp5_iter8;
reg    ap_enable_reg_pp5_iter9;
reg    ap_enable_reg_pp5_iter11;
reg   [5:0] j_reg_369;
wire    ap_CS_fsm_state4;
reg   [5:0] i_reg_380;
wire    ap_CS_fsm_state19;
reg   [63:0] ap_phi_mux_j_3_phi_fu_394_p4;
wire    ap_block_pp0_stage0;
reg   [6:0] i_4_reg_414;
wire    ap_CS_fsm_state27;
reg   [63:0] ap_phi_mux_j_6_phi_fu_429_p4;
wire    ap_block_pp2_stage0;
reg   [31:0] ap_phi_mux_val_2_phi_fu_442_p4;
wire    ap_block_pp2_stage3;
wire   [63:0] zext_ln12_1_fu_540_p1;
wire   [63:0] zext_ln243_fu_557_p1;
wire   [63:0] i_3_cast_fu_563_p1;
wire   [63:0] zext_ln246_fu_591_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] i_1_cast_fu_643_p1;
wire    ap_block_pp1_stage0;
wire   [63:0] zext_ln259_fu_657_p1;
wire   [63:0] add_i7_i_i_cast_fu_673_p1;
wire   [63:0] zext_ln262_fu_691_p1;
wire    ap_block_pp2_stage1;
wire   [63:0] j_8_cast_fu_720_p1;
wire    ap_block_pp3_stage0;
wire   [63:0] zext_ln17_fu_726_p1;
wire    ap_block_pp4_stage0;
wire   [63:0] j_11_cast2_fu_760_p1;
wire    ap_block_pp5_stage0;
wire   [63:0] zext_ln42_fu_775_p1;
reg   [63:0] reuse_addr_reg_fu_102;
reg   [31:0] reuse_reg_fu_106;
reg   [31:0] ap_sig_allocacmp_reuse_reg_load;
wire    ap_block_pp0_stage5;
reg   [31:0] grp_fu_482_p0;
wire   [31:0] grp_fu_482_p1;
reg   [31:0] grp_fu_487_p0;
reg   [31:0] grp_fu_487_p1;
wire    ap_block_pp0_stage2;
wire   [5:0] trunc_ln259_fu_663_p1;
wire   [5:0] add_i7_i_i_fu_667_p2;
wire   [5:0] j_11_cast_fu_765_p1;
wire   [5:0] add_ln42_fu_769_p2;
reg   [1:0] grp_fu_482_opcode;
wire    ap_block_pp5_stage0_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp2_stage3_00001;
wire    grp_fu_482_ce;
wire    grp_fu_487_ce;
wire    ap_CS_fsm_state61;
reg   [27:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_state10_pp0_stage3_iter0;
wire    ap_block_state16_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp2_stage0_subdone;
wire    ap_block_pp2_stage1_subdone;
wire    ap_block_pp2_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_idle_pp3;
wire    ap_enable_pp3;
reg    ap_idle_pp4;
wire    ap_enable_pp4;
reg    ap_idle_pp5;
wire    ap_enable_pp5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 28'd1;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp5_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp5_iter10 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp3_iter0 = 1'b0;
#0 ap_enable_reg_pp4_iter0 = 1'b0;
#0 ap_enable_reg_pp5_iter0 = 1'b0;
#0 ap_enable_reg_pp5_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp3_iter1 = 1'b0;
#0 ap_enable_reg_pp4_iter1 = 1'b0;
#0 ap_enable_reg_pp5_iter2 = 1'b0;
#0 ap_enable_reg_pp5_iter3 = 1'b0;
#0 ap_enable_reg_pp5_iter4 = 1'b0;
#0 ap_enable_reg_pp5_iter6 = 1'b0;
#0 ap_enable_reg_pp5_iter7 = 1'b0;
#0 ap_enable_reg_pp5_iter8 = 1'b0;
#0 ap_enable_reg_pp5_iter9 = 1'b0;
#0 ap_enable_reg_pp5_iter11 = 1'b0;
end

myFunction_solve_linsys_qdldl_linsys_solver_P #(
    .DataWidth( 6 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
linsys_solver_P_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linsys_solver_P_address0),
    .ce0(linsys_solver_P_ce0),
    .q0(linsys_solver_P_q0)
);

myFunction_solve_linsys_qdldl_linsys_solver_bp #(
    .DataWidth( 32 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
linsys_solver_bp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linsys_solver_bp_address0),
    .ce0(linsys_solver_bp_ce0),
    .we0(linsys_solver_bp_we0),
    .d0(linsys_solver_bp_d0),
    .q0(linsys_solver_bp_q0),
    .address1(linsys_solver_bp_address1),
    .ce1(linsys_solver_bp_ce1),
    .we1(linsys_solver_bp_we1),
    .d1(val_2_reg_438),
    .q1(linsys_solver_bp_q1)
);

myFunction_solve_linsys_qdldl_linsys_solver_sol #(
    .DataWidth( 32 ),
    .AddressRange( 34 ),
    .AddressWidth( 6 ))
linsys_solver_sol_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(linsys_solver_sol_address0),
    .ce0(linsys_solver_sol_ce0),
    .we0(linsys_solver_sol_we0),
    .d0(linsys_solver_bp_q1),
    .q0(linsys_solver_sol_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state7) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp1_exit_iter0_state20) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((icmp_ln243_fu_551_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state20)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state20);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end else if (((icmp_ln243_fu_551_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp1_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp2_flush_enable)) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state29)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_subdone))) begin
            if (((ap_enable_reg_pp2_iter0 == 1'b0) & (1'b1 == ap_condition_pp2_exit_iter1_state36))) begin
                ap_enable_reg_pp2_iter1 <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp2_exit_iter1_state36) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_subdone))) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter0;
        end else if (((1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_subdone))) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end else if ((1'b1 == ap_CS_fsm_state29)) begin
            ap_enable_reg_pp2_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp3_exit_iter0_state43) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
            ap_enable_reg_pp3_iter0 <= 1'b0;
        end else if (((tmp_fu_649_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
            ap_enable_reg_pp3_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp3_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp3_exit_iter0_state43) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
            ap_enable_reg_pp3_iter1 <= (1'b1 ^ ap_condition_pp3_exit_iter0_state43);
        end else if ((1'b0 == ap_block_pp3_stage0_subdone)) begin
            ap_enable_reg_pp3_iter1 <= ap_enable_reg_pp3_iter0;
        end else if (((tmp_fu_649_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
            ap_enable_reg_pp3_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp4_exit_iter0_state46) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
            ap_enable_reg_pp4_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state45)) begin
            ap_enable_reg_pp4_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp4_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp4_exit_iter0_state46) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
            ap_enable_reg_pp4_iter1 <= (1'b1 ^ ap_condition_pp4_exit_iter0_state46);
        end else if ((1'b0 == ap_block_pp4_stage0_subdone)) begin
            ap_enable_reg_pp4_iter1 <= ap_enable_reg_pp4_iter0;
        end else if ((1'b1 == ap_CS_fsm_state45)) begin
            ap_enable_reg_pp4_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp5_exit_iter0_state49) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0_subdone))) begin
            ap_enable_reg_pp5_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state48)) begin
            ap_enable_reg_pp5_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp5_exit_iter0_state49)) begin
                ap_enable_reg_pp5_iter1 <= (1'b1 ^ ap_condition_pp5_exit_iter0_state49);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp5_iter1 <= ap_enable_reg_pp5_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter10 <= ap_enable_reg_pp5_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter11 <= ap_enable_reg_pp5_iter10;
        end else if ((1'b1 == ap_CS_fsm_state48)) begin
            ap_enable_reg_pp5_iter11 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter2 <= ap_enable_reg_pp5_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter3 <= ap_enable_reg_pp5_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter4 <= ap_enable_reg_pp5_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter5 <= ap_enable_reg_pp5_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter6 <= ap_enable_reg_pp5_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter7 <= ap_enable_reg_pp5_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter8 <= ap_enable_reg_pp5_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp5_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp5_stage0_subdone)) begin
            ap_enable_reg_pp5_iter9 <= ap_enable_reg_pp5_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln243_fu_551_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_1_reg_403 <= 6'd0;
    end else if (((icmp_ln279_fu_637_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        i_1_reg_403 <= i_2_fu_631_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        i_4_reg_414 <= 7'd33;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        i_4_reg_414 <= i_5_fu_702_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln12_fu_534_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_reg_380 <= 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        i_reg_380 <= i_3_reg_818;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        j_04_reg_460 <= 4'd0;
    end else if (((icmp_ln37_fu_737_p2 == 1'd0) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        j_04_reg_460 <= j_14_fu_731_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        j_11_reg_471 <= 5'd0;
    end else if (((icmp_ln41_fu_754_p2 == 1'd0) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0_11001))) begin
        j_11_reg_471 <= j_15_fu_748_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln245_reg_852 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_3_reg_391 <= j_4_reg_881;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        j_3_reg_391 <= zext_ln242_fu_578_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln261_reg_940 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        j_6_reg_426 <= j_13_reg_959;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        j_6_reg_426 <= zext_ln258_fu_678_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_649_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        j_8_reg_449 <= 6'd0;
    end else if (((icmp_ln17_fu_714_p2 == 1'd0) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        j_8_reg_449 <= j_9_fu_708_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        j_reg_369 <= j_1_reg_795;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_reg_369 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state29) | ((1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln279_reg_891 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        reg_491 <= linsys_solver_bp_q1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_491 <= linsys_solver_bp_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln261_reg_940 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2) & (1'b0 == ap_block_pp2_stage2_11001))) begin
        reg_504 <= linsys_solver_bp_q1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln245_reg_852 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        reg_504 <= linsys_solver_bp_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln243_fu_551_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        reuse_addr_reg_fu_102 <= 64'd18446744073709551615;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln245_reg_852 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        reuse_addr_reg_fu_102 <= zext_ln246_fu_591_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln243_fu_551_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        reuse_reg_fu_106 <= 32'd0;
    end else if (((icmp_ln245_reg_852_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        reuse_reg_fu_106 <= reg_516;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln261_reg_940_pp2_iter2_reg == 1'd1) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_11001))) begin
        val_2_reg_438 <= grp_fu_1008_p_dout0;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        val_2_reg_438 <= linsys_solver_bp_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln245_reg_852 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        addr_cmp_reg_871 <= addr_cmp_fu_599_p2;
        linsys_solver_bp_addr_3_reg_866 <= zext_ln246_fu_591_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_3_reg_818 <= i_3_fu_545_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        icmp_ln17_reg_974 <= icmp_ln17_fu_714_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln245_reg_852 <= icmp_ln245_fu_586_p2;
        icmp_ln245_reg_852_pp0_iter1_reg <= icmp_ln245_reg_852;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        icmp_ln261_reg_940 <= icmp_ln261_fu_686_p2;
        icmp_ln261_reg_940_pp2_iter1_reg <= icmp_ln261_reg_940;
        icmp_ln261_reg_940_pp2_iter2_reg <= icmp_ln261_reg_940_pp2_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln279_reg_891 <= icmp_ln279_fu_637_p2;
        icmp_ln279_reg_891_pp1_iter1_reg <= icmp_ln279_reg_891;
        linsys_solver_bp_addr_2_reg_900_pp1_iter1_reg <= linsys_solver_bp_addr_2_reg_900;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        icmp_ln279_reg_891_pp1_iter2_reg <= icmp_ln279_reg_891_pp1_iter1_reg;
        icmp_ln279_reg_891_pp1_iter3_reg <= icmp_ln279_reg_891_pp1_iter2_reg;
        icmp_ln279_reg_891_pp1_iter4_reg <= icmp_ln279_reg_891_pp1_iter3_reg;
        icmp_ln279_reg_891_pp1_iter5_reg <= icmp_ln279_reg_891_pp1_iter4_reg;
        linsys_solver_bp_addr_2_reg_900_pp1_iter2_reg <= linsys_solver_bp_addr_2_reg_900_pp1_iter1_reg;
        linsys_solver_bp_addr_2_reg_900_pp1_iter3_reg <= linsys_solver_bp_addr_2_reg_900_pp1_iter2_reg;
        linsys_solver_bp_addr_2_reg_900_pp1_iter4_reg <= linsys_solver_bp_addr_2_reg_900_pp1_iter3_reg;
        linsys_solver_bp_addr_2_reg_900_pp1_iter5_reg <= linsys_solver_bp_addr_2_reg_900_pp1_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        icmp_ln37_reg_993 <= icmp_ln37_fu_737_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0_11001))) begin
        icmp_ln41_reg_1012 <= icmp_ln41_fu_754_p2;
        icmp_ln41_reg_1012_pp5_iter1_reg <= icmp_ln41_reg_1012;
        work_xz_tilde_addr_2_reg_1026_pp5_iter1_reg <= work_xz_tilde_addr_2_reg_1026;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp5_stage0_11001)) begin
        icmp_ln41_reg_1012_pp5_iter10_reg <= icmp_ln41_reg_1012_pp5_iter9_reg;
        icmp_ln41_reg_1012_pp5_iter2_reg <= icmp_ln41_reg_1012_pp5_iter1_reg;
        icmp_ln41_reg_1012_pp5_iter3_reg <= icmp_ln41_reg_1012_pp5_iter2_reg;
        icmp_ln41_reg_1012_pp5_iter4_reg <= icmp_ln41_reg_1012_pp5_iter3_reg;
        icmp_ln41_reg_1012_pp5_iter5_reg <= icmp_ln41_reg_1012_pp5_iter4_reg;
        icmp_ln41_reg_1012_pp5_iter6_reg <= icmp_ln41_reg_1012_pp5_iter5_reg;
        icmp_ln41_reg_1012_pp5_iter7_reg <= icmp_ln41_reg_1012_pp5_iter6_reg;
        icmp_ln41_reg_1012_pp5_iter8_reg <= icmp_ln41_reg_1012_pp5_iter7_reg;
        icmp_ln41_reg_1012_pp5_iter9_reg <= icmp_ln41_reg_1012_pp5_iter8_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter10_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter9_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter2_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter1_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter3_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter2_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter4_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter3_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter5_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter4_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter6_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter5_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter7_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter6_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter8_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter7_reg;
        work_xz_tilde_addr_2_reg_1026_pp5_iter9_reg <= work_xz_tilde_addr_2_reg_1026_pp5_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_737_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001))) begin
        j_04_cast_reg_997[3 : 0] <= j_04_cast_fu_743_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln261_reg_940 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_11001))) begin
        j_13_reg_959 <= j_13_fu_696_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        j_1_reg_795 <= j_1_fu_523_p2;
        zext_ln12_reg_800[5 : 0] <= zext_ln12_fu_529_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (icmp_ln245_reg_852 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        j_4_reg_881 <= j_4_fu_620_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln279_reg_891 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        linsys_solver_Dinv_load_reg_906 <= linsys_solver_Dinv_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln279_fu_637_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        linsys_solver_bp_addr_2_reg_900 <= i_1_cast_fu_643_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        linsys_solver_bp_addr_3_reg_866_pp0_iter1_reg <= linsys_solver_bp_addr_3_reg_866;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_649_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        linsys_solver_bp_addr_4_reg_915 <= zext_ln259_fu_657_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_1012 == 1'd0) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0_11001))) begin
        linsys_solver_rho_inv_vec_load_reg_1032 <= linsys_solver_rho_inv_vec_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp5_iter1 == 1'b1) & (icmp_ln41_reg_1012 == 1'd0) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0_11001))) begin
        linsys_solver_sol_load_1_reg_1037 <= linsys_solver_sol_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln261_reg_940 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln245_reg_852 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        reg_499 <= linsys_solver_L_x_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln41_reg_1012_pp5_iter4_reg == 1'd0) & (ap_enable_reg_pp5_iter5 == 1'b1) & (1'b0 == ap_block_pp5_stage0_11001)) | ((icmp_ln261_reg_940_pp2_iter1_reg == 1'd1) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2) & (1'b0 == ap_block_pp2_stage2_11001)) | ((icmp_ln279_reg_891_pp1_iter4_reg == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (icmp_ln245_reg_852 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001)))) begin
        reg_510 <= grp_fu_1020_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln41_reg_1012_pp5_iter9_reg == 1'd0) & (ap_enable_reg_pp5_iter10 == 1'b1) & (1'b0 == ap_block_pp5_stage0_11001)) | ((icmp_ln261_reg_940_pp2_iter2_reg == 1'd1) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_11001)) | ((icmp_ln245_reg_852_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001)))) begin
        reg_516 <= grp_fu_1008_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (icmp_ln245_reg_852 == 1'd1) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        reuse_select_reg_876 <= reuse_select_fu_613_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_fu_754_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0_11001))) begin
        work_xz_tilde_addr_2_reg_1026 <= zext_ln42_fu_775_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln41_reg_1012_pp5_iter4_reg == 1'd0) & (ap_enable_reg_pp5_iter5 == 1'b1) & (1'b0 == ap_block_pp5_stage0_11001))) begin
        work_xz_tilde_load_1_reg_1042 <= work_xz_tilde_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        zext_ln245_reg_847[5 : 0] <= zext_ln245_fu_582_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        zext_ln261_reg_935[5 : 0] <= zext_ln261_fu_682_p1[5 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln245_fu_586_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln279_fu_637_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state20 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state20 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_condition_pp2_exit_iter1_state36 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter1_state36 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln261_reg_940 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_subdone))) begin
        ap_condition_pp2_flush_enable = 1'b1;
    end else begin
        ap_condition_pp2_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln17_fu_714_p2 == 1'd1)) begin
        ap_condition_pp3_exit_iter0_state43 = 1'b1;
    end else begin
        ap_condition_pp3_exit_iter0_state43 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln37_fu_737_p2 == 1'd1)) begin
        ap_condition_pp4_exit_iter0_state46 = 1'b1;
    end else begin
        ap_condition_pp4_exit_iter0_state46 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln41_fu_754_p2 == 1'd1)) begin
        ap_condition_pp5_exit_iter0_state49 = 1'b1;
    end else begin
        ap_condition_pp5_exit_iter0_state49 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state61) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b0) & (ap_enable_reg_pp3_iter0 == 1'b0))) begin
        ap_idle_pp3 = 1'b1;
    end else begin
        ap_idle_pp3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp4_iter1 == 1'b0) & (ap_enable_reg_pp4_iter0 == 1'b0))) begin
        ap_idle_pp4 = 1'b1;
    end else begin
        ap_idle_pp4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter11 == 1'b0) & (ap_enable_reg_pp5_iter9 == 1'b0) & (ap_enable_reg_pp5_iter8 == 1'b0) & (ap_enable_reg_pp5_iter7 == 1'b0) & (ap_enable_reg_pp5_iter6 == 1'b0) & (ap_enable_reg_pp5_iter4 == 1'b0) & (ap_enable_reg_pp5_iter3 == 1'b0) & (ap_enable_reg_pp5_iter2 == 1'b0) & (ap_enable_reg_pp5_iter1 == 1'b0) & (ap_enable_reg_pp5_iter0 == 1'b0) & (ap_enable_reg_pp5_iter10 == 1'b0) & (ap_enable_reg_pp5_iter5 == 1'b0))) begin
        ap_idle_pp5 = 1'b1;
    end else begin
        ap_idle_pp5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln245_reg_852 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_j_3_phi_fu_394_p4 = j_4_reg_881;
    end else begin
        ap_phi_mux_j_3_phi_fu_394_p4 = j_3_reg_391;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b1) & (icmp_ln261_reg_940 == 1'd1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        ap_phi_mux_j_6_phi_fu_429_p4 = j_13_reg_959;
    end else begin
        ap_phi_mux_j_6_phi_fu_429_p4 = j_6_reg_426;
    end
end

always @ (*) begin
    if (((icmp_ln261_reg_940_pp2_iter2_reg == 1'd1) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3))) begin
        ap_phi_mux_val_2_phi_fu_442_p4 = grp_fu_1008_p_dout0;
    end else begin
        ap_phi_mux_val_2_phi_fu_442_p4 = val_2_reg_438;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln245_reg_852_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5))) begin
        ap_sig_allocacmp_reuse_reg_load = reg_516;
    end else begin
        ap_sig_allocacmp_reuse_reg_load = reuse_reg_fu_106;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln245_reg_852 == 1'd1) & (1'b0 == ap_block_pp0_stage0_00001)) | ((icmp_ln261_reg_940_pp2_iter1_reg == 1'd1) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_00001)))) begin
        grp_fu_482_opcode = 2'd1;
    end else if (((ap_enable_reg_pp5_iter6 == 1'b1) & (icmp_ln41_reg_1012_pp5_iter5_reg == 1'd0) & (1'b0 == ap_block_pp5_stage0_00001))) begin
        grp_fu_482_opcode = 2'd0;
    end else begin
        grp_fu_482_opcode = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter6 == 1'b1) & (1'b0 == ap_block_pp5_stage0))) begin
        grp_fu_482_p0 = work_xz_tilde_load_1_reg_1042;
    end else if (((ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3))) begin
        grp_fu_482_p0 = ap_phi_mux_val_2_phi_fu_442_p4;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        grp_fu_482_p0 = reuse_select_reg_876;
    end else begin
        grp_fu_482_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter2 == 1'b1) & (1'b0 == ap_block_pp5_stage0))) begin
        grp_fu_487_p0 = linsys_solver_rho_inv_vec_load_reg_1032;
    end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        grp_fu_487_p0 = reg_491;
    end else if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3)))) begin
        grp_fu_487_p0 = reg_499;
    end else begin
        grp_fu_487_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter2 == 1'b1) & (1'b0 == ap_block_pp5_stage0))) begin
        grp_fu_487_p1 = linsys_solver_sol_load_1_reg_1037;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3))) begin
        grp_fu_487_p1 = reg_504;
    end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        grp_fu_487_p1 = linsys_solver_Dinv_load_reg_906;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_487_p1 = reg_491;
    end else begin
        grp_fu_487_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        linsys_solver_Dinv_ce0 = 1'b1;
    end else begin
        linsys_solver_Dinv_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        linsys_solver_L_i_address0 = ap_phi_mux_j_6_phi_fu_429_p4;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        linsys_solver_L_i_address0 = ap_phi_mux_j_3_phi_fu_394_p4;
    end else begin
        linsys_solver_L_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        linsys_solver_L_i_ce0 = 1'b1;
    end else begin
        linsys_solver_L_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        linsys_solver_L_p_address0 = add_i7_i_i_cast_fu_673_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linsys_solver_L_p_address0 = i_3_cast_fu_563_p1;
    end else begin
        linsys_solver_L_p_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        linsys_solver_L_p_address1 = zext_ln259_fu_657_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linsys_solver_L_p_address1 = zext_ln243_fu_557_p1;
    end else begin
        linsys_solver_L_p_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state5))) begin
        linsys_solver_L_p_ce0 = 1'b1;
    end else begin
        linsys_solver_L_p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state5))) begin
        linsys_solver_L_p_ce1 = 1'b1;
    end else begin
        linsys_solver_L_p_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0))) begin
        linsys_solver_L_x_address0 = ap_phi_mux_j_6_phi_fu_429_p4;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        linsys_solver_L_x_address0 = ap_phi_mux_j_3_phi_fu_394_p4;
    end else begin
        linsys_solver_L_x_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        linsys_solver_L_x_ce0 = 1'b1;
    end else begin
        linsys_solver_L_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        linsys_solver_P_address0 = j_8_cast_fu_720_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        linsys_solver_P_address0 = zext_ln12_fu_529_p1;
    end else begin
        linsys_solver_P_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)))) begin
        linsys_solver_P_ce0 = 1'b1;
    end else begin
        linsys_solver_P_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter6 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        linsys_solver_bp_address0 = linsys_solver_bp_addr_2_reg_900_pp1_iter5_reg;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5))) begin
        linsys_solver_bp_address0 = linsys_solver_bp_addr_3_reg_866_pp0_iter1_reg;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1))) begin
        linsys_solver_bp_address0 = zext_ln246_fu_591_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        linsys_solver_bp_address0 = zext_ln243_fu_557_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linsys_solver_bp_address0 = zext_ln12_reg_800;
    end else begin
        linsys_solver_bp_address0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        linsys_solver_bp_address1 = j_8_cast_fu_720_p1;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        linsys_solver_bp_address1 = linsys_solver_bp_addr_4_reg_915;
    end else if (((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1))) begin
        linsys_solver_bp_address1 = zext_ln262_fu_691_p1;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        linsys_solver_bp_address1 = zext_ln259_fu_657_p1;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0))) begin
        linsys_solver_bp_address1 = i_1_cast_fu_643_p1;
    end else begin
        linsys_solver_bp_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state5) | ((ap_enable_reg_pp1_iter6 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        linsys_solver_bp_ce0 = 1'b1;
    end else begin
        linsys_solver_bp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state28) | ((ap_enable_reg_pp3_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (1'b0 == ap_block_pp2_stage1_11001)))) begin
        linsys_solver_bp_ce1 = 1'b1;
    end else begin
        linsys_solver_bp_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter6 == 1'b1) & (1'b0 == ap_block_pp1_stage0))) begin
        linsys_solver_bp_d0 = reg_510;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5))) begin
        linsys_solver_bp_d0 = reg_516;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        linsys_solver_bp_d0 = work_xz_tilde_q0;
    end else begin
        linsys_solver_bp_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_enable_reg_pp1_iter6 == 1'b1) & (icmp_ln279_reg_891_pp1_iter5_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((icmp_ln245_reg_852_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)))) begin
        linsys_solver_bp_we0 = 1'b1;
    end else begin
        linsys_solver_bp_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        linsys_solver_bp_we1 = 1'b1;
    end else begin
        linsys_solver_bp_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0_11001))) begin
        linsys_solver_rho_inv_vec_ce0 = 1'b1;
    end else begin
        linsys_solver_rho_inv_vec_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0))) begin
        linsys_solver_sol_address0 = zext_ln42_fu_775_p1;
    end else if (((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0))) begin
        linsys_solver_sol_address0 = j_04_cast_fu_743_p1;
    end else if (((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0))) begin
        linsys_solver_sol_address0 = zext_ln17_fu_726_p1;
    end else begin
        linsys_solver_sol_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp3_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001)) | ((ap_enable_reg_pp5_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp5_stage0) & (1'b0 == ap_block_pp5_stage0_11001)) | ((ap_enable_reg_pp4_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001)))) begin
        linsys_solver_sol_ce0 = 1'b1;
    end else begin
        linsys_solver_sol_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp3_iter1 == 1'b1) & (icmp_ln17_reg_974 == 1'd0) & (1'b1 == ap_CS_fsm_pp3_stage0) & (1'b0 == ap_block_pp3_stage0_11001))) begin
        linsys_solver_sol_we0 = 1'b1;
    end else begin
        linsys_solver_sol_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter11 == 1'b1) & (1'b0 == ap_block_pp5_stage0))) begin
        work_xz_tilde_address0 = work_xz_tilde_addr_2_reg_1026_pp5_iter10_reg;
    end else if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0))) begin
        work_xz_tilde_address0 = j_04_cast_reg_997;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        work_xz_tilde_address0 = zext_ln12_1_fu_540_p1;
    end else begin
        work_xz_tilde_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_enable_reg_pp5_iter11 == 1'b1) & (1'b0 == ap_block_pp5_stage0_11001)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001)))) begin
        work_xz_tilde_ce0 = 1'b1;
    end else begin
        work_xz_tilde_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter4 == 1'b1) & (1'b0 == ap_block_pp5_stage0_11001))) begin
        work_xz_tilde_ce1 = 1'b1;
    end else begin
        work_xz_tilde_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp5_iter11 == 1'b1) & (1'b0 == ap_block_pp5_stage0))) begin
        work_xz_tilde_d0 = reg_516;
    end else if (((ap_enable_reg_pp4_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0))) begin
        work_xz_tilde_d0 = linsys_solver_sol_q0;
    end else begin
        work_xz_tilde_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp5_iter11 == 1'b1) & (icmp_ln41_reg_1012_pp5_iter10_reg == 1'd0) & (1'b0 == ap_block_pp5_stage0_11001)) | ((ap_enable_reg_pp4_iter1 == 1'b1) & (icmp_ln37_reg_993 == 1'd0) & (1'b1 == ap_CS_fsm_pp4_stage0) & (1'b0 == ap_block_pp4_stage0_11001)))) begin
        work_xz_tilde_we0 = 1'b1;
    end else begin
        work_xz_tilde_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln12_fu_534_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln243_fu_551_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln245_fu_586_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((icmp_ln245_fu_586_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage5_subdone)) & (1'b0 == ap_block_pp0_stage5_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage5_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((icmp_ln279_fu_637_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone)) & ~((ap_enable_reg_pp1_iter6 == 1'b1) & (ap_enable_reg_pp1_iter5 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter6 == 1'b1) & (ap_enable_reg_pp1_iter5 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone)) | ((icmp_ln279_fu_637_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((tmp_fu_649_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_pp2_stage1 : begin
            if ((1'b0 == ap_block_pp2_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end
        end
        ap_ST_fsm_pp2_stage2 : begin
            if ((~((ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp2_stage2) & (1'b0 == ap_block_pp2_stage2_subdone)) & (1'b0 == ap_block_pp2_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end else if (((ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (ap_enable_reg_pp2_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp2_stage2) & (1'b0 == ap_block_pp2_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end
        end
        ap_ST_fsm_pp2_stage3 : begin
            if ((~((1'b1 == ap_condition_pp2_exit_iter1_state36) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_subdone)) & (1'b0 == ap_block_pp2_stage3_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b1 == ap_condition_pp2_exit_iter1_state36) & (1'b1 == ap_CS_fsm_pp2_stage3) & (1'b0 == ap_block_pp2_stage3_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_pp3_stage0 : begin
            if (~((icmp_ln17_fu_714_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end else if (((icmp_ln17_fu_714_p2 == 1'd1) & (ap_enable_reg_pp3_iter0 == 1'b1) & (1'b0 == ap_block_pp3_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state45;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp3_stage0;
            end
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_pp4_stage0;
        end
        ap_ST_fsm_pp4_stage0 : begin
            if (~((icmp_ln37_fu_737_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end else if (((icmp_ln37_fu_737_p2 == 1'd1) & (ap_enable_reg_pp4_iter0 == 1'b1) & (1'b0 == ap_block_pp4_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp4_stage0;
            end
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_pp5_stage0;
        end
        ap_ST_fsm_pp5_stage0 : begin
            if ((~((ap_enable_reg_pp5_iter1 == 1'b0) & (icmp_ln41_fu_754_p2 == 1'd1) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b0 == ap_block_pp5_stage0_subdone)) & ~((ap_enable_reg_pp5_iter11 == 1'b1) & (ap_enable_reg_pp5_iter10 == 1'b0) & (1'b0 == ap_block_pp5_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end else if ((((ap_enable_reg_pp5_iter11 == 1'b1) & (ap_enable_reg_pp5_iter10 == 1'b0) & (1'b0 == ap_block_pp5_stage0_subdone)) | ((ap_enable_reg_pp5_iter1 == 1'b0) & (icmp_ln41_fu_754_p2 == 1'd1) & (ap_enable_reg_pp5_iter0 == 1'b1) & (1'b0 == ap_block_pp5_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state61;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp5_stage0;
            end
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i7_i_i_cast_fu_673_p1 = add_i7_i_i_fu_667_p2;

assign add_i7_i_i_fu_667_p2 = (trunc_ln259_fu_663_p1 + 6'd1);

assign add_ln42_fu_769_p2 = (j_11_cast_fu_765_p1 + 6'd15);

assign addr_cmp_fu_599_p2 = ((reuse_addr_reg_fu_102 == zext_ln246_fu_591_p1) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_pp2_stage1 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_pp2_stage2 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_pp2_stage3 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_pp3_stage0 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_pp4_stage0 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_pp5_stage0 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd27];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp3_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp4_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp5_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp2_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp2_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp2_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp2_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp2_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp2_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp2_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp2_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp2_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp3_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp3_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp4_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp4_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp5_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp5_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp5_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp5_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp5_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp5_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp5_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp5_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp5_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp5_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp5_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp5_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_enable_pp3 = (ap_idle_pp3 ^ 1'b1);

assign ap_enable_pp4 = (ap_idle_pp4 ^ 1'b1);

assign ap_enable_pp5 = (ap_idle_pp5 ^ 1'b1);

assign grp_fu_1008_p_ce = 1'b1;

assign grp_fu_1008_p_din0 = grp_fu_482_p0;

assign grp_fu_1008_p_din1 = reg_510;

assign grp_fu_1008_p_opcode = grp_fu_482_opcode;

assign grp_fu_1020_p_ce = 1'b1;

assign grp_fu_1020_p_din0 = grp_fu_487_p0;

assign grp_fu_1020_p_din1 = grp_fu_487_p1;

assign grp_fu_482_ce = 1'b1;

assign grp_fu_482_p1 = reg_510;

assign grp_fu_482_p2 = grp_fu_1008_p_dout0;

assign grp_fu_487_ce = 1'b1;

assign grp_fu_487_p2 = grp_fu_1020_p_dout0;

assign i_1_cast_fu_643_p1 = i_1_reg_403;

assign i_2_fu_631_p2 = (i_1_reg_403 + 6'd1);

assign i_3_cast_fu_563_p1 = i_3_fu_545_p2;

assign i_3_fu_545_p2 = (i_reg_380 + 6'd1);

assign i_5_fu_702_p2 = ($signed(i_4_reg_414) + $signed(7'd127));

assign icmp_ln12_fu_534_p2 = ((j_reg_369 == 6'd34) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_714_p2 = ((j_8_reg_449 == 6'd34) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_551_p2 = ((i_reg_380 == 6'd34) ? 1'b1 : 1'b0);

assign icmp_ln245_fu_586_p2 = (($signed(ap_phi_mux_j_3_phi_fu_394_p4) < $signed(zext_ln245_reg_847)) ? 1'b1 : 1'b0);

assign icmp_ln261_fu_686_p2 = (($signed(ap_phi_mux_j_6_phi_fu_429_p4) < $signed(zext_ln261_reg_935)) ? 1'b1 : 1'b0);

assign icmp_ln279_fu_637_p2 = ((i_1_reg_403 == 6'd34) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_737_p2 = ((j_04_reg_460 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_754_p2 = ((j_11_reg_471 == 5'd19) ? 1'b1 : 1'b0);

assign j_04_cast_fu_743_p1 = j_04_reg_460;

assign j_11_cast2_fu_760_p1 = j_11_reg_471;

assign j_11_cast_fu_765_p1 = j_11_reg_471;

assign j_13_fu_696_p2 = (j_6_reg_426 + 64'd1);

assign j_14_fu_731_p2 = (j_04_reg_460 + 4'd1);

assign j_15_fu_748_p2 = (j_11_reg_471 + 5'd1);

assign j_1_fu_523_p2 = (j_reg_369 + 6'd1);

assign j_4_fu_620_p2 = (j_3_reg_391 + 64'd1);

assign j_8_cast_fu_720_p1 = j_8_reg_449;

assign j_9_fu_708_p2 = (j_8_reg_449 + 6'd1);

assign linsys_solver_Dinv_address0 = i_1_cast_fu_643_p1;

assign linsys_solver_rho_inv_vec_address0 = j_11_cast2_fu_760_p1;

assign reuse_select_fu_613_p3 = ((addr_cmp_reg_871[0:0] == 1'b1) ? ap_sig_allocacmp_reuse_reg_load : reg_504);

assign tmp_fu_649_p3 = i_4_reg_414[32'd6];

assign trunc_ln259_fu_663_p1 = i_4_reg_414[5:0];

assign work_xz_tilde_address1 = work_xz_tilde_addr_2_reg_1026_pp5_iter3_reg;

assign zext_ln12_1_fu_540_p1 = linsys_solver_P_q0;

assign zext_ln12_fu_529_p1 = j_reg_369;

assign zext_ln17_fu_726_p1 = linsys_solver_P_q0;

assign zext_ln242_fu_578_p1 = linsys_solver_L_p_q1;

assign zext_ln243_fu_557_p1 = i_reg_380;

assign zext_ln245_fu_582_p1 = linsys_solver_L_p_q0;

assign zext_ln246_fu_591_p1 = linsys_solver_L_i_q0;

assign zext_ln258_fu_678_p1 = linsys_solver_L_p_q1;

assign zext_ln259_fu_657_p1 = i_4_reg_414;

assign zext_ln261_fu_682_p1 = linsys_solver_L_p_q0;

assign zext_ln262_fu_691_p1 = linsys_solver_L_i_q0;

assign zext_ln42_fu_775_p1 = add_ln42_fu_769_p2;

always @ (posedge ap_clk) begin
    zext_ln12_reg_800[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln245_reg_847[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    zext_ln261_reg_935[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    j_04_cast_reg_997[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //myFunction_solve_linsys_qdldl
