// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myFunction_is_dual_infeasible (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        eps_dual_inf,
        work_delta_x_address0,
        work_delta_x_ce0,
        work_delta_x_q0,
        qdata_address0,
        qdata_ce0,
        qdata_q0,
        grp_fu_350_p_din0,
        grp_fu_350_p_din1,
        grp_fu_350_p_dout0,
        grp_fu_350_p_ce,
        grp_fu_359_p_din0,
        grp_fu_359_p_din1,
        grp_fu_359_p_opcode,
        grp_fu_359_p_dout0,
        grp_fu_359_p_ce
);

parameter    ap_ST_fsm_state1 = 26'd1;
parameter    ap_ST_fsm_state2 = 26'd2;
parameter    ap_ST_fsm_state3 = 26'd4;
parameter    ap_ST_fsm_state4 = 26'd8;
parameter    ap_ST_fsm_state5 = 26'd16;
parameter    ap_ST_fsm_state6 = 26'd32;
parameter    ap_ST_fsm_state7 = 26'd64;
parameter    ap_ST_fsm_state8 = 26'd128;
parameter    ap_ST_fsm_state9 = 26'd256;
parameter    ap_ST_fsm_state10 = 26'd512;
parameter    ap_ST_fsm_state11 = 26'd1024;
parameter    ap_ST_fsm_state12 = 26'd2048;
parameter    ap_ST_fsm_state13 = 26'd4096;
parameter    ap_ST_fsm_state14 = 26'd8192;
parameter    ap_ST_fsm_state15 = 26'd16384;
parameter    ap_ST_fsm_state16 = 26'd32768;
parameter    ap_ST_fsm_state17 = 26'd65536;
parameter    ap_ST_fsm_state18 = 26'd131072;
parameter    ap_ST_fsm_state19 = 26'd262144;
parameter    ap_ST_fsm_state20 = 26'd524288;
parameter    ap_ST_fsm_state21 = 26'd1048576;
parameter    ap_ST_fsm_state22 = 26'd2097152;
parameter    ap_ST_fsm_state23 = 26'd4194304;
parameter    ap_ST_fsm_state24 = 26'd8388608;
parameter    ap_ST_fsm_state25 = 26'd16777216;
parameter    ap_ST_fsm_state26 = 26'd33554432;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] eps_dual_inf;
output  [3:0] work_delta_x_address0;
output   work_delta_x_ce0;
input  [31:0] work_delta_x_q0;
output  [3:0] qdata_address0;
output   qdata_ce0;
input  [31:0] qdata_q0;
output  [31:0] grp_fu_350_p_din0;
output  [31:0] grp_fu_350_p_din1;
input  [31:0] grp_fu_350_p_dout0;
output   grp_fu_350_p_ce;
output  [31:0] grp_fu_359_p_din0;
output  [31:0] grp_fu_359_p_din1;
output  [4:0] grp_fu_359_p_opcode;
input  [0:0] grp_fu_359_p_dout0;
output   grp_fu_359_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] work_delta_x_address0;
reg work_delta_x_ce0;
reg qdata_ce0;

(* fsm_encoding = "none" *) reg   [25:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_148;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_134_p2;
reg   [31:0] reg_154;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state23;
wire   [3:0] i_69_fu_159_p2;
reg   [3:0] i_69_reg_484;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln14_fu_170_p2;
wire   [31:0] abs_v_i_fu_228_p3;
reg   [31:0] abs_v_i_reg_497;
wire    ap_CS_fsm_state5;
wire   [31:0] max_9_fu_319_p3;
wire    ap_CS_fsm_state7;
wire   [0:0] and_ln158_fu_362_p2;
reg   [0:0] and_ln158_reg_509;
wire    ap_CS_fsm_state8;
wire   [3:0] i_71_fu_368_p2;
reg   [3:0] i_71_reg_513;
wire    ap_CS_fsm_state9;
wire   [0:0] icmp_ln49_fu_380_p2;
wire   [0:0] icmp_ln49_1_fu_386_p2;
reg   [0:0] icmp_ln49_1_reg_531;
reg   [31:0] qdata_load_reg_536;
wire   [31:0] grp_fu_392_p3;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln159_fu_435_p2;
reg   [0:0] icmp_ln159_reg_546;
wire    ap_CS_fsm_state24;
wire   [0:0] icmp_ln159_1_fu_441_p2;
reg   [0:0] icmp_ln159_1_reg_551;
wire   [0:0] icmp_ln159_2_fu_447_p2;
reg   [0:0] icmp_ln159_2_reg_556;
wire   [0:0] icmp_ln159_3_fu_453_p2;
reg   [0:0] icmp_ln159_3_reg_561;
reg   [31:0] max_reg_88;
reg   [3:0] i_reg_100;
reg   [3:0] i_70_reg_111;
reg   [31:0] prod_reg_122;
wire   [63:0] zext_ln14_fu_165_p1;
wire   [63:0] zext_ln49_fu_374_p1;
reg   [31:0] grp_fu_134_p0;
reg   [31:0] grp_fu_134_p1;
wire    ap_CS_fsm_state11;
reg   [31:0] grp_fu_139_p0;
reg   [31:0] grp_fu_139_p1;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire   [31:0] bitcast_ln14_fu_176_p1;
wire   [7:0] tmp_40_fu_180_p4;
wire   [22:0] trunc_ln14_fu_190_p1;
wire   [0:0] icmp_ln14_20_fu_200_p2;
wire   [0:0] icmp_ln14_19_fu_194_p2;
wire   [0:0] or_ln14_fu_206_p2;
wire   [0:0] grp_fu_139_p2;
wire   [31:0] xor_ln14_fu_218_p2;
wire   [0:0] and_ln14_fu_212_p2;
wire   [31:0] bitcast_ln14_5_fu_224_p1;
wire   [31:0] bitcast_ln14_10_fu_236_p1;
wire   [31:0] bitcast_ln14_11_fu_253_p1;
wire   [7:0] tmp_42_fu_239_p4;
wire   [22:0] trunc_ln14_8_fu_249_p1;
wire   [0:0] icmp_ln14_22_fu_277_p2;
wire   [0:0] icmp_ln14_21_fu_271_p2;
wire   [7:0] tmp_43_fu_257_p4;
wire   [22:0] trunc_ln14_9_fu_267_p1;
wire   [0:0] icmp_ln14_24_fu_295_p2;
wire   [0:0] icmp_ln14_23_fu_289_p2;
wire   [0:0] or_ln14_8_fu_283_p2;
wire   [0:0] or_ln14_9_fu_301_p2;
wire   [0:0] and_ln14_8_fu_307_p2;
wire   [0:0] and_ln14_9_fu_313_p2;
wire   [31:0] bitcast_ln158_fu_326_p1;
wire   [7:0] tmp_fu_330_p4;
wire   [22:0] trunc_ln158_fu_340_p1;
wire   [0:0] icmp_ln158_1_fu_350_p2;
wire   [0:0] icmp_ln158_fu_344_p2;
wire   [0:0] or_ln158_fu_356_p2;
wire    ap_CS_fsm_state15;
wire   [31:0] bitcast_ln159_fu_399_p1;
wire   [31:0] bitcast_ln159_1_fu_417_p1;
wire   [7:0] tmp_45_fu_403_p4;
wire   [22:0] trunc_ln159_fu_413_p1;
wire   [7:0] tmp_46_fu_421_p4;
wire   [22:0] trunc_ln159_1_fu_431_p1;
wire    ap_CS_fsm_state25;
wire   [0:0] or_ln159_fu_459_p2;
wire   [0:0] or_ln159_1_fu_463_p2;
wire   [0:0] and_ln159_fu_467_p2;
wire    grp_fu_134_ce;
wire    grp_fu_139_ce;
reg   [4:0] grp_fu_139_opcode;
reg    grp_fu_392_in_valid;
wire   [0:0] and_ln159_1_fu_473_p2;
reg   [25:0] ap_NS_fsm;
wire   [31:0] grp_fu_392_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 26'd1;
end

myFunction_facc_32ns_32ns_1ns_32_6_no_dsp_1 #(
    .DWIDTH( 32 ))
facc_32ns_32ns_1ns_32_6_no_dsp_1_U96(
    .clk(ap_clk),
    .reset(ap_rst),
    .ce(1'b1),
    .in_data(reg_154),
    .in_last(icmp_ln49_1_reg_531),
    .in_valid(grp_fu_392_in_valid),
    .out_data(grp_fu_392_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln158_fu_362_p2))) begin
        i_70_reg_111 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        i_70_reg_111 <= i_71_reg_513;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_reg_100 <= i_69_reg_484;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_100 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        max_reg_88 <= max_9_fu_319_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        max_reg_88 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln158_fu_362_p2))) begin
        prod_reg_122 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        prod_reg_122 <= grp_fu_392_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        abs_v_i_reg_497 <= abs_v_i_fu_228_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        and_ln158_reg_509 <= and_ln158_fu_362_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_69_reg_484 <= i_69_fu_159_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_71_reg_513 <= i_71_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        icmp_ln159_1_reg_551 <= icmp_ln159_1_fu_441_p2;
        icmp_ln159_2_reg_556 <= icmp_ln159_2_fu_447_p2;
        icmp_ln159_3_reg_561 <= icmp_ln159_3_fu_453_p2;
        icmp_ln159_reg_546 <= icmp_ln159_fu_435_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln49_fu_380_p2 == 1'd0))) begin
        icmp_ln49_1_reg_531 <= icmp_ln49_1_fu_386_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        qdata_load_reg_536 <= qdata_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_148 <= work_delta_x_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state14))) begin
        reg_154 <= grp_fu_350_p_dout0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state25) & ((1'd0 == and_ln159_1_fu_473_p2) | (1'd0 == and_ln158_reg_509))) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & ((1'd0 == and_ln159_1_fu_473_p2) | (1'd0 == and_ln158_reg_509)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_134_p0 = qdata_load_reg_536;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_134_p0 = max_reg_88;
    end else begin
        grp_fu_134_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_134_p1 = reg_148;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_134_p1 = eps_dual_inf;
    end else begin
        grp_fu_134_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state24))) begin
        grp_fu_139_opcode = 5'd4;
    end else if (((1'b1 == ap_CS_fsm_state6) | ((icmp_ln14_fu_170_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        grp_fu_139_opcode = 5'd2;
    end else begin
        grp_fu_139_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_139_p0 = prod_reg_122;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_139_p0 = abs_v_i_reg_497;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_139_p0 = reg_148;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_139_p0 = max_reg_88;
    end else begin
        grp_fu_139_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        grp_fu_139_p1 = reg_154;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_139_p1 = max_reg_88;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_139_p1 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_139_p1 = 32'd228737632;
    end else begin
        grp_fu_139_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_392_in_valid = 1'b1;
    end else begin
        grp_fu_392_in_valid = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        qdata_ce0 = 1'b1;
    end else begin
        qdata_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        work_delta_x_address0 = zext_ln49_fu_374_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        work_delta_x_address0 = zext_ln14_fu_165_p1;
    end else begin
        work_delta_x_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9))) begin
        work_delta_x_ce0 = 1'b1;
    end else begin
        work_delta_x_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln14_fu_170_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (1'd1 == and_ln158_fu_362_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (icmp_ln49_fu_380_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((1'b1 == ap_CS_fsm_state25) & ((1'd0 == and_ln159_1_fu_473_p2) | (1'd0 == and_ln158_reg_509)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_v_i_fu_228_p3 = ((and_ln14_fu_212_p2[0:0] == 1'b1) ? bitcast_ln14_5_fu_224_p1 : reg_148);

assign and_ln14_8_fu_307_p2 = (or_ln14_9_fu_301_p2 & or_ln14_8_fu_283_p2);

assign and_ln14_9_fu_313_p2 = (grp_fu_359_p_dout0 & and_ln14_8_fu_307_p2);

assign and_ln14_fu_212_p2 = (or_ln14_fu_206_p2 & grp_fu_359_p_dout0);

assign and_ln158_fu_362_p2 = (or_ln158_fu_356_p2 & grp_fu_359_p_dout0);

assign and_ln159_1_fu_473_p2 = (grp_fu_359_p_dout0 & and_ln159_fu_467_p2);

assign and_ln159_fu_467_p2 = (or_ln159_fu_459_p2 & or_ln159_1_fu_463_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln14_10_fu_236_p1 = abs_v_i_reg_497;

assign bitcast_ln14_11_fu_253_p1 = max_reg_88;

assign bitcast_ln14_5_fu_224_p1 = xor_ln14_fu_218_p2;

assign bitcast_ln14_fu_176_p1 = reg_148;

assign bitcast_ln158_fu_326_p1 = max_reg_88;

assign bitcast_ln159_1_fu_417_p1 = reg_154;

assign bitcast_ln159_fu_399_p1 = prod_reg_122;

assign grp_fu_134_ce = 1'b1;

assign grp_fu_134_p2 = grp_fu_350_p_dout0;

assign grp_fu_139_ce = 1'b1;

assign grp_fu_139_p2 = grp_fu_359_p_dout0;

assign grp_fu_350_p_ce = 1'b1;

assign grp_fu_350_p_din0 = grp_fu_134_p0;

assign grp_fu_350_p_din1 = grp_fu_134_p1;

assign grp_fu_359_p_ce = 1'b1;

assign grp_fu_359_p_din0 = grp_fu_139_p0;

assign grp_fu_359_p_din1 = grp_fu_139_p1;

assign grp_fu_359_p_opcode = grp_fu_139_opcode;

assign i_69_fu_159_p2 = (i_reg_100 + 4'd1);

assign i_71_fu_368_p2 = (i_70_reg_111 + 4'd1);

assign icmp_ln14_19_fu_194_p2 = ((tmp_40_fu_180_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_20_fu_200_p2 = ((trunc_ln14_fu_190_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_21_fu_271_p2 = ((tmp_42_fu_239_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_22_fu_277_p2 = ((trunc_ln14_8_fu_249_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_23_fu_289_p2 = ((tmp_43_fu_257_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln14_24_fu_295_p2 = ((trunc_ln14_9_fu_267_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln14_fu_170_p2 = ((i_reg_100 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln158_1_fu_350_p2 = ((trunc_ln158_fu_340_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln158_fu_344_p2 = ((tmp_fu_330_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln159_1_fu_441_p2 = ((trunc_ln159_fu_413_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln159_2_fu_447_p2 = ((tmp_46_fu_421_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln159_3_fu_453_p2 = ((trunc_ln159_1_fu_431_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln159_fu_435_p2 = ((tmp_45_fu_403_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln49_1_fu_386_p2 = ((i_71_fu_368_p2 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln49_fu_380_p2 = ((i_70_reg_111 == 4'd15) ? 1'b1 : 1'b0);

assign max_9_fu_319_p3 = ((and_ln14_9_fu_313_p2[0:0] == 1'b1) ? abs_v_i_reg_497 : max_reg_88);

assign or_ln14_8_fu_283_p2 = (icmp_ln14_22_fu_277_p2 | icmp_ln14_21_fu_271_p2);

assign or_ln14_9_fu_301_p2 = (icmp_ln14_24_fu_295_p2 | icmp_ln14_23_fu_289_p2);

assign or_ln14_fu_206_p2 = (icmp_ln14_20_fu_200_p2 | icmp_ln14_19_fu_194_p2);

assign or_ln158_fu_356_p2 = (icmp_ln158_fu_344_p2 | icmp_ln158_1_fu_350_p2);

assign or_ln159_1_fu_463_p2 = (icmp_ln159_3_reg_561 | icmp_ln159_2_reg_556);

assign or_ln159_fu_459_p2 = (icmp_ln159_reg_546 | icmp_ln159_1_reg_551);

assign qdata_address0 = zext_ln49_fu_374_p1;

assign tmp_40_fu_180_p4 = {{bitcast_ln14_fu_176_p1[30:23]}};

assign tmp_42_fu_239_p4 = {{bitcast_ln14_10_fu_236_p1[30:23]}};

assign tmp_43_fu_257_p4 = {{bitcast_ln14_11_fu_253_p1[30:23]}};

assign tmp_45_fu_403_p4 = {{bitcast_ln159_fu_399_p1[30:23]}};

assign tmp_46_fu_421_p4 = {{bitcast_ln159_1_fu_417_p1[30:23]}};

assign tmp_fu_330_p4 = {{bitcast_ln158_fu_326_p1[30:23]}};

assign trunc_ln14_8_fu_249_p1 = bitcast_ln14_10_fu_236_p1[22:0];

assign trunc_ln14_9_fu_267_p1 = bitcast_ln14_11_fu_253_p1[22:0];

assign trunc_ln14_fu_190_p1 = bitcast_ln14_fu_176_p1[22:0];

assign trunc_ln158_fu_340_p1 = bitcast_ln158_fu_326_p1[22:0];

assign trunc_ln159_1_fu_431_p1 = bitcast_ln159_1_fu_417_p1[22:0];

assign trunc_ln159_fu_413_p1 = bitcast_ln159_fu_399_p1[22:0];

assign xor_ln14_fu_218_p2 = (bitcast_ln14_fu_176_p1 ^ 32'd2147483648);

assign zext_ln14_fu_165_p1 = i_reg_100;

assign zext_ln49_fu_374_p1 = i_70_reg_111;

endmodule //myFunction_is_dual_infeasible
